global option to set log file

diff --git a/bin/awkLint b/bin/awkLint
--- a/bin/awkLint
+++ b/bin/awkLint
@@ -239,6 +239,51 @@ Log::displayInfo() {
   Log::logInfo "$1" "${type}"
 }
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables loaded by Env::requireLoad
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
+# @require Env::requireLoad
+# @require UI::requireTheme
+Log::requireLoad() {
+  if [[ -z "${BASH_FRAMEWORK_LOG_FILE:-}" ]]; then
+    BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
+    export BASH_FRAMEWORK_LOG_LEVEL
+  fi
+
+  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
+    if [[ ! -f "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
+      if
+        ! mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" 2>/dev/null ||
+          ! touch --no-create "${BASH_FRAMEWORK_LOG_FILE}" 2>/dev/null
+      then
+        BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
+        echo -e "${__ERROR_COLOR}ERROR   - File ${BASH_FRAMEWORK_LOG_FILE} is not writable${__RESET_COLOR}" >&2
+      fi
+    elif [[ ! -w "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
+      BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
+      echo -e "${__ERROR_COLOR}ERROR   - File ${BASH_FRAMEWORK_LOG_FILE} is not writable${__RESET_COLOR}" >&2
+    fi
+
+  fi
+
+  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
+    # will always be created even if not in info level
+    Log::logMessage "INFO" "Logging to file ${BASH_FRAMEWORK_LOG_FILE} - Log level ${BASH_FRAMEWORK_LOG_LEVEL}"
+    if ((BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION > 0)); then
+      Log::rotate "${BASH_FRAMEWORK_LOG_FILE}" "${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION}"
+    fi
+  fi
+}
+
 # @description load colors theme constants
 # @warning if tty not opened, noColor theme will be chosen
 # @arg $1 theme:String the theme to use (default, noColor)
@@ -390,6 +435,27 @@ Log::logMessage() {
   fi
 }
 
+# @description To be called before logging in the log file
+# @arg $1 file:string log file name
+# @arg $2 maxLogFilesCount:int maximum number of log files
+Log::rotate() {
+  local file="$1"
+  local maxLogFilesCount="${2:-5}"
+
+  if [[ ! -f "${file}" ]]; then
+    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    return 0
+  fi
+  for i in $(seq $((maxLogFilesCount - 1)) -1 1); do
+    Log::displayInfo "Log rotation ${file}.${i} to ${file}.$((i + 1))"
+    mv "${file}."{"${i}","$((i + 1))"} &>/dev/null || true
+  done
+  if cp "${file}" "${file}.1" &>/dev/null; then
+    echo >"${file}" # reset log file
+    Log::displayInfo "Log rotation ${file} to ${file}.1"
+  fi
+}
+
 # @description ensure env files are loaded
 # @noargs
 # @exitcode 1 if getOrderedConfFiles fails
@@ -415,49 +481,12 @@ Env::requireLoad() {
   }
 }
 
-# @description activate or not Log::display* and Log::log* functions
-# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
-# environment variables loaded by Env::requireLoad
-# try to create log file and rotate it if necessary
+# @description load color theme
 # @noargs
-# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
-# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
-# @env BASH_FRAMEWORK_LOG_LEVEL int
-# @env BASH_FRAMEWORK_LOG_FILE String
-# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @env BASH_FRAMEWORK_THEME String theme to use
 # @exitcode 0 always successful
-# @stderr diagnostics information about log file is displayed
-# @require Env::requireLoad
-# @require UI::requireTheme
-Log::requireLoad() {
-  if [[ -z "${BASH_FRAMEWORK_LOG_FILE:-}" ]]; then
-    BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
-    export BASH_FRAMEWORK_LOG_LEVEL
-  fi
-
-  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
-    if [[ ! -f "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
-      if
-        ! mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" 2>/dev/null ||
-          ! touch --no-create "${BASH_FRAMEWORK_LOG_FILE}" 2>/dev/null
-      then
-        BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
-        echo -e "${__ERROR_COLOR}ERROR   - File ${BASH_FRAMEWORK_LOG_FILE} is not writable${__RESET_COLOR}" >&2
-      fi
-    elif [[ ! -w "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
-      BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
-      echo -e "${__ERROR_COLOR}ERROR   - File ${BASH_FRAMEWORK_LOG_FILE} is not writable${__RESET_COLOR}" >&2
-    fi
-
-  fi
-
-  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
-    # will always be created even if not in info level
-    Log::logMessage "INFO" "Logging to file ${BASH_FRAMEWORK_LOG_FILE} - Log level ${BASH_FRAMEWORK_LOG_LEVEL}"
-    if ((BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION > 0)); then
-      Log::rotate "${BASH_FRAMEWORK_LOG_FILE}" "${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION}"
-    fi
-  fi
+UI::requireTheme() {
+  UI::theme "${BASH_FRAMEWORK_THEME-default}"
 }
 
 # @description get list of env files to load
@@ -562,35 +591,6 @@ Log::displaySkipped() {
     echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
-}
-
-# @description To be called before logging in the log file
-# @arg $1 file:string log file name
-# @arg $2 maxLogFilesCount:int maximum number of log files
-Log::rotate() {
-  local file="$1"
-  local maxLogFilesCount="${2:-5}"
-
-  if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
-    return 0
-  fi
-  for i in $(seq $((maxLogFilesCount - 1)) -1 1); do
-    Log::displayInfo "Log rotation ${file}.${i} to ${file}.$((i + 1))"
-    mv "${file}."{"${i}","$((i + 1))"} &>/dev/null || true
-  done
-  if cp "${file}" "${file}.1" &>/dev/null; then
-    echo >"${file}" # reset log file
-    Log::displayInfo "Log rotation ${file} to ${file}.1"
-  fi
-}
-
-# @description load color theme
-# @noargs
-# @env BASH_FRAMEWORK_THEME String theme to use
-# @exitcode 0 always successful
-UI::requireTheme() {
-  UI::theme "${BASH_FRAMEWORK_THEME-default}"
 }
 
 # @description default env file with all default values
@@ -790,8 +790,8 @@ FRAMEWORK_VENDOR_DIR="${FRAMEWORK_ROOT_DIR}/vendor"
 FRAMEWORK_VENDOR_BIN_DIR="${FRAMEWORK_ROOT_DIR}/vendor/bin"
 # REQUIRES
 Env::requireLoad
-Log::requireLoad
 UI::requireTheme
+Log::requireLoad
 Env::requireRemoveVerboseArg
 Compiler::Facade::requireCommandBinDir
 
@@ -888,12 +888,21 @@ optionLogLevelCallback() {
   export BASH_FRAMEWORK_LOG_LEVEL=${logLevel}
 }
 
+optionLogFileCallback() {
+  local logFile="$1"
+  export BASH_FRAMEWORK_LOG_FILE="${logFile}"
+}
+
 optionQuietCallback() {
   export BASH_FRAMEWORK_QUIET_MODE=1
 }
 
 optionNoColorCallback() {
   UI::theme "noColor"
+}
+
+commandOptionParseFinished() {
+  Log::requireLoad
 }
 
 awkLintCommand() {
@@ -915,6 +924,8 @@ awkLintCommand() {
     ((options_parse_optionParsedCountOptionQuiet = 0)) || true
     local -i options_parse_optionParsedCountOptionLogLevel
     ((options_parse_optionParsedCountOptionLogLevel = 0)) || true
+    local -i options_parse_optionParsedCountOptionLogFile
+    ((options_parse_optionParsedCountOptionLogFile = 0)) || true
     local -i options_parse_optionParsedCountOptionDisplayLevel
     ((options_parse_optionParsedCountOptionDisplayLevel = 0)) || true
     optionInfoVerbose="0"
@@ -930,7 +941,7 @@ awkLintCommand() {
     while (($# > 0)); do
       local options_parse_arg="$1"
       case "${options_parse_arg}" in
-        # Option 1/9
+        # Option 1/10
         # Option optionNoColor --no-color variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --no-color)
           optionNoColor="1"
@@ -940,7 +951,7 @@ awkLintCommand() {
           fi
           optionNoColorCallback "${optionNoColor}"
           ;;
-        # Option 2/9
+        # Option 2/10
         # Option optionHelp --help|-h variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --help | -h)
           optionHelp="1"
@@ -950,7 +961,7 @@ awkLintCommand() {
           fi
           optionHelpCallback "${optionHelp}"
           ;;
-        # Option 3/9
+        # Option 3/10
         # Option optionVersion --version variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --version)
           optionVersion="1"
@@ -960,7 +971,7 @@ awkLintCommand() {
           fi
           optionVersionCallback "${optionVersion}"
           ;;
-        # Option 4/9
+        # Option 4/10
         # Option optionQuiet --quiet|-q variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --quiet | -q)
           optionQuiet="1"
@@ -970,7 +981,7 @@ awkLintCommand() {
           fi
           optionQuietCallback "${optionQuiet}"
           ;;
-        # Option 5/9
+        # Option 5/10
         # Option optionLogLevel --log-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
         --log-level)
           shift
@@ -990,7 +1001,23 @@ awkLintCommand() {
           optionLogLevel="$1"
           optionLogLevelCallback "${optionLogLevel}"
           ;;
-        # Option 6/9
+        # Option 6/10
+        # Option optionLogFile --log-file variableType String min 0 max 1 authorizedValues '' regexp ''
+        --log-file)
+          shift
+          if (($# == 0)); then
+            Log::displayError "Option ${options_parse_arg} - a value needs to be specified"
+            return 1
+          fi
+          if ((options_parse_optionParsedCountOptionLogFile >= 1)); then
+            Log::displayError "Option ${options_parse_arg} - Maximum number of option occurrences reached(1)"
+            return 1
+          fi
+          ((++options_parse_optionParsedCountOptionLogFile))
+          optionLogFile="$1"
+          optionLogFileCallback "${optionLogFile}"
+          ;;
+        # Option 7/10
         # Option optionDisplayLevel --display-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
         --display-level)
           shift
@@ -1010,7 +1037,7 @@ awkLintCommand() {
           optionDisplayLevel="$1"
           optionDisplayLevelCallback "${optionDisplayLevel}"
           ;;
-        # Option 7/9
+        # Option 8/10
         # Option optionInfoVerbose --verbose|-v variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --verbose | -v)
           optionInfoVerbose="1"
@@ -1020,7 +1047,7 @@ awkLintCommand() {
           fi
           optionInfoVerboseCallback "${optionInfoVerbose}"
           ;;
-        # Option 8/9
+        # Option 9/10
         # Option optionDebugVerbose -vv variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         -vv)
           optionDebugVerbose="1"
@@ -1030,7 +1057,7 @@ awkLintCommand() {
           fi
           optionDebugVerboseCallback "${optionDebugVerbose}"
           ;;
-        # Option 9/9
+        # Option 10/10
         # Option optionTraceVerbose -vvv variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         -vvv)
           optionTraceVerbose="1"
@@ -1055,10 +1082,12 @@ awkLintCommand() {
     export optionVersion
     export optionQuiet
     export optionLogLevel
+    export optionLogFile
     export optionDisplayLevel
     export optionInfoVerbose
     export optionDebugVerbose
     export optionTraceVerbose
+    commandOptionParseFinished
   elif [[ "${options_parse_cmd}" = "help" ]]; then
     echo -e "$(Array::wrap " " 80 0 "${__HELP_TITLE_COLOR}Description:${__RESET_COLOR}" "lint awk files
 
@@ -1069,7 +1098,7 @@ Result in checkstyle format.")"
     echo -e "$(Array::wrap " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" "${SCRIPT_NAME}" "[OPTIONS]")"
     echo -e "$(Array::wrap " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" \
       "${SCRIPT_NAME}" \
-      "[--no-color]" "[--help|-h]" "[--version]" "[--quiet|-q]" "[--log-level <String>]" "[--display-level <String>]" "[--verbose|-v]" "[-vv]" "[-vvv]")"
+      "[--no-color]" "[--help|-h]" "[--version]" "[--quiet|-q]" "[--log-level <String>]" "[--log-file <String>]" "[--display-level <String>]" "[--verbose|-v]" "[-vv]" "[-vvv]")"
     echo
     echo -e "${__HELP_TITLE_COLOR}GLOBAL OPTIONS:${__RESET_COLOR}"
     echo -n -e "  ${__HELP_OPTION_COLOR}"
@@ -1108,6 +1137,14 @@ Result in checkstyle format.")"
     echo -n -e ' (at most 1 times)'
     echo
     echo "    Set log level (one of OFF, ERROR, WARNING, INFO, DEBUG, TRACE value)"
+    echo -n -e "  ${__HELP_OPTION_COLOR}"
+    echo -n "--log-file"
+    echo -n ' <String>'
+    echo -n -e "${__HELP_NORMAL}"
+    echo -n -e ' (optional)'
+    echo -n -e ' (at most 1 times)'
+    echo
+    echo "    Set log file"
     echo -n -e "  ${__HELP_OPTION_COLOR}"
     echo -n "--display-level"
     echo -n ' <String>'
