FACADE and IMPLEMENT directives (#24)
**Breaking changes:**

- Git::pullIfNoChanges exits with different codes instead of silently ignore errors
- Profiles::allDepsRecursive exits with different codes instead of silently ignore errors
- Profiles::loadProfile exits with different codes instead of silently ignore errors
- added Filters::removeAnsiCodes to replace UI::removeAnsiCode and Filters::escapeColorCodes
- Filters::bashFrameworkFunctions now namespace should begin with a capital letter
- moved Apt namespace to Linux/Apt namespace
- moved Sudo namespace to Linux/Sudo namespace
- moved Wsl namespace to Linux/Wsl namespace
- moved OS::getUbuntuCodename to Linux::getCodename
- removed Version::getCommandVersionFromJson in favor to Version::getCommandVersionFromPlainText

**Compiler changes:**

- stops if an error is found when bash-tpl is executed (eg.: .INCLUDE with file not found)
- new FACADE directive with activity diagram, functional and technical documentation
- new IMPLEMENT directive with activity diagram, functional and technical documentation
- new REQUIRE directive specifications (not yet finalized and implemented)
- moved Embed namespace under Compiler one
- clarified EMBED directive documentation with md5/base64 typo

**Binaries changes:**

- added `shopt -s inherit_errexit` in all scripts header
- added src/_includes/_mandatoryHeader.sh for some options to come earlier in the
  generated scripts
- src/_binaries/buildBinFiles.sh now use main function (facade principle)

**Updated framework functions:**

- securized File::garbageCollect to avoid that a complete directory could be erased
  by error because of variable not set or empty by limiting the default depth of
  deletion
- updated File::getAbsolutePath, now using realpath + UT
- Filters::directive now filters out the new directives IMPLEMENT, REQUIRE,
  COMPATIBILITY, EMBED, FACADE
- most of the filters (Filter namespace) can now use a file argument or stdin
- removed Acquire::ForceIPv4, added it to FRAMEWORK_FUNCTIONS_IGNORE_REGEXP
- ensure local is used in a lot of functions to avoid polluting parent script,
  and renamed local variables from uppercase to lowercase
- Version::checkMinimal fixed argument 5 typo

**New Bash framework functions:**

- added Linux::getDistributorId
- added Array::setArray
- added Compiler::Facade namespace
- added Compiler::Implement namespace
- added Crypto::uuidV4
- added Filters::trimString
- added several unit tests
- new require functions
  - Aws::requireAwsCommand
  - Linux::require*
  - Git::require*
  - Docker::require*
  - Ssh::require
  - ...

**runBuildContainer:**

- fixed verbose arg passed to container
- share docker container tmp folder with host for easier debug
  when used with bats for example

**frameworkLint:**

- added shdoc checks
  - check that only shdoc valid annotations are used
  - check that @require function matches naming convention and exists
  - check that at least @description is provided

**shdoc**

- removed tomdoc dependency
- Use shdoc tool to generate bash functions framework documentation
- generate doc using shdoc and make it docsify compatible
- updated all bash framework functions using shdoc
- added @require function for several commands

diff --git a/bin/buildPushDockerImages b/bin/buildPushDockerImages
--- a/bin/buildPushDockerImages
+++ b/bin/buildPushDockerImages
@@ -10,6 +10,34 @@
 unalias -a || true
 
 # shellcheck disable=SC2034
+((failures = 0)) || true
+
+shopt -s expand_aliases
+
+# Bash will remember & return the highest exit code in a chain of pipes.
+# This way you can catch the error inside pipes, e.g. mysqldump | gzip
+set -o pipefail
+set -o errexit
+
+# Command Substitution can inherit errexit option since bash v4.4
+shopt -s inherit_errexit || true
+
+# a log is generated when a command fails
+set -o errtrace
+
+# use nullglob so that (file*.php) will return an empty array if no file matches the wildcard
+shopt -s nullglob
+
+# ensure regexp are interpreted without accentuated characters
+export LC_ALL=POSIX
+
+export TERM=xterm-256color
+
+#avoid interactive install
+export DEBIAN_FRONTEND=noninteractive
+export DEBCONF_NONINTERACTIVE_SEEN=true
+
+# shellcheck disable=SC2034
 SCRIPT_NAME=${0##*/}
 REAL_SCRIPT_FILE="$(readlink -e "$(realpath "${BASH_SOURCE[0]}")")"
 # shellcheck disable=SC2034
@@ -90,34 +118,6 @@ interruptManagement() {
   kill -s INT "$$"
 }
 trap interruptManagement INT
-
-# shellcheck disable=SC2034
-((failures = 0)) || true
-
-shopt -s expand_aliases
-
-# Bash will remember & return the highest exit code in a chain of pipes.
-# This way you can catch the error inside pipes, e.g. mysqldump | gzip
-set -o pipefail
-set -o errexit
-
-# Command Substitution can inherit errexit option since bash v4.4
-(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
-
-# a log is generated when a command fails
-set -o errtrace
-
-# use nullglob so that (file*.php) will return an empty array if no file matches the wildcard
-shopt -s nullglob
-
-# ensure regexp are interpreted without accentuated characters
-export LC_ALL=POSIX
-
-export TERM=xterm-256color
-
-#avoid interactive install
-export DEBIAN_FRONTEND=noninteractive
-export DEBCONF_NONINTERACTIVE_SEEN=true
 FRAMEWORK_ROOT_DIR="$(cd "${CURRENT_DIR}/.." && pwd -P)"
 
 COMMAND_BIN_DIR="${CURRENT_DIR}"
@@ -132,6 +132,13 @@ if [[ -n "${FRAMEWORK_ROOT_DIR+xxx}" ]]; then
   FRAMEWORK_VENDOR_BIN_DIR="${FRAMEWORK_ROOT_DIR}/vendor/bin"
 fi
 
+# @description display help and exits if one of args is -h|--help
+# @arg $1 helpArg:String|Function the help string to display or the function to call to display the help
+# @arg $@ args:String[] list of options
+# @option -h short help option
+# @option --help long help option
+# @exitcode 0 displays help and exit with code 0 if -h or --help option is in the args list
+# @stdout displays help if -h or --help option is in the args list
 Args::defaultHelp() {
   local helpArg=$1
   shift || true
@@ -140,8 +147,14 @@ Args::defaultHelp() {
   fi
 }
 
-# change display level to level argument
-# if --verbose|-v option is parsed in arguments
+# @description change display level to verboseDisplayLevel argument if --verbose|-v option is parsed in arguments
+# @arg $1 verboseDisplayLevel:String the level of verbosity to set
+# @arg $@ args:String[] list of options
+# @option -v short verbose option
+# @option --verbose long verbose option
+# @set ARGS_VERBOSE 1 if --verbose|-v option is parsed in arguments
+# @set BASH_FRAMEWORK_DISPLAY_LEVEL to verboseDisplayLevel if --verbose|-v option is parsed in arguments
+# @exitcode 1 if --verbose|-v option is not present in args list
 Args::parseVerbose() {
   local verboseDisplayLevel="$1"
   declare -gx ARGS_VERBOSE=0
@@ -161,9 +174,12 @@ Args::parseVerbose() {
   return "${status}"
 }
 
-# remove elements from array
-# Performance1 : version taken from https://stackoverflow.com/a/59030460
-# Performance2 : for multiple values to remove, prefer using Array::removeIf
+# @description remove elements from array
+# @arg $1 arrayRemoveArray:&String[] (reference) array from which elements have to be removed
+# @arg $@ valuesToRemoveKeys:String[] list of elements to remove
+# @warning Performance1 : version taken from https://stackoverflow.com/a/59030460
+# @warning Performance2 : for multiple values to remove, prefer using Array::removeIf
+# @see Array::removeIf
 Array::remove() {
   local -n arrayRemoveArray=$1
   shift || true # $@ contains elements to remove
@@ -189,12 +205,22 @@ Array::remove() {
 declare -g BASH_FRAMEWORK_CACHED_ENV_FILE
 declare -g BASH_FRAMEWORK_DEFAULT_ENV_FILE
 
-# load variables in order(from less specific to more specific) from :
+# @description load variables in order(from less specific to more specific) from :
 # - ${FRAMEWORK_ROOT_DIR}/src/Env/testsData/.env file
 # - ${FRAMEWORK_ROOT_DIR}/conf/.env file if exists
 # - ~/.env file if exists
 # - ~/.bash-tools/.env file if exists
 # - BASH_FRAMEWORK_ENV_FILEPATH=<fullPathToEnvFile or empty if no file to be loaded>
+#
+# @env BASH_FRAMEWORK_INITIALIZED if 1 skip the load
+# @env FRAMEWORK_ROOT_DIR
+# @env HOME
+# @env BASH_FRAMEWORK_ENV_FILEPATH
+# @env OVERRIDE_* string allows to override any env file variable (with * name)
+#
+# @set BASH_FRAMEWORK_CACHED_ENV_FILE string
+# @set BASH_FRAMEWORK_DEFAULT_ENV_FILE string
+# @set BASH_FRAMEWORK_INITIALIZED int 1 if load successful
 Env::load() {
   if [[ "${BASH_FRAMEWORK_INITIALIZED:-0}" = "1" ]]; then
     return 0
@@ -279,6 +305,9 @@ Env::load() {
   BASH_FRAMEWORK_INITIALIZED=1
 }
 
+# @description prepend directories to the PATH environment variable
+# @arg $@ args:String[] list of directories to prepend
+# @set PATH update PATH with the directories prepended
 Env::pathPrepend() {
   local arg
   for arg in "$@"; do
@@ -288,17 +317,25 @@ Env::pathPrepend() {
   done
 }
 
-# Public: log level off
+# @description Log namespace provides 2 kind of functions
+# - Log::display* allows to display given message with
+#   given display level
+# - Log::log* allows to log given message with
+#   given log level
+# Log::display* functions automatically log the message too
+# @see Log::load to load the display and log level from .env file
+
+# @description log level off
 export __LEVEL_OFF=0
-# Public: log level error
+# @description log level error
 export __LEVEL_ERROR=1
-# Public: log level warning
+# @description log level warning
 export __LEVEL_WARNING=2
-# Public: log level info
+# @description log level info
 export __LEVEL_INFO=3
-# Public: log level success
+# @description log level success
 export __LEVEL_SUCCESS=3
-# Public: log level debug
+# @description log level debug
 export __LEVEL_DEBUG=4
 
 export __LEVEL_OFF
@@ -308,23 +345,23 @@ export __LEVEL_INFO
 export __LEVEL_SUCCESS
 export __LEVEL_DEBUG
 
-# Display message using debug color (grey)
-# @param {String} $1 message
+# @description Display message using debug color (grey)
+# @arg $1 message:String the message to display
 Log::displayDebug() {
   echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
   Log::logDebug "$1"
 }
 
-# Display message using info color (bg light blue/fg white)
-# @param {String} $1 message
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
 Log::displayInfo() {
   local type="${2:-INFO}"
   echo -e "${__INFO_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
   Log::logInfo "$1" "${type}"
 }
 
-# Display message using error color (red) and exit immediately with error status 1
-# @param {String} $1 message
+# @description Display message using error color (red) and exit immediately with error status 1
+# @arg $1 message:String the message to display
 Log::fatal() {
   echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
@@ -333,6 +370,18 @@ Log::fatal() {
 
 # shellcheck disable=SC2317
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
 Log::load() {
   # disable display methods following display level
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
@@ -390,6 +439,13 @@ Log::load() {
   fi
 }
 
+# @description display help if one of args is -h|--help
+# @arg $1 helpArg:String|Function the help string to display or the function to call to display the help
+# @arg $@ args:String[] list of options
+# @option -h short help option
+# @option --help long help option
+# @exitcode 1 displays help and returns with code 1 if -h or --help option is in the args list
+# @stdout displays help if -h or --help option is in the args list
 Args::defaultHelpNoExit() {
   local helpArg=$1
   shift || true
@@ -418,107 +474,107 @@ Args::defaultHelpNoExit() {
   done
 }
 
-# Display message using error color (red)
-# @param {String} $1 message
+# @description Display message using error color (red)
+# @arg $1 message:String the message to display
 Log::displayError() {
   echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
   Log::logError "$1"
 }
 
-# Display message using info color (bg light blue/fg white)
-# @param {String} $1 message
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
 Log::displayHelp() {
   local type="${2:-HELP}"
   echo -e "${__HELP_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
   Log::logHelp "$1" "${type}"
 }
 
-# Display message using skip color (yellow)
-# @param {String} $1 message
+# @description Display message using skip color (yellow)
+# @arg $1 message:String the message to display
 Log::displaySkipped() {
   echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
   Log::logSkipped "$1"
 }
 
-# Display message using info color (blue) but warning level
-# @param {String} $1 message
+# @description Display message using info color (blue) but warning level
+# @arg $1 message:String the message to display
 Log::displayStatus() {
   local type="${2:-STATUS}"
   echo -e "${__INFO_COLOR}${type}  - ${1}${__RESET_COLOR}" >&2
   Log::logStatus "$1" "${type}"
 }
 
-# Display message using success color (bg green/fg white)
-# @param {String} $1 message
+# @description Display message using success color (bg green/fg white)
+# @arg $1 message:String the message to display
 Log::displaySuccess() {
   echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
   Log::logSuccess "$1"
 }
 
-# Display message using warning color (yellow)
-# @param {String} $1 message
+# @description Display message using warning color (yellow)
+# @arg $1 message:String the message to display
 Log::displayWarning() {
   echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
   Log::logWarning "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logDebug() {
   Log::logMessage "${2:-DEBUG}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logError() {
   Log::logMessage "${2:-ERROR}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logFatal() {
   Log::logMessage "${2:-FATAL}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logHelp() {
   Log::logMessage "${2:-HELP}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logInfo() {
   Log::logMessage "${2:-INFO}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logSkipped() {
   Log::logMessage "${2:-SKIPPED}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logStatus() {
   Log::logMessage "${2:-STATUS}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logSuccess() {
   Log::logMessage "${2:-SUCCESS}" "$1"
 }
 
-# log message to file
-# @param {String} $1 message
+# @description log message to file
+# @arg $1 message:String the message to display
 Log::logWarning() {
   Log::logMessage "${2:-WARNING}" "$1"
 }
 
-# To be called before logging in the log file
-# @param {string} file $1 log file name
-# @param {int} maxLogFilesCount $2 maximum number of log files
+# @description To be called before logging in the log file
+# @arg $1 file:string log file name
+# @arg $2 maxLogFilesCount:int maximum number of log files
 Log::rotate() {
   local file="$1"
   local maxLogFilesCount="${2:-5}"
@@ -537,24 +593,27 @@ Log::rotate() {
   fi
 }
 
+# @description display help
+# @arg $1 helpArg:String the help string to show
+# @stdout display help arg
 Args::showHelp() {
   local helpArg="$1"
   echo -e "${helpArg}"
 }
 
-# Internal: common log message
+# @description Internal: common log message
+# @example text
+#   [date]|[levelMsg]|message
 #
-# **Arguments**:
-# * $1 - message's level description
-# * $2 - message
-# **Output**:
-# [date]|[levelMsg]|message
+# @example text
+#   2020-01-19 19:20:21|ERROR  |log error
+#   2020-01-19 19:20:21|SKIPPED|log skipped
 #
-# **Examples**:
-# <pre>
-# 2020-01-19 19:20:21|ERROR  |log error
-# 2020-01-19 19:20:21|SKIPPED|log skipped
-# </pre>
+# @arg $1 levelMsg:String message's level description (eg: STATUS, ERROR, ...)
+# @arg $2 msg:String the message to display
+# @env BASH_FRAMEWORK_LOG_FILE String log file to use, do nothing if empty
+# @env BASH_FRAMEWORK_LOG_LEVEL int log level log only if > OFF or fatal messages
+# @stderr diagnostics information is displayed
 Log::logMessage() {
   local levelMsg="$1"
   local msg="$2"
@@ -576,29 +635,43 @@ Log::logMessage() {
 }
 
 # Checks if file can be created in folder
+#
+
+# @description Checks if file can be created in folder
 # The file does not need to exist
+# @arg $1 file:String
+# @exitcode 1 if file is not a valid path
+# @exitcode 2 if file parent's dir is not writable
+# @exitcode 3 if existing file is not writable
+# @see Assert::validPath
 Assert::fileWritable() {
   local file="$1"
   local dir
 
-  dir="$(dirname "${file}")"
+  Assert::validPath "${file}" || return 1
+  if [[ -f "${file}" ]]; then
+    [[ -w "${file}" ]] || return 3
+  else
+    dir="$(dirname "${file}")"
+    [[ -w "${dir}" ]] || return 2
+  fi
 
-  Assert::validPath "${file}" && [[ -w "${dir}" ]]
 }
 
-# Public: check if argument is a valid linux path
-#
-# @param {string} path $1 path that needs to be checked
-# @return 1 if path is invalid
+# @description check if argument is a valid linux path
 # invalid path are those with:
 # - invalid characters
-# - component beginning by a - (because option)
+# - component beginning by a - (because could be considered as a command's option)
 # - not beginning with a slash
 # - relative
+#
+# @arg $1 path:string path that needs to be checked
+# @exitcode 1 if path is invalid
+# @see https://regex101.com/r/afLrmM/2
+# @see Assert::validPosixPath if you need more restrictive check
 Assert::validPath() {
   local path="$1"
 
-  # https://regex101.com/r/afLrmM/2
   [[ "${path}" =~ ^\/$|^(\/[.a-zA-Z_0-9][.a-zA-Z_0-9-]*)+$ ]] &&
     [[ ! "${path}" =~ (\/\.\.)|(\.\.\/)|^\.$|^\.\.$ ]] # avoid relative
 }
@@ -616,7 +689,7 @@ Log::load
 
 Env::pathPrepend "${COMMAND_BIN_DIR}"
 
-# prepare bin directory for eventual bin files generated by Embed::embed
+# prepare bin directory for eventual bin files generated by Compiler::Embed::embed
 mkdir -p "${TMPDIR:-/tmp}/bin"
 Env::pathPrepend "${TMPDIR:-/tmp}/bin"
 
diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -57,34 +57,20 @@ source "${_COMPILE_SRC_DIR}/Compiler/injectFileOnce.sh"
 source "${_COMPILE_SRC_DIR}/File/insertFileBeforeToken.sh"
 # shellcheck source=/src/File/insertFileAfterToken.sh
 source "${_COMPILE_SRC_DIR}/File/insertFileAfterToken.sh"
-# shellcheck source=src/Embed/inject.sh
-source "${_COMPILE_SRC_DIR}/Embed/inject.sh"
-# shellcheck source=src/Embed/filter.sh
-source "${_COMPILE_SRC_DIR}/Embed/filter.sh"
-# shellcheck source=src/Embed/parse.sh
-source "${_COMPILE_SRC_DIR}/Embed/parse.sh"
-# shellcheck source=src/Embed/assertAsName.sh
-source "${_COMPILE_SRC_DIR}/Embed/assertAsName.sh"
-# shellcheck source=src/Embed/assertResource.sh
-source "${_COMPILE_SRC_DIR}/Embed/assertResource.sh"
-# shellcheck source=src/Embed/embed.sh
-source "${_COMPILE_SRC_DIR}/Embed/embed.sh"
-# shellcheck source=src/Assert/validVariableName.sh
-source "${_COMPILE_SRC_DIR}/Assert/validVariableName.sh"
-# shellcheck source=src/Embed/embedFile.sh
-source "${_COMPILE_SRC_DIR}/Embed/embedFile.sh"
-# shellcheck source=src/Embed/embedDir.sh
-source "${_COMPILE_SRC_DIR}/Embed/embedDir.sh"
-# shellcheck source=src/Embed/embedFrameworkFunction.sh
-source "${_COMPILE_SRC_DIR}/Embed/embedFrameworkFunction.sh"
+# shellcheck source=src/Compiler/Embed/__all.sh
+source "${_COMPILE_SRC_DIR}/Compiler/Embed/__all.sh"
+# shellcheck source=src/Compiler/Facade/__all.sh
+source "${_COMPILE_SRC_DIR}/Compiler/Facade/__all.sh"
+# shellcheck source=/src/Compiler/Implement/__all.sh
+source "${_COMPILE_SRC_DIR}/Compiler/Implement/__all.sh"
 # shellcheck source=src/Filters/removeExternalQuotes.sh
 source "${_COMPILE_SRC_DIR}/Filters/removeExternalQuotes.sh"
 # shellcheck source=/src/Assert/bashFrameworkFunction.sh
 source "${_COMPILE_SRC_DIR}/Assert/bashFrameworkFunction.sh"
 # shellcheck source=/src/Assert/fileWritable.sh
 source "${_COMPILE_SRC_DIR}/Assert/fileWritable.sh"
-# shellcheck source=/src/Embed/getSrcDirsFromOptions.sh
-source "${_COMPILE_SRC_DIR}/Embed/getSrcDirsFromOptions.sh"
+# shellcheck source=/src/Compiler/Embed/getSrcDirsFromOptions.sh
+source "${_COMPILE_SRC_DIR}/Compiler/Embed/getSrcDirsFromOptions.sh"
 
 # shellcheck disable=SC2034
 ((failures = 0)) || true
@@ -311,20 +297,30 @@ dynamicSrcDir() {
 export -f dynamicSrcDir
 
 evalTemplate() {
-  local FILE="$1"
+  local file="$1"
+  local targetBinFile="$2"
+  local callback="$3"
   local varExports
-  varExports="$(Compiler::extractVarForExport "${FILE}")"
+  varExports="$(Compiler::extractVarForExport "${file}")"
+
+  local varCallbackExports=""
+  if [[ "$(type -t "${callback}")" = "function" ]]; then
+    local tmpFile
+    tmpFile="$(Framework::createTempFile "callbackExports")"
+    "${callback}" "${file}" >"${tmpFile}"
+    varCallbackExports="$(cat "${tmpFile}")"
+  fi
 
   # the src file you want to show at the top of generated file to indicate
   # from which source file the binary has been generated
   if [[ -z "${SRC_FILE_PATH+xxx}" ]]; then
     SRC_FILE_PATH="$(File::relativeToDir "${INPUT_FILE}" "${FRAMEWORK_ROOT_DIR}")"
   fi
-
   SRC_ABSOLUTE_PATH="$(realpath "${INPUT_FILE}")"
   (
     cd "${TEMPLATE_DIR}"
     eval "${varExports}"
+    eval "${varCallbackExports}"
     ORIGINAL_TEMPLATE_DIR="${_COMPILE_SRC_DIR}"
     export FRAMEWORK_BIN_DIR
     export FRAMEWORK_ROOT_DIR
@@ -336,9 +332,18 @@ evalTemplate() {
     # make srcDirs array available for dynamicSrcFile and dynamicSrcDir
     trap 'rm -f "${TMPDIR:-/tmp}/srcDirs"' INT EXIT HUP QUIT ABRT TERM
     printf '%s\n' "${srcDirs[@]}" >"${TMPDIR:-/tmp}/srcDirs"
+    local bashtplLogFile
+    bashtplLogFile="$(Framework::createTempFile "bashtplLogFile")"
     # shellcheck source=/dev/null
-    source <("${_COMPILE_ROOT_DIR}/bin/bash-tpl" "${FILE}")
-  ) | Filters::removeDuplicatedShebangs
+    source <("${_COMPILE_ROOT_DIR}/bin/bash-tpl" "${file}" 2>"${bashtplLogFile}")
+    wait $!
+    if [[ -s "${bashtplLogFile}" ]]; then
+      Log::displayError "bash-tpl found some errors"
+      cat >&2 "${bashtplLogFile}"
+      exit 1
+    fi
+  ) | Filters::removeDuplicatedShebangs | Compiler::Facade::restoreOldMainFunctionName "${targetBinFile}"
+
 }
 
 importFunctions() {
@@ -453,7 +458,7 @@ injectEmbed() {
   local -a embeddedNames=()
   # shellcheck disable=SC2034
   local -a embeddedResources=()
-  Embed::inject embeddedNames embeddedResources <"${file}" >"${embedFile}"
+  Compiler::Embed::inject embeddedNames embeddedResources <"${file}" >"${embedFile}"
   File::insertFileAfterToken "${file}" "${embedFile}" "# FUNCTIONS"
 }
 
@@ -479,7 +484,7 @@ COMPILED_FILE2="$(mktemp -p "${TMPDIR:-/tmp}" -t "compiled_file2.XXXXXXX")"
 
 # shellcheck disable=SC2034
 declare -a filesAlreadyImported=("${INPUT_FILE}")
-evalTemplate "${INPUT_FILE}" >"${COMPILED_FILE}"
+evalTemplate "${INPUT_FILE}" "${BIN_FILE}" Compiler::Facade::facade >"${COMPILED_FILE}"
 
 # compute BIN_FILE
 if [[ -z "${BIN_FILE}" ]]; then
@@ -500,7 +505,7 @@ injectImportedFunctions "${COMPILED_FILE}" filesAlreadyImported
 
 # evaluate again the current compiledFile as a template in the case
 # where injected function are using template function (include files like Env::load
-evalTemplate "${COMPILED_FILE}" >"${COMPILED_FILE2}"
+evalTemplate "${COMPILED_FILE}" "${BIN_FILE}" >"${COMPILED_FILE2}"
 
 # inject again functions in case included file at previous step needs some new functions
 # filesAlreadyImported is global variable so we will not reimport already included functions
@@ -508,6 +513,13 @@ injectImportedFunctions "${COMPILED_FILE2}" filesAlreadyImported
 
 # remove spaces at the end of the lines
 sed -E -i 's/[[:blank:]]+$//' "${COMPILED_FILE2}"
+
+# retrieve all interfaces functions that need to be implemented
+export _COMPILE_FILE_ARGUMENTS
+declare -a interfacesFunctions
+Compiler::Implement::mergeInterfacesFunctions "${COMPILED_FILE2}" | readarray -t interfacesFunctions
+Compiler::Implement::validateInterfaceFunctions \
+  "${COMPILED_FILE2}" "${INPUT_FILE}" "${interfacesFunctions[@]}"
 
 cat -s "${COMPILED_FILE2}" | Filters::directive "${FILTER_DIRECTIVE_REMOVE_HEADERS}" >"${BIN_FILE}"
 chmod +x "${BIN_FILE}"
