Improve framework reusability outside of this project (#22)
stabilize bash-tools project using this project

**Build/Compilation improvements**
- build.sh allows parallel build when several files passed to the command
- compile - fix dynamicTemplateDir and dynamicSrcFile was not able to access srcDirs variable
- frameworkLint - added better ways to filter non wanted checks + display more verbose messages
- frameworkLint - bats new .framework-config BATS_FILE_NOT_NEEDED_REGEXP
- runBuildContainer - additional docker run options can be passed via DOCKER_RUN_OPTIONS env variable
- dockerLint - ensure using hadolint installed not necessarily in PATH
- fixed buildBinFiles - was no more working on github

Logging management
- separate Env::load and Log::load
- added Args::parseVerbose to allow all binaries to benefit from verbose arg addition
-  _includes/_colors.sh changed readonly to export, to allow for themable log display in the future
- replaced Log/ZZZ.sh by Log::load to allow better control on when initialization is done
- moved Env::load + Log::load in headers
- added Log::displayStatus and Log::logStatus to allow important command information to be displayed (displayed with 
  level warning but color info)
- BASH_FRAMEWORK_DISPLAY_LEVEL init from existing var if any
- Log::logMessage - ensure log directory is created

**Framework functions changes:**
- added Array::remove that allows to remove a specific array element 
- added Array::removeIf - more performant and flexible version than Array::remove
- doc - extracted ShellDoc::fixMarkdownToc
- new Github::downloadReleaseVersion, Github::extractRepoFromGithubUrl and Github::getLatestVersionFromUrl

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -29,8 +29,6 @@ source "${_COMPILE_SRC_DIR}/Env/load.sh"
 source "${_COMPILE_SRC_DIR}/File/upFind.sh"
 # shellcheck source=src/File/relativeToDir.sh
 source "${_COMPILE_SRC_DIR}/File/relativeToDir.sh"
-# shellcheck source=src/Log/__all.sh
-source "${_COMPILE_SRC_DIR}/Log/__all.sh"
 # shellcheck source=/src/Filters/removeDuplicatedShebangs.sh
 source "${_COMPILE_SRC_DIR}/Filters/removeDuplicatedShebangs.sh"
 # shellcheck source=/src/Filters/catFileCleaned.sh
@@ -83,6 +81,8 @@ source "${_COMPILE_SRC_DIR}/Embed/embedFrameworkFunction.sh"
 source "${_COMPILE_SRC_DIR}/Filters/removeExternalQuotes.sh"
 # shellcheck source=/src/Assert/bashFrameworkFunction.sh
 source "${_COMPILE_SRC_DIR}/Assert/bashFrameworkFunction.sh"
+# shellcheck source=/src/Assert/fileWritable.sh
+source "${_COMPILE_SRC_DIR}/Assert/fileWritable.sh"
 # shellcheck source=/src/Embed/getSrcDirsFromOptions.sh
 source "${_COMPILE_SRC_DIR}/Embed/getSrcDirsFromOptions.sh"
 
@@ -253,6 +253,7 @@ if [[ -z "${BIN_DIR+xxx}" ]]; then
 fi
 export BIN_DIR
 FRAMEWORK_FUNCTIONS_IGNORE_REGEXP=^$
+loggedMessages=()
 
 # load .framework-config
 configFile=""
@@ -262,44 +263,50 @@ Framework::loadConfig configFile "${srcDirs[@]}" || Log::fatal "error while load
 # shellcheck disable=SC2317
 dynamicTemplateDir() {
   local file="$1"
-  if [[ ! -f "${file}" ]]; then
-    if [[ -f "${TEMPLATE_DIR}/${file}" ]]; then
-      echo "${TEMPLATE_DIR}/${file}"
-      return 0
-    elif [[ -f "${ORIGINAL_TEMPLATE_DIR}/${file}" ]]; then
-      echo "${ORIGINAL_TEMPLATE_DIR}/${file}"
-      return 0
-    fi
+  if [[ -f "${TEMPLATE_DIR}/${file}" ]]; then
+    echo "${TEMPLATE_DIR}/${file}"
+    return 0
+  elif [[ -f "${ORIGINAL_TEMPLATE_DIR}/${file}" ]]; then
+    echo "${ORIGINAL_TEMPLATE_DIR}/${file}"
+    return 0
   fi
-  echo "${file}"
+  local msg="dynamicTemplateDir - ${file} does not exist in any template dirs declared"
+  echo -e "\e[31m${msg}\e[0m" >&2
+  return 1
 }
 export -f dynamicTemplateDir
 
 # shellcheck disable=SC2317
 dynamicSrcFile() {
   local file="$1"
-  local srcDir
+  local -a srcDirs=()
+  readarray -t srcDirs <"${TMPDIR:-/tmp}/srcDirs"
   for srcDir in "${srcDirs[@]}"; do
     if [[ -f "${srcDir}/${file}" ]]; then
       echo "${srcDir}/${file}"
       return 0
     fi
   done
-  echo "${file}"
+  local msg="dynamicSrcFile - ${file} does not exist in any src dirs declared"
+  echo -e "\e[31m${msg}\e[0m" >&2
+  return 1
 }
 export -f dynamicSrcFile
 
 # shellcheck disable=SC2317
 dynamicSrcDir() {
   local dir="$1"
-  local srcDir
+  local -a srcDirs=()
+  readarray -t srcDirs <"${TMPDIR:-/tmp}/srcDirs"
   for srcDir in "${srcDirs[@]}"; do
     if [[ -d "${srcDir}/${dir}" ]]; then
       echo "${srcDir}/${dir}"
       return 0
     fi
   done
-  echo "${dir}"
+  local msg="dynamicSrcDir - ${dir} does not exist in any src dirs declared"
+  echo -e "\e[31m${msg}\e[0m" >&2
+  return 1
 }
 export -f dynamicSrcDir
 
@@ -326,6 +333,10 @@ evalTemplate() {
     export SRC_ABSOLUTE_PATH
     export SRC_FILE_PATH
     export ROOT_DIR_RELATIVE_TO_BIN_DIR
+    export TMPDIR
+    # make srcDirs array available for dynamicSrcFile and dynamicSrcDir
+    trap 'rm -f "${TMPDIR:-/tmp}/srcDirs"' INT EXIT HUP QUIT ABRT TERM
+    printf '%s\n' "${srcDirs[@]}" >"${TMPDIR:-/tmp}/srcDirs"
     # shellcheck source=/dev/null
     source <("${_COMPILE_ROOT_DIR}/bin/bash-tpl" "${FILE}")
   ) | Filters::removeDuplicatedShebangs
@@ -344,18 +355,24 @@ importFunctions() {
   readarray -t functionsToImport < <(Compiler::extractUniqueFrameworkFunctions "${file}")
 
   ((newFilesAdded = 0)) || true
-  if [[ "${DEBUG:-0}" = "1" ]]; then
-    echo >&2 "importing ${file} with ${#functionsToImport[@]} functions to import"
+  if [[ "${ARGS_VERBOSE:-0}" = "2" ]]; then
+    Log::displayDebug "importing ${file} with ${#functionsToImport[@]} functions to import"
   fi
   for functionToImport in "${functionsToImport[@]}"; do
     if echo "${functionToImport}" | grep -q -E "${FRAMEWORK_FUNCTIONS_IGNORE_REGEXP}"; then
-      (echo >&2 -e "${__DEBUG_COLOR}\tFunction ${functionToImport} ignored, because of rule defined in ${configFile}${__RESET_COLOR}")
+      if [[ "${ARGS_VERBOSE:-0}" = "1" ]]; then
+        msg="File ${INPUT_FILE} Function ${functionToImport} ignored, because of rule defined in ${configFile}"
+        if ! Array::contains "${msg}" "${loggedMessages[@]}"; then
+          loggedMessages+=("${msg}")
+          Log::displayHelp "${msg}" "HINT"
+        fi
+      fi
       continue
     fi
 
     local fileToImport
     fileToImport="$(Compiler::findFunctionInSrcDirs "${functionToImport}" "${srcDirs[@]}")" || {
-      (echo >&2 -e "${__ERROR_COLOR}\tFunction ${functionToImport} not found in any src directories${__RESET_COLOR}")
+      Log::displayError "File ${INPUT_FILE} Function ${functionToImport} not found in any src directories"
       ((importFailures++)) || true
       continue
     }
@@ -383,7 +400,7 @@ importFunctions() {
       # shellcheck disable=SC2034
       ((newFilesAdded = 1)) # as we added some files, we need to do another pass
     else
-      (echo >&2 -e "${__ERROR_COLOR}\tFile ${fileToImport} does not exist${__RESET_COLOR}")
+      Log::displayError "File ${INPUT_FILE} File ${fileToImport} does not exist${__RESET_COLOR}"
       # even if not existing, consider the file as imported to avoid other same errors
       filesImportedWithFunctions+=("${fileToImport}")
       ((importFailures++)) || true
@@ -409,8 +426,8 @@ injectImportedFunctions() {
   ((needAnotherPass = 1))
   ((iteration = 1))
   while ((needAnotherPass >= 1)); do
-    if [[ "${DEBUG:-0}" = "1" ]]; then
-      (echo >&2 -e "${__DEBUG_COLOR}\tIteration #${iteration}${__RESET_COLOR}")
+    if [[ "${ARGS_VERBOSE:-0}" = "2" ]]; then
+      Log::displayDebug "File ${INPUT_FILE} Iteration #${iteration}"
     fi
     echo >"${importedFunctionsTempFile}"
     echo >"${importedZZZTempFile}"
@@ -475,7 +492,7 @@ if [[ -z "${BIN_FILE}" ]]; then
     exit 0
   fi
 fi
-Log::displayInfo "Binfile ${BIN_FILE} from ${INPUT_FILE}"
+Log::displayInfo "Compiling ${INPUT_FILE} ..."
 
 # inject embed
 injectEmbed "${COMPILED_FILE}"
@@ -504,4 +521,5 @@ sed -E -i 's/[[:blank:]]+$//' "${COMPILED_FILE2}"
 cat -s "${COMPILED_FILE2}" | Filters::directive "${FILTER_DIRECTIVE_REMOVE_HEADERS}" >"${BIN_FILE}"
 chmod +x "${BIN_FILE}"
 
+Log::displayStatus "Compiled ${INPUT_FILE} to Binfile ${BIN_FILE}"
 exit "${failures}"
diff --git a/bin/plantuml b/bin/plantuml
--- a/bin/plantuml
+++ b/bin/plantuml
@@ -25,6 +25,43 @@ VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
 VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
 
+if [[ -t 1 || -t 2 ]]; then
+  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
+  export __ERROR_COLOR='\e[31m'      # Red
+  export __INFO_COLOR='\e[44m'       # white on lightBlue
+  export __SUCCESS_COLOR='\e[32m'    # Green
+  export __WARNING_COLOR='\e[33m'    # Yellow
+  export __TEST_COLOR='\e[100m'      # Light magenta
+  export __TEST_ERROR_COLOR='\e[41m' # white on red
+  export __SKIPPED_COLOR='\e[33m'    # Yellow
+  export __HELP_COLOR='\e[7;49;33m'  # Black on Gold
+  export __DEBUG_COLOR='\e[37m'      # Grey
+  # Internal: reset color
+  export __RESET_COLOR='\e[0m' # Reset Color
+  # shellcheck disable=SC2155,SC2034
+  export __HELP_EXAMPLE="$(echo -e "\e[1;30m")"
+  # shellcheck disable=SC2155,SC2034
+  export __HELP_TITLE="$(echo -e "\e[1;37m")"
+  # shellcheck disable=SC2155,SC2034
+  export __HELP_NORMAL="$(echo -e "\033[0m")"
+else
+  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
+  export __ERROR_COLOR=''
+  export __INFO_COLOR=''
+  export __SUCCESS_COLOR=''
+  export __WARNING_COLOR=''
+  export __SKIPPED_COLOR=''
+  export __HELP_COLOR=''
+  export __TEST_COLOR=''
+  export __TEST_ERROR_COLOR=''
+  export __DEBUG_COLOR=''
+  # Internal: reset color
+  export __RESET_COLOR=''
+  export __HELP_EXAMPLE=''
+  export __HELP_TITLE=''
+  export __HELP_NORMAL=''
+fi
+
 ################################################
 # Temp dir management
 ################################################
@@ -46,7 +83,7 @@ cleanOnExit() {
   if [[ "${KEEP_TEMP_FILES:-0}" = "1" ]]; then
     Log::displayInfo "KEEP_TEMP_FILES=1 temp files kept here '${TMPDIR}'"
   elif [[ -n "${TMPDIR+xxx}" ]]; then
-    Log::displayInfo "KEEP_TEMP_FILES=0 removing temp files '${TMPDIR}'"
+    Log::displayDebug "KEEP_TEMP_FILES=0 removing temp files '${TMPDIR}'"
     rm -Rf "${TMPDIR:-/tmp/fake}" >/dev/null 2>&1
   fi
 }
@@ -87,52 +124,52 @@ export TERM=xterm-256color
 export DEBIAN_FRONTEND=noninteractive
 export DEBCONF_NONINTERACTIVE_SEEN=true
 
-Env::pathPrepend() {
-  local arg
-  for arg in "$@"; do
-    if [[ -d "${arg}" && ":${PATH}:" != *":${arg}:"* ]]; then
-      PATH="$(realpath "${arg}"):${PATH}"
+# change display level to level argument
+# if --verbose|-v option is parsed in arguments
+Args::parseVerbose() {
+  local verboseDisplayLevel="$1"
+  declare -gx ARGS_VERBOSE=0
+  shift || true
+  local status=1
+  while true; do
+    if [[ "$1" = "--verbose" || "$1" = "-v" ]]; then
+      status=0
+      ARGS_VERBOSE=1
+      break
+    fi
+    shift || break
+  done
+  if [[ "${status}" = "0" ]]; then
+    export BASH_FRAMEWORK_DISPLAY_LEVEL=${verboseDisplayLevel}
+  fi
+  return "${status}"
+}
+
+# remove elements from array
+# Performance1 : version taken from https://stackoverflow.com/a/59030460
+# Performance2 : for multiple values to remove, prefer using Array::removeIf
+Array::remove() {
+  local -n arrayRemoveArray=$1
+  shift || true # $@ contains elements to remove
+  local -A valuesToRemoveKeys=()
+
+  # Tag items to remove
+  local del
+  for del in "$@"; do valuesToRemoveKeys[${del}]=1; done
+
+  # remove items
+  local k
+  for k in "${!arrayRemoveArray[@]}"; do
+    if [[ -n "${valuesToRemoveKeys[${arrayRemoveArray[k]}]+xxx}" ]]; then
+      unset 'arrayRemoveArray[k]'
     fi
   done
-}
 
-# Public: log level off
-export __LEVEL_OFF=0
-# Public: log level error
-export __LEVEL_ERROR=1
-# Public: log level warning
-export __LEVEL_WARNING=2
-# Public: log level info
-export __LEVEL_INFO=3
-# Public: log level success
-export __LEVEL_SUCCESS=3
-# Public: log level debug
-export __LEVEL_DEBUG=4
-
-export __LEVEL_OFF
-export __LEVEL_ERROR
-export __LEVEL_WARNING
-export __LEVEL_INFO
-export __LEVEL_SUCCESS
-export __LEVEL_DEBUG
-
-# Display message using info color (bg light blue/fg white)
-# @param {String} $1 message
-Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
-  Log::logInfo "$1"
-}
-
-# Display message using error color (red) and exit immediately with error status 1
-# @param {String} $1 message
-Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
-  Log::logFatal "$1"
-  exit 1
+  # compaction (element re-indexing, because unset makes "holes" in array )
+  arrayRemoveArray=("${arrayRemoveArray[@]}")
 }
 
 # lazy initialization
-declare -g BASH_FRAMEWORK_INITIALIZED="0"
 declare -g BASH_FRAMEWORK_CACHED_ENV_FILE
 declare -g BASH_FRAMEWORK_DEFAULT_ENV_FILE
 
@@ -143,7 +180,7 @@ declare -g BASH_FRAMEWORK_DEFAULT_ENV_FILE
 # - ~/.bash-tools/.env file if exists
 # - BASH_FRAMEWORK_ENV_FILEPATH=<fullPathToEnvFile or empty if no file to be loaded>
 Env::load() {
-  if [[ "${BASH_FRAMEWORK_INITIALIZED}" = "1" ]]; then
+  if [[ "${BASH_FRAMEWORK_INITIALIZED:-0}" = "1" ]]; then
     return 0
   fi
   BASH_FRAMEWORK_CACHED_ENV_FILE="$(mktemp -p "${TMPDIR:-/tmp}" -t "env_vars.XXXXXXX")"
@@ -222,16 +259,119 @@ Env::load() {
   # shellcheck source=src/Env/testsData/.env
   source "${BASH_FRAMEWORK_CACHED_ENV_FILE}"
 
-  export BASH_FRAMEWORK_INITIALIZED=1
-
   set +o allexport
+  BASH_FRAMEWORK_INITIALIZED=1
 }
+
+Env::pathPrepend() {
+  local arg
+  for arg in "$@"; do
+    if [[ -d "${arg}" && ":${PATH}:" != *":${arg}:"* ]]; then
+      PATH="$(realpath "${arg}"):${PATH}"
+    fi
+  done
+}
+
+# Public: log level off
+export __LEVEL_OFF=0
+# Public: log level error
+export __LEVEL_ERROR=1
+# Public: log level warning
+export __LEVEL_WARNING=2
+# Public: log level info
+export __LEVEL_INFO=3
+# Public: log level success
+export __LEVEL_SUCCESS=3
+# Public: log level debug
+export __LEVEL_DEBUG=4
+
+export __LEVEL_OFF
+export __LEVEL_ERROR
+export __LEVEL_WARNING
+export __LEVEL_INFO
+export __LEVEL_SUCCESS
+export __LEVEL_DEBUG
 
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
   echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
   Log::logDebug "$1"
+}
+
+# Display message using info color (bg light blue/fg white)
+# @param {String} $1 message
+Log::displayInfo() {
+  local type="${2:-INFO}"
+  echo -e "${__INFO_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
+  Log::logInfo "$1" "${type}"
+}
+
+# Display message using error color (red) and exit immediately with error status 1
+# @param {String} $1 message
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
+}
+
+# shellcheck disable=SC2317
+
+Log::load() {
+  # disable display methods following display level
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
+    Log::displayDebug() { :; }
+  fi
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_INFO)); then
+    Log::displayHelp() { :; }
+    Log::displayInfo() { :; }
+    Log::displaySkipped() { :; }
+    Log::displaySuccess() { :; }
+  fi
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_WARNING)); then
+    Log::displayWarning() { :; }
+    Log::displayStatus() { :; }
+  fi
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_ERROR)); then
+    Log::displayError() { :; }
+  fi
+  # disable log methods following log level
+  if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_DEBUG)); then
+    Log::logDebug() { :; }
+  fi
+  if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_INFO)); then
+    Log::logHelp() { :; }
+    Log::logInfo() { :; }
+    Log::logSkipped() { :; }
+    Log::logSuccess() { :; }
+  fi
+  if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_WARNING)); then
+    Log::logWarning() { :; }
+    Log::logStatus() { :; }
+  fi
+  if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_ERROR)); then
+    Log::logError() { :; }
+  fi
+
+  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
+    if [[ -z "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
+      BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
+      export BASH_FRAMEWORK_LOG_LEVEL
+    elif [[ ! -f "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
+      if ! mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" 2>/dev/null; then
+        BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
+        Log::displayWarning "Log dir cannot be created $(dirname "${BASH_FRAMEWORK_LOG_FILE}")"
+      fi
+      if ! touch --no-create "${BASH_FRAMEWORK_LOG_FILE}" 2>/dev/null; then
+        BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
+        Log::displayWarning "Log file '${BASH_FRAMEWORK_LOG_FILE}' cannot be created"
+      fi
+    fi
+    Log::displayInfo "Logging to file ${BASH_FRAMEWORK_LOG_FILE}"
+    if ((BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION > 0)); then
+      Log::rotate "${BASH_FRAMEWORK_LOG_FILE}" "${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION}"
+    fi
+  fi
 }
 
 # Display message using error color (red)
@@ -244,8 +384,9 @@ Log::displayError() {
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayHelp() {
-  echo -e "${__HELP_COLOR}HELP    - ${1}${__RESET_COLOR}" >&2
-  Log::logHelp "$1"
+  local type="${2:-HELP}"
+  echo -e "${__HELP_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
+  Log::logHelp "$1" "${type}"
 }
 
 # Display message using skip color (yellow)
@@ -253,6 +394,14 @@ Log::displayHelp() {
 Log::displaySkipped() {
   echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
   Log::logSkipped "$1"
+}
+
+# Display message using info color (blue) but warning level
+# @param {String} $1 message
+Log::displayStatus() {
+  local type="${2:-STATUS}"
+  echo -e "${__INFO_COLOR}${type}  - ${1}${__RESET_COLOR}" >&2
+  Log::logStatus "$1" "${type}"
 }
 
 # Display message using success color (bg green/fg white)
@@ -272,49 +421,55 @@ Log::displayWarning() {
 # log message to file
 # @param {String} $1 message
 Log::logDebug() {
-  Log::logMessage "DEBUG" "$@"
+  Log::logMessage "${2:-DEBUG}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logError() {
-  Log::logMessage "ERROR" "$@"
+  Log::logMessage "${2:-ERROR}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logFatal() {
-  Log::logMessage "FATAL" "$@"
+  Log::logMessage "${2:-FATAL}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logHelp() {
-  Log::logMessage "HELP" "$@"
+  Log::logMessage "${2:-HELP}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logInfo() {
-  Log::logMessage "INFO" "$@"
+  Log::logMessage "${2:-INFO}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logSkipped() {
-  Log::logMessage "SKIPPED" "$@"
+  Log::logMessage "${2:-SKIPPED}" "$1"
+}
+
+# log message to file
+# @param {String} $1 message
+Log::logStatus() {
+  Log::logMessage "${2:-STATUS}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logSuccess() {
-  Log::logMessage "SUCCESS" "$@"
+  Log::logMessage "${2:-SUCCESS}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logWarning() {
-  Log::logMessage "WARNING" "$@"
+  Log::logMessage "${2:-WARNING}" "$1"
 }
 
 # To be called before logging in the log file
@@ -360,6 +515,7 @@ Log::logMessage() {
     return 0
   fi
   if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)) || [[ "${levelMsg}" = "FATAL" ]]; then
+    mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" || true
     if Assert::fileWritable "${BASH_FRAMEWORK_LOG_FILE}"; then
       date="$(date '+%Y-%m-%d %H:%M:%S')"
       touch "${BASH_FRAMEWORK_LOG_FILE}"
@@ -401,110 +557,12 @@ Assert::validPath() {
 # FUNCTIONS
 
 Env::load
-
-# disable display methods following display level
-if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
-  Log::displayDebug() { :; }
-fi
-if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_INFO)); then
-  Log::displayHelp() { :; }
-  Log::displayInfo() { :; }
-  Log::displaySkipped() { :; }
-  Log::displaySuccess() { :; }
-fi
-if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_WARNING)); then
-  Log::displayWarning() { :; }
-fi
-if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_ERROR)); then
-  Log::displayError() { :; }
-fi
-# disable log methods following log level
-if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_DEBUG)); then
-  Log::logDebug() { :; }
-fi
-if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_INFO)); then
-  Log::logHelp() { :; }
-  Log::logInfo() { :; }
-  Log::logSkipped() { :; }
-  Log::logSuccess() { :; }
-fi
-if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_WARNING)); then
-  Log::logWarning() { :; }
-fi
-if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_ERROR)); then
-  Log::logError() { :; }
-fi
-
-if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
-  if [[ -z "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
-    BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
-    export BASH_FRAMEWORK_LOG_LEVEL
-  elif [[ ! -f "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
-    if ! mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" 2>/dev/null; then
-      BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
-      Log::displayWarning "Log dir cannot be created $(dirname "${BASH_FRAMEWORK_LOG_FILE}")"
-    fi
-    if ! touch --no-create "${BASH_FRAMEWORK_LOG_FILE}" 2>/dev/null; then
-      BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
-      Log::displayWarning "Log file '${BASH_FRAMEWORK_LOG_FILE}' cannot be created"
-    fi
-  fi
-  Log::displayInfo "Logging to file ${BASH_FRAMEWORK_LOG_FILE}"
-  if ((BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION > 0)); then
-    Log::rotate "${BASH_FRAMEWORK_LOG_FILE}" "${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION}"
-  fi
-fi
-
-if [[ -t 1 || -t 2 ]]; then
-  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  readonly __ERROR_COLOR='\e[31m'      # Red
-  readonly __INFO_COLOR='\e[44m'       # white on lightBlue
-  readonly __SUCCESS_COLOR='\e[32m'    # Green
-  readonly __WARNING_COLOR='\e[33m'    # Yellow
-  readonly __TEST_COLOR='\e[100m'      # Light magenta
-  readonly __TEST_ERROR_COLOR='\e[41m' # white on red
-  readonly __SKIPPED_COLOR='\e[33m'    # Yellow
-  readonly __HELP_COLOR='\e[7;49;33m'  # Black on Gold
-  readonly __DEBUG_COLOR='\e[37m'      # Grey
-  # Internal: reset color
-  readonly __RESET_COLOR='\e[0m' # Reset Color
-  # shellcheck disable=SC2155,SC2034
-  readonly __HELP_EXAMPLE="$(echo -e "\e[1;30m")"
-  # shellcheck disable=SC2155,SC2034
-  readonly __HELP_TITLE="$(echo -e "\e[1;37m")"
-  # shellcheck disable=SC2155,SC2034
-  readonly __HELP_NORMAL="$(echo -e "\033[0m")"
-else
-  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  readonly __ERROR_COLOR=''
-  readonly __INFO_COLOR=''
-  readonly __SUCCESS_COLOR=''
-  readonly __WARNING_COLOR=''
-  readonly __SKIPPED_COLOR=''
-  readonly __HELP_COLOR=''
-  readonly __TEST_COLOR=''
-  readonly __TEST_ERROR_COLOR=''
-  readonly __DEBUG_COLOR=''
-  # Internal: reset color
-  readonly __RESET_COLOR=''
-  readonly __HELP_EXAMPLE=''
-  readonly __HELP_TITLE=''
-  readonly __HELP_NORMAL=''
-fi
-export __ERROR_COLOR
-export __INFO_COLOR
-export __SUCCESS_COLOR
-export __WARNING_COLOR
-export __SKIPPED_COLOR
-export __TEST_COLOR
-export __TEST_ERROR_COLOR
-export __SKIPPED_COLOR
-export __HELP_COLOR
-export __DEBUG_COLOR
-export __RESET_COLOR
-export __HELP_EXAMPLE
-export __HELP_TITLE
-export __HELP_NORMAL
+export BASH_FRAMEWORK_DISPLAY_LEVEL="${__LEVEL_WARNING}"
+Args::parseVerbose "${__LEVEL_INFO}" "$@" || true
+declare -a args=("$@")
+Array::remove args -v --verbose
+set -- "${args[@]}"
+Log::load
 
 Env::pathPrepend "${VENDOR_BIN_DIR}"
 Env::pathPrepend "${BIN_DIR}"
