compile - refact extract importFunctions

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -259,11 +259,81 @@ evalTemplate() {
 
 evalTemplate "${INPUT_FILE}" >"${COMPILED_FILE}"
 
+importFunctions() {
+  local importedFunctionsTempFile="$1"
+  local importedZZZTempFile="$2"
+  local -n filesImportedWithFunctions=$3
+  local -n functionsNeedToBeImported=$4
+  local functionToImport
+
+  readarray -t functionsToImport < <(
+    Filters::bashFrameworkFunctions "${file}" |
+      awk '{$1=$1};1' |
+      sort |
+      uniq
+  )
+  ((functionsNeedToBeImported = 0)) || true
+  for functionToImport in "${functionsToImport[@]}"; do
+    if echo "${functionToImport}" | grep -q -E "${FRAMEWORK_FUNCTIONS_IGNORE_REGEXP}"; then
+      (echo >&2 -e "${__DEBUG_COLOR}\tFunction ${functionToImport} ignored, because of rule defined in ${configFile}${__RESET_COLOR}")
+      continue
+    fi
+
+    local fileNameToImport
+    fileNameToImport="$(echo "${functionToImport}" | sed -E 's#::#/#g').sh"
+    # search through srcDirs the file to import
+    for srcDir in "${srcDirs[@]}"; do
+      fileToImport="${srcDir}/${fileNameToImport}"
+      if [[ -f "${fileToImport}" ]]; then
+        # we found it
+        break
+      fi
+    done
+
+    if ! Array::contains "${fileToImport}" "${filesImportedWithFunctions[@]}"; then
+      if [[ -f "${fileToImport}" ]]; then
+        # check if we need to import _.sh
+        underscoreFile="$(dirname "${fileToImport}")/_.sh"
+        if ! Array::contains "${underscoreFile}" "${filesImportedWithFunctions[@]}" &&
+          [[ -f "${underscoreFile}" ]]; then
+          if [[ "${DEBUG:-0}" = "1" ]]; then
+            (echo >&2 -e "${__DEBUG_COLOR}\tImporting ${underscoreFile} ...${__RESET_COLOR}")
+          fi
+          Filters::catFileCleaned "${underscoreFile}" >>"${importedFunctionsTempFile}"
+          filesImportedWithFunctions+=("${underscoreFile}")
+        fi
+        # check if we need to import ZZZ.sh
+        zzzFile="$(dirname "${fileToImport}")/ZZZ.sh"
+        if ! Array::contains "${zzzFile}" "${filesImportedWithFunctions[@]}" &&
+          [[ -f "${zzzFile}" ]]; then
+          if [[ "${DEBUG:-0}" = "1" ]]; then
+            (echo >&2 -e "${__DEBUG_COLOR}\tImporting ${zzzFile} ...${__RESET_COLOR}")
+          fi
+          Filters::catFileCleaned "${zzzFile}" >>"${importedZZZTempFile}"
+          filesImportedWithFunctions+=("${zzzFile}")
+        fi
+
+        if [[ "${DEBUG:-0}" = "1" ]]; then
+          (echo >&2 -e "\t${__DEBUG_COLOR}Importing ${fileToImport} ...${__RESET_COLOR}")
+        fi
+        Filters::catFileCleaned "${fileToImport}" >>"${importedFunctionsTempFile}"
+      else
+        (echo >&2 -e "${__ERROR_COLOR}\tFile ${fileToImport} does not exist${__RESET_COLOR}")
+        ((failures++)) || true
+      fi
+      filesImportedWithFunctions+=("${fileToImport}")
+      # shellcheck disable=SC2034
+      ((functionsNeedToBeImported = 1)) # as we added some files, we need to do another pass
+    fi
+  done
+}
+
 injectImportedFunctions() {
   local file="$1"
+  # shellcheck disable=SC2034
   local -n filesImported=$2
 
-  local functionsNeedToBeImported
+  local needAnotherPass
   local -a functionsToImport
   local iteration zzzFile fileToImport underscoreFile
   local importedFunctionsTempFile
@@ -272,74 +342,16 @@ injectImportedFunctions() {
   local importedZZZTempFile
   importedZZZTempFile="$(mktemp -p "${TMPDIR:-/tmp}" -t "imported_zzz_files.XXXXXXX")"
 
-  ((functionsNeedToBeImported = 1))
+  ((needAnotherPass = 1))
   ((iteration = 1))
-  while ((functionsNeedToBeImported >= 1)); do
+  while ((needAnotherPass >= 1)); do
     if [[ "${DEBUG:-0}" = "1" ]]; then
       (echo >&2 -e "${__DEBUG_COLOR}\tIteration #${iteration}${__RESET_COLOR}")
     fi
     echo >"${importedFunctionsTempFile}"
     echo >"${importedZZZTempFile}"
 
-    readarray -t functionsToImport < <(
-      Filters::bashFrameworkFunctions "${file}" |
-        awk '{$1=$1};1' |
-        sort |
-        uniq
-    )
-    ((functionsNeedToBeImported = 0)) || true
-    for functionToImport in "${functionsToImport[@]}"; do
-      if echo "${functionToImport}" | grep -q -E "${FRAMEWORK_FUNCTIONS_IGNORE_REGEXP}"; then
-        (echo >&2 -e "${__DEBUG_COLOR}\tFunction ${functionToImport} ignored, because of rule defined in ${configFile}${__RESET_COLOR}")
-        continue
-      fi
-
-      local fileNameToImport
-      fileNameToImport="$(echo "${functionToImport}" | sed -E 's#::#/#g').sh"
-      # search through srcDirs the file to import
-      for srcDir in "${srcDirs[@]}"; do
-        fileToImport="${srcDir}/${fileNameToImport}"
-        if [[ -f "${fileToImport}" ]]; then
-          # we found it
-          break
-        fi
-      done
-
-      if ! Array::contains "${fileToImport}" "${filesImported[@]}"; then
-        if [[ -f "${fileToImport}" ]]; then
-          # check if we need to import _.sh
-          underscoreFile="$(dirname "${fileToImport}")/_.sh"
-          if ! Array::contains "${underscoreFile}" "${filesImported[@]}" &&
-            [[ -f "${underscoreFile}" ]]; then
-            if [[ "${DEBUG:-0}" = "1" ]]; then
-              (echo >&2 -e "${__DEBUG_COLOR}\tImporting ${underscoreFile} ...${__RESET_COLOR}")
-            fi
-            Filters::catFileCleaned "${underscoreFile}" >>"${importedFunctionsTempFile}"
-            filesImported+=("${underscoreFile}")
-          fi
-          # check if we need to import ZZZ.sh
-          zzzFile="$(dirname "${fileToImport}")/ZZZ.sh"
-          if ! Array::contains "${zzzFile}" "${filesImported[@]}" &&
-            [[ -f "${zzzFile}" ]]; then
-            if [[ "${DEBUG:-0}" = "1" ]]; then
-              (echo >&2 -e "${__DEBUG_COLOR}\tImporting ${zzzFile} ...${__RESET_COLOR}")
-            fi
-            Filters::catFileCleaned "${zzzFile}" >>"${importedZZZTempFile}"
-            filesImported+=("${zzzFile}")
-          fi
-
-          if [[ "${DEBUG:-0}" = "1" ]]; then
-            (echo >&2 -e "\t${__DEBUG_COLOR}Importing ${fileToImport} ...${__RESET_COLOR}")
-          fi
-          Filters::catFileCleaned "${fileToImport}" >>"${importedFunctionsTempFile}"
-        else
-          (echo >&2 -e "${__ERROR_COLOR}\tFile ${fileToImport} does not exist${__RESET_COLOR}")
-          ((failures++)) || true
-        fi
-        filesImported+=("${fileToImport}")
-        ((functionsNeedToBeImported = 1)) # as we added some files, we need to do another pass
-      fi
-    done
+    importFunctions "${importedFunctionsTempFile}" "${importedZZZTempFile}" filesImported needAnotherPass
 
     # insert functions before # FUNCTIONS
     sed -E -i "/# FUNCTIONS/ e cat ${importedFunctionsTempFile}\n" "${file}"
