added frameworkLint command

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -17,6 +17,8 @@ source "${_COMPILE_SRC_DIR}/_includes/_header.sh"
 source "${_COMPILE_SRC_DIR}/Array/contains.sh"
 # shellcheck source=src/Env/load.sh
 source "${_COMPILE_SRC_DIR}/Env/load.sh"
+# shellcheck source=src/File/upFind.sh
+source "${_COMPILE_SRC_DIR}/File/upFind.sh"
 # shellcheck source=src/Log/__all.sh
 source "${_COMPILE_SRC_DIR}/Log/__all.sh"
 # shellcheck source=/src/Filters/removeDuplicatedShebangs.sh
@@ -152,6 +154,18 @@ SRC_FILE_PATH="$2"
 # how to join ROOT_DIR from target BIN_FILE directory
 ROOT_DIR_RELATIVE_TO_BIN_DIR="$3"
 
+# try to find .framework-config
+FRAMEWORK_FUNCTIONS_IGNORE_REGEXP=^$
+NON_FRAMEWORK_FILES_REGEXP=
+for srcDir in "${srcDirs[@]}"; do
+  configFile="$(File::upFind "${srcDir}" ".framework-config" || true)"
+  if [[ -n "${configFile}" ]]; then
+    # shellcheck source=/.framework-config
+    source "${configFile}" || Log::fatal "error while loading config file '${configFile}'"
+    Log::displayDebug "Config file ${configFile} is loaded"
+  fi
+done
+
 ################################################
 # compile Algo
 ################################################
@@ -227,6 +241,11 @@ injectImportedFunctions() {
     )
     ((functionsNeedToBeImported = 0)) || true
     for functionToImport in "${functionsToImport[@]}"; do
+      if echo "${functionToImport}" | grep -q -E "${FRAMEWORK_FUNCTIONS_IGNORE_REGEXP}"; then
+        (echo >&2 -e "${__DEBUG_COLOR}\tFunction ${functionToImport} ignored, because of rule defined in ${configFile}${__RESET_COLOR}")
+        continue
+      fi
+
       local fileNameToImport
       fileNameToImport="$(echo "${functionToImport}" | sed -E 's#::#/#g').sh"
       # search through srcDirs the file to import
@@ -290,7 +309,7 @@ declare -a FILES_IMPORTED=("${INPUT_FILE}")
 injectImportedFunctions "${COMPILED_FILE}" FILES_IMPORTED
 
 # evaluate again the current compiledFile as a template in the case
-# where injected function are using template function (include files like Framework::loadEnv
+# where injected function are using template function (include files like Env::load
 if [[ "${DEBUG:-0}" = "1" ]]; then
   (echo >&2 -e "${__DEBUG_COLOR}\tevalTemplate2${__RESET_COLOR}")
 fi
