Fixed configuration loading management (#55)
Options overrriding .framework-config parameters were not taken 
into account.
Improved tooling.

tag: 2.2.0

# Breaking changes

N/A

# Bug fixes

- fixed regression - global options passed to the command was not
  taken into account(--verbose, -no-color, --log-level, ...)
- added shortcuts for --log-level and --display-level options

# Compiler changes

- replaced usage of process substitution `<(command)` by `shopt -u lastpipe` 
  and pipe usage instead. Removed process substitution because error in 
  command is not catched by parent script.

# Binaries changes

- all binaries are using
  - shopt -s lastpipe headers change

# Updated Bash framework functions

N/A

# New Bash framework functions

N/A

# Documentation

N/A

# Validation/Tooling

- updated pre-commit hooks versions
- upgraded github actions/deploy-pages from v2 to v4
- Fixed Array::wrap2 tests flakiness
- make pre-commit lighter for local development

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -399,8 +399,8 @@ importFunctions() {
   local -a requireFunctionsToImport
   local functionToImport
 
-  readarray -t functionsToImport < <(Compiler::extractUniqueFrameworkFunctions "${file}")
-  readarray -t requireFunctionsToImport < <(Compiler::Require::requires "${file}")
+  Compiler::extractUniqueFrameworkFunctions "${file}" | readarray -t functionsToImport
+  Compiler::Require::requires "${file}" | readarray -t requireFunctionsToImport
   functionsToImport+=("${requireFunctionsToImport[@]}")
 
   ((newFilesAdded = 0)) || true
@@ -577,4 +577,8 @@ cat -s "${COMPILED_FILE2}" | Filters::directive "${FILTER_DIRECTIVE_REMOVE_HEADE
 chmod +x "${BIN_FILE}"
 
 Log::displayStatus "Compiled '${CURRENT_COMPILED_RELATIVE_FILE}' to Binfile '${BIN_FILE}'"
-exit "${failures}"
+
+if [[ "${failures}" != "0" ]]; then
+  Log::displayError "Found ${failures} errors during compilation"
+  exit 1
+fi
