added Log::displayStatus and Log::logStatus to allow important command information to be displayed (displayed with level warning but color info)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -253,6 +253,7 @@ if [[ -z "${BIN_DIR+xxx}" ]]; then
 fi
 export BIN_DIR
 FRAMEWORK_FUNCTIONS_IGNORE_REGEXP=^$
+loggedMessages=()
 
 # load .framework-config
 configFile=""
@@ -354,18 +355,24 @@ importFunctions() {
   readarray -t functionsToImport < <(Compiler::extractUniqueFrameworkFunctions "${file}")
 
   ((newFilesAdded = 0)) || true
-  if [[ "${DEBUG:-0}" = "1" ]]; then
-    echo >&2 "importing ${file} with ${#functionsToImport[@]} functions to import"
+  if [[ "${ARGS_VERBOSE:-0}" = "2" ]]; then
+    Log::displayDebug "importing ${file} with ${#functionsToImport[@]} functions to import"
   fi
   for functionToImport in "${functionsToImport[@]}"; do
     if echo "${functionToImport}" | grep -q -E "${FRAMEWORK_FUNCTIONS_IGNORE_REGEXP}"; then
-      (echo >&2 -e "${__DEBUG_COLOR}\tFunction ${functionToImport} ignored, because of rule defined in ${configFile}${__RESET_COLOR}")
+      if [[ "${ARGS_VERBOSE:-0}" = "1" ]]; then
+        msg="File ${INPUT_FILE} Function ${functionToImport} ignored, because of rule defined in ${configFile}"
+        if ! Array::contains "${msg}" "${loggedMessages[@]}"; then
+          loggedMessages+=("${msg}")
+          Log::displayHelp "${msg}" "HINT"
+        fi
+      fi
       continue
     fi
 
     local fileToImport
     fileToImport="$(Compiler::findFunctionInSrcDirs "${functionToImport}" "${srcDirs[@]}")" || {
-      (echo >&2 -e "${__ERROR_COLOR}\tFunction ${functionToImport} not found in any src directories${__RESET_COLOR}")
+      Log::displayError "File ${INPUT_FILE} Function ${functionToImport} not found in any src directories"
       ((importFailures++)) || true
       continue
     }
@@ -393,7 +400,7 @@ importFunctions() {
       # shellcheck disable=SC2034
       ((newFilesAdded = 1)) # as we added some files, we need to do another pass
     else
-      (echo >&2 -e "${__ERROR_COLOR}\tFile ${fileToImport} does not exist${__RESET_COLOR}")
+      Log::displayError "File ${INPUT_FILE} File ${fileToImport} does not exist${__RESET_COLOR}"
       # even if not existing, consider the file as imported to avoid other same errors
       filesImportedWithFunctions+=("${fileToImport}")
       ((importFailures++)) || true
@@ -419,8 +426,8 @@ injectImportedFunctions() {
   ((needAnotherPass = 1))
   ((iteration = 1))
   while ((needAnotherPass >= 1)); do
-    if [[ "${DEBUG:-0}" = "1" ]]; then
-      (echo >&2 -e "${__DEBUG_COLOR}\tIteration #${iteration}${__RESET_COLOR}")
+    if [[ "${ARGS_VERBOSE:-0}" = "2" ]]; then
+      Log::displayDebug "File ${INPUT_FILE} Iteration #${iteration}"
     fi
     echo >"${importedFunctionsTempFile}"
     echo >"${importedZZZTempFile}"
@@ -485,7 +492,7 @@ if [[ -z "${BIN_FILE}" ]]; then
     exit 0
   fi
 fi
-Log::displayInfo "Binfile ${BIN_FILE} from ${INPUT_FILE}"
+Log::displayInfo "Compiling ${INPUT_FILE} ..."
 
 # inject embed
 injectEmbed "${COMPILED_FILE}"
@@ -514,4 +521,5 @@ sed -E -i 's/[[:blank:]]+$//' "${COMPILED_FILE2}"
 cat -s "${COMPILED_FILE2}" | Filters::directive "${FILTER_DIRECTIVE_REMOVE_HEADERS}" >"${BIN_FILE}"
 chmod +x "${BIN_FILE}"
 
+Log::displayStatus "Compiled ${INPUT_FILE} to Binfile ${BIN_FILE}"
 exit "${failures}"
diff --git a/bin/findShebangFiles b/bin/findShebangFiles
--- a/bin/findShebangFiles
+++ b/bin/findShebangFiles
@@ -319,8 +319,9 @@ Log::displayDebug() {
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
-  Log::logInfo "$1"
+  local type="${2:-INFO}"
+  echo -e "${__INFO_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
+  Log::logInfo "$1" "${type}"
 }
 
 # shellcheck disable=SC2317
@@ -338,6 +339,7 @@ Log::load() {
   fi
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_WARNING)); then
     Log::displayWarning() { :; }
+    Log::displayStatus() { :; }
   fi
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_ERROR)); then
     Log::displayError() { :; }
@@ -354,6 +356,7 @@ Log::load() {
   fi
   if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_WARNING)); then
     Log::logWarning() { :; }
+    Log::logStatus() { :; }
   fi
   if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_ERROR)); then
     Log::logError() { :; }
@@ -418,8 +421,9 @@ Log::displayError() {
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayHelp() {
-  echo -e "${__HELP_COLOR}HELP    - ${1}${__RESET_COLOR}" >&2
-  Log::logHelp "$1"
+  local type="${2:-HELP}"
+  echo -e "${__HELP_COLOR}${type}    - ${1}${__RESET_COLOR}" >&2
+  Log::logHelp "$1" "${type}"
 }
 
 # Display message using skip color (yellow)
@@ -427,6 +431,14 @@ Log::displayHelp() {
 Log::displaySkipped() {
   echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
   Log::logSkipped "$1"
+}
+
+# Display message using info color (blue) but warning level
+# @param {String} $1 message
+Log::displayStatus() {
+  local type="${2:-STATUS}"
+  echo -e "${__INFO_COLOR}${type}  - ${1}${__RESET_COLOR}" >&2
+  Log::logStatus "$1" "${type}"
 }
 
 # Display message using success color (bg green/fg white)
@@ -446,43 +458,49 @@ Log::displayWarning() {
 # log message to file
 # @param {String} $1 message
 Log::logDebug() {
-  Log::logMessage "DEBUG" "$@"
+  Log::logMessage "${2:-DEBUG}" "$@"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logError() {
-  Log::logMessage "ERROR" "$@"
+  Log::logMessage "${2:-ERROR}" "$@"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logHelp() {
-  Log::logMessage "HELP" "$@"
+  Log::logMessage "${2:-HELP}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logInfo() {
-  Log::logMessage "INFO" "$@"
+  Log::logMessage "${2:-INFO}" "$1"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logSkipped() {
-  Log::logMessage "SKIPPED" "$@"
+  Log::logMessage "${2:-SKIPPED}" "$@"
+}
+
+# log message to file
+# @param {String} $1 message
+Log::logStatus() {
+  Log::logMessage "${2:-STATUS}" "$@"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logSuccess() {
-  Log::logMessage "SUCCESS" "$@"
+  Log::logMessage "${2:-SUCCESS}" "$@"
 }
 
 # log message to file
 # @param {String} $1 message
 Log::logWarning() {
-  Log::logMessage "WARNING" "$@"
+  Log::logMessage "${2:-WARNING}" "$@"
 }
 
 # To be called before logging in the log file
