frameworkLint - added shdoc checks sh doc on all bash framework functions added require function for several commands added several unit tests

diff --git a/bin/doc b/bin/doc
--- a/bin/doc
+++ b/bin/doc
@@ -139,7 +139,7 @@ fi
 # @option -h short help option
 # @option --help long help option
 # @exitcode 0 displays help and exit with code 0 if -h or --help option is in the args list
-# @output displays help if -h or --help option is in the args list
+# @stdout displays help if -h or --help option is in the args list
 Args::defaultHelp() {
   local helpArg=$1
   shift || true
@@ -363,6 +363,18 @@ Log::displayInfo() {
 
 # shellcheck disable=SC2317
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
 Log::load() {
   # disable display methods following display level
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
@@ -420,8 +432,11 @@ Log::load() {
   fi
 }
 
-# fix markdown TOC generated by Markdown all in one vscode extension
-# https://regex101.com/r/DJJf2I/1
+# @description fix markdown TOC generated by Markdown all in one vscode extension
+# to make TOC compatible with docsify
+# @arg $1 file:String file to fix
+# @exitcode 1 if awk fails
+# @see https://regex101.com/r/DJJf2I/1
 ShellDoc::fixMarkdownToc() {
   local file="$1"
   local fixMarkdownToc
@@ -447,16 +462,18 @@ EOF
   awk -i inplace "${fixMarkdownToc}" "${file}"
 }
 
-# generate markdown file from template by replacing
-# @@@command_help@@@ by the help of the command
+# @description generates markdown file from template by
+# replacing @@@command_help@@@ by the help of the command
 # eg: @@@test_help@@@ will be replaced by the output
 # of the command `test --help` in the directory provided
 #
 # @arg $1 templateFile:String the file to use as template
 # @arg $2 targetFile:String the target file
 # @arg $3 fromDir:String the directory from which commands will be searched
-# @arg $4 tokenNotFoundCount:int passed by reference, number of tokens @@@command_help@@@ not found in the template file
-# @arg $5 excludeFilesPattern:String grep exclude pattern (eg: '^(bash-tpl)$')
+# @arg $4 tokenNotFoundCount:&int (passed by reference) number of tokens @@@command_help@@@ not found in the template file
+# @arg $5 excludeFilesPattern:String grep exclude pattern (eg: '^(bash-tpl)$') (default value: "")
+# @stderr diagnostics logs
+# @stdout the generated markdown with help of the matching command
 ShellDoc::generateMdFileFromTemplate() {
   local templateFile="$1"
   local targetFile="$2"
@@ -549,6 +566,15 @@ ShellDoc::generateShellDocsFromDir() {
 BASH_FRAMEWORK_SHDOC_INSTALLED="${FRAMEWORK_ROOT_DIR}/vendor/.shDocInstalled"
 BASH_FRAMEWORK_SHDOC_CHECK_TIMEOUT=86400 # 1 day
 
+# @description install requirements to execute shdoc
+# @warning cloning is skipped if vendor/.shDocInstalled file exists
+# @warning a new check is done everyday
+# @warning repository is not updated if a change is detected
+# @env BASH_FRAMEWORK_SHDOC_CHECK_TIMEOUT int default value 86400 (86400 seconds = 1 day)
+# @set BASH_FRAMEWORK_SHDOC_INSTALLED String the file created when git clone succeeded
+# @see https://github.com/fchastanet/shdoc
+# @stderr diagnostics information is displayed
+# @feature Git::cloneOrPullIfNoChanges
 ShellDoc::installRequirementsIfNeeded() {
   if [[ "$(
     Cache::getFileContentIfNotExpired \
@@ -572,7 +598,7 @@ ShellDoc::installRequirementsIfNeeded() {
 # @option -h short help option
 # @option --help long help option
 # @exitcode 1 displays help and returns with code 1 if -h or --help option is in the args list
-# @output displays help if -h or --help option is in the args list
+# @stdout displays help if -h or --help option is in the args list
 Args::defaultHelpNoExit() {
   local helpArg=$1
   shift || true
@@ -620,6 +646,12 @@ Cache::getFileContentIfNotExpired() {
   cat "${file}"
 }
 
+# @description replace token by input(stdin) in given targetFile
+# @warning special ansi codes will be removed from stdin
+# @arg $1 token:String the token to replace by stdin
+# @arg $2 targetFile:String the file in which token will be replaced by stdin
+# @exitcode 1 if error
+# @stdin the file content that will be injected in targetFile
 File::replaceTokenByInput() {
   local token="$1"
   local targetFile="$2"
@@ -628,7 +660,7 @@ File::replaceTokenByInput() {
     local tokenFile
     tokenFile="$(Framework::createTempFile "replaceTokenByInput")"
 
-    cat - | Filters::escapeColorCodes >"${tokenFile}"
+    cat - | Filters::removeAnsiCodes >"${tokenFile}"
 
     sed -E -i \
       -e "/${token}/r ${tokenFile}" \
@@ -886,13 +918,13 @@ ShellDoc::generateShellDocDir() {
 
 # @description display help
 # @arg $1 helpArg:String the help string to show
-# @output display help arg
+# @stdout display help arg
 Args::showHelp() {
   local helpArg="$1"
   echo -e "${helpArg}"
 }
 
-# @description Number of seconds since last modification of the file
+# @description get number of seconds since last modification of the file
 # @arg $1 file:String file path
 # @exitcode 1 if file does not exist
 # @stdout number of seconds since last modification of the file
@@ -907,36 +939,49 @@ File::elapsedTimeSinceLastModification() {
   echo -n "${diff}"
 }
 
-Filters::escapeColorCodes() {
-  cat - | sed -E $'s/\e\\[[0-9;:]*[a-zA-Z]//g'
+# @description remove ansi codes from input or files given as argument
+# @arg $@ files:String[] the files to filter
+# @exitcode * if one of the filter command fails
+# @stdin you can use stdin as alternative to files argument
+# @stdout the filtered content
+# @see https://en.wikipedia.org/wiki/ANSI_escape_code
+# shellcheck disable=SC2120
+Filters::removeAnsiCodes() {
+  sed -E 's/\x1b\[[0-9;]*[mGKHF]//g' "$@"
 }
 
 # @description create a temp file using default TMPDIR variable
 # initialized in src/_includes/_header.tpl
-#
-# @arg $1 {templateName:String} template name to use(optional)
+# @env TMPDIR String (default value /tmp)
+# @arg $1 templateName:String template name to use(optional)
 Framework::createTempFile() {
-  mktemp -p "${TMPDIR:-/tmp}" -t "$1.XXXXXXXXXXXX"
+  mktemp -p "${TMPDIR:-/tmp}" -t "${1:-}.XXXXXXXXXXXX"
 }
 
-# pull the repository if no change in it
-# @exitcode 0 on successful pulling, 1 on failure or no pull needed
+# @description pull git directory only if no change has been detected
+# @arg $1 dir:String the git directory to pull
+# @exitcode 0 on successful pulling
+# @exitcode 1 on any other failure
+# @exitcode 2 changes detected, pull avoided
+# @exitcode 3 not a git directory
+# @exitcode 4 not able to update index
+# @stderr diagnostics information is displayed
+# @require Git::requireGitCommand
 Git::pullIfNoChanges() {
   local dir="$1"
-  if [[ -d "${dir}/.git" ]]; then
-    (
-      cd "${dir}"
-      git update-index --refresh &>/dev/null || true
-      if git diff-index --quiet HEAD --; then
-        Log::displayInfo "Pull git repository '${dir}' as no changes detected"
-        git pull --progress
-        return 0
-      else
-        Log::displayWarning "Pulling git repository '${dir}' avoided as changes detected"
-      fi
-    ) && return 0
+  if [[ ! -d "${dir}/.git" ]]; then
+    return 3
   fi
-  return 1
+  (
+    cd "${dir}" || exit 3
+    git update-index --refresh &>/dev/null || exit 4
+    if ! git diff-index --quiet HEAD --; then
+      Log::displayWarning "Pulling git repository '${dir}' avoided as changes detected"
+      exit 2
+    fi
+    Log::displayInfo "Pull git repository '${dir}' as no changes detected"
+    git pull --progress
+  )
 }
 
 # @description log message to file
@@ -945,16 +990,19 @@ Log::logFatal() {
   Log::logMessage "${2:-FATAL}" "$1"
 }
 
-# Internal: common log message
-#
-# @arg $1 levelMsg:String message's level description
-# @arg $2 msg:String the message to display
-# @output text
+# @description Internal: common log message
+# @example text
 #   [date]|[levelMsg]|message
 #
-# @example
+# @example text
 #   2020-01-19 19:20:21|ERROR  |log error
 #   2020-01-19 19:20:21|SKIPPED|log skipped
+#
+# @arg $1 levelMsg:String message's level description (eg: STATUS, ERROR, ...)
+# @arg $2 msg:String the message to display
+# @env BASH_FRAMEWORK_LOG_FILE String log file to use, do nothing if empty
+# @env BASH_FRAMEWORK_LOG_LEVEL int log level log only if > OFF or fatal messages
+# @stderr diagnostics information is displayed
 Log::logMessage() {
   local levelMsg="$1"
   local msg="$2"
@@ -1119,6 +1167,7 @@ mkdir -p "${DOC_DIR}/images" || true
 cp -R "${FRAMEWORK_ROOT_DIR}/images/"* "${DOC_DIR}/images"
 cp "${FRAMEWORK_ROOT_DIR}/BestPractices.md" "${DOC_DIR}"
 cp "${FRAMEWORK_ROOT_DIR}/CompileCommand.md" "${DOC_DIR}"
+cp "${FRAMEWORK_ROOT_DIR}/src/Docker/DockerUsage.md" "${DOC_DIR}/DockerUsage.md"
 
 Log::displayInfo 'generate FrameworkFullDoc.md'
 cp "${FRAMEWORK_ROOT_DIR}/FrameworkFullDoc.tmpl.md" "${DOC_DIR}/FrameworkFullDoc.md"
diff --git a/bin/dockerLint b/bin/dockerLint
--- a/bin/dockerLint
+++ b/bin/dockerLint
@@ -139,7 +139,7 @@ fi
 # @option -h short help option
 # @option --help long help option
 # @exitcode 1 displays help and returns with code 1 if -h or --help option is in the args list
-# @output displays help if -h or --help option is in the args list
+# @stdout displays help if -h or --help option is in the args list
 Args::defaultHelpNoExit() {
   local helpArg=$1
   shift || true
@@ -432,6 +432,18 @@ Log::displayInfo() {
 
 # shellcheck disable=SC2317
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
 Log::load() {
   # disable display methods following display level
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
@@ -529,7 +541,7 @@ Version::checkMinimal() {
 
 # @description display help
 # @arg $1 helpArg:String the help string to show
-# @output display help arg
+# @stdout display help arg
 Args::showHelp() {
   local helpArg="$1"
   echo -e "${helpArg}"
@@ -541,8 +553,8 @@ Args::showHelp() {
 # @arg $1 commandName:String on which existence must be checked
 # @arg $2 helpIfNotExists:String a help command to display if the command does not exist
 #
-# @exitCode 1 if the command specified does not exist
-# @stderr diagnotics information + help if second argument is provided
+# @exitcode 1 if the command specified does not exist
+# @stderr diagnostic information + help if second argument is provided
 Assert::commandExists() {
   local commandName="$1"
   local helpIfNotExists="$2"
@@ -557,6 +569,23 @@ Assert::commandExists() {
   return 0
 }
 
+# @description intermediate callback that is used by Github::upgradeRelease
+# or Github::installRelease
+# if installCallback is not set, it allows to:
+#   - copy the downloaded file to the right target file
+#   - and set the execution bit
+# else
+#   installCallback is called with newSoftware, targetFile, version arguments
+# fi
+# @warning do not use this function as callback for Github::upgradeRelease or Github::installRelease, as it would result to an infinite loop
+# @arg $1 newSoftware:String the downloaded software file
+# @arg $2 targetFile:String where we want to copy the file
+# @arg $3 version:String the version that has been downloaded
+# @arg $4 installCallback:Function (optional) the callback to call with 3 first arguments
+# @exitcode * on failure
+# @see Github::upgradeRelease
+# @see Github::installRelease
+# @internal
 Github::defaultInstall() {
   local newSoftware="$1"
   local targetFile="$2"
@@ -568,10 +597,10 @@ Github::defaultInstall() {
     ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
   else
     mv "${newSoftware}" "${targetFile}"
+    chmod +x "${targetFile}"
+    hash -r
+    rm -f "${newSoftware}" || true
   fi
-  chmod +x "${targetFile}"
-  hash -r
-  rm -f "${newSoftware}" || true
 }
 
 # @description github repository eg: kubernetes-sigs/kind
@@ -787,10 +816,14 @@ Version::getCommandVersionFromPlainText() {
     Version::parse # keep only version numbers
 }
 
-# filter to keep only version number from a string
-# @stdin the string to parse
+# @description filter to keep only version number from a string
+# @arg $@ files:String[] the files to filter
+# @exitcode * if one of the filter command fails
+# @stdin you can use stdin as alternative to files argument
+# @stdout the filtered content
+# shellcheck disable=SC2120
 Version::parse() {
-  sed -En 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' | head -n1
+  sed -En 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' "$@" | head -n1
 }
 
 # @description log message to file
@@ -799,16 +832,19 @@ Log::logFatal() {
   Log::logMessage "${2:-FATAL}" "$1"
 }
 
-# Internal: common log message
-#
-# @arg $1 levelMsg:String message's level description
-# @arg $2 msg:String the message to display
-# @output text
+# @description Internal: common log message
+# @example text
 #   [date]|[levelMsg]|message
 #
-# @example
+# @example text
 #   2020-01-19 19:20:21|ERROR  |log error
 #   2020-01-19 19:20:21|SKIPPED|log skipped
+#
+# @arg $1 levelMsg:String message's level description (eg: STATUS, ERROR, ...)
+# @arg $2 msg:String the message to display
+# @env BASH_FRAMEWORK_LOG_FILE String log file to use, do nothing if empty
+# @env BASH_FRAMEWORK_LOG_LEVEL int log level log only if > OFF or fatal messages
+# @stderr diagnostics information is displayed
 Log::logMessage() {
   local levelMsg="$1"
   local msg="$2"
@@ -866,8 +902,12 @@ Retry::parameterized() {
   return 0
 }
 
-# extract version number from github api
+# @description extract version number from github api
+# @noargs
 # @stdin json result of github API
+# @exitcode 1 if jq or Version::parse fails
+# @stdout the version parsed
+# @require Linux::requireJqCommand
 Version::githubApiExtractVersion() {
   jq -r ".tag_name" | Version::parse
 }
diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -217,6 +217,50 @@ Assert::bashFile() {
   [[ "${head}" =~ ^#\!.*bash ]]
 }
 
+# @description assert that first arg respects this bash framework naming convention
+# @arg $1 bashFrameworkFunction:String the function's name to assert
+# @exitcode 1 if bashFrameworkFunction arg doesn't respect this bash framework naming convention
+Assert::bashFrameworkFunction() {
+  local bashFrameworkFunction="$1"
+  local expectedRegexp="^([A-Za-z0-9_]+[A-Za-z0-9_-]*::)+([a-zA-Z0-9_-]+)\$"
+
+  [[ "${bashFrameworkFunction}" =~ ${expectedRegexp} ]]
+}
+
+# @description convert function name to path replacing :: by /
+# @internal
+convertFunctionNameToPath() {
+  local functionName="$1"
+  echo "$(sed -E 's#::#/#g' <<<"${functionName}").sh"
+}
+
+# @description return the path of the function found in srcDirs
+# @arg $1 functionName:String function name (eg: Functions::myFunction)
+# @arg $@ srcDirs:String[] rest of args list of src directories in # which the function will be searched
+# @exitcode 1 if function not found
+# @exitcode 0 if found
+# @stdout the filepath of the function if found
+Compiler::findFunctionInSrcDirs() {
+  local functionName="$1"
+  shift || true
+  local -a srcDirs=("$@")
+  local fileNameToImport
+
+  fileNameToImport="$(convertFunctionNameToPath "${functionName}")"
+
+  # search through srcDirs the file to import
+  for srcDir in "${srcDirs[@]}"; do
+    fileToImport="${srcDir}/${fileNameToImport}"
+    if [[ -f "${fileToImport}" ]]; then
+      # we found it
+      echo "${fileToImport}"
+      return 0
+    fi
+  done
+
+  return 1
+}
+
 # lazy initialization
 declare -g BASH_FRAMEWORK_CACHED_ENV_FILE
 declare -g BASH_FRAMEWORK_DEFAULT_ENV_FILE
@@ -340,6 +384,12 @@ declare missingBashFileList
 missingBashFileList=""
 export missingBashFileList
 
+# @description check if file provided is a bash file
+# @arg $1 file:String
+# @arg $@ args:String[]
+# @set missingBashFileList String temp filepath that contains eventual missing files
+# @stdout filepath if Assert::bashFile succeed
+# @see Assert::bashFile
 File::detectBashFile() {
   local file="$1"
 
@@ -357,8 +407,8 @@ File::detectBashFile() {
 
 # @description print the resolved path relative to DIR
 # do not check for path existence
-# @arg $1 srcFile:string the file to resolve
-# @arg $2 relativeTo:string the directory
+# @arg $1 srcFile:String the file to resolve
+# @arg $2 relativeTo:String the directory
 # @stdout the resolved path relative to DIR
 File::relativeToDir() {
   local srcFile="$1"
@@ -367,24 +417,46 @@ File::relativeToDir() {
   realpath -m --relative-to="${relativeTo}" "${srcFile}"
 }
 
+# @description allows to match a bash framework function based on the naming convention
+# @warning this filter could extract bash framework functions that are actually commented in the source file
+# @warning use FRAMEWORK_FUNCTIONS_IGNORE_REGEXP from .framework-config to filter unwanted functions
+# @arg $@ files:String[] the files in which bash framework functions will be extracted
+# @env PREFIX String an eventual prefix you would like to match
+# @env FRAMEWORK_FUNCTIONS_IGNORE_REGEXP String this filter does not use this variable
+# @exitcode 0 if match or no match
+# @exitcode 2 if grep fails for other reasons
+# @stdin you can alternatively provide content to filter via stdin
+# @stdout the list of bash framework function detected
+# @see [bash framework functions naming convention](/CompileCommand.md#bash_framework_functions_naming_convention)
 # shellcheck disable=SC2120
 Filters::bashFrameworkFunctions() {
-  grep -Eo "${PREFIX:-}([A-Za-z0-9_]+[A-Za-z0-9_-]*::)+([a-zA-Z0-9_-]+)" "$@" || test $? = 1
+  grep -Eo "${PREFIX:-}([A-Z]+[A-Za-z0-9_-]*::)+([a-zA-Z0-9_-]+)" "$@" || test $? = 1
 }
 
+# @description remove comment lines from input or files provided as arguments
+# @arg $@ files:String[] (optional) the files to filter
+# @env commentLinePrefix String the comment line prefix (default value: #)
+# @exitcode 0 if lines filtered or not
+# @exitcode 2 if grep fails for any other reasons than not found
+# @stdin the file as stdin to filter (alternative to files argument)
+# @stdout the filtered lines
 # shellcheck disable=SC2120
 Filters::commentLines() {
   grep -vxE "[[:blank:]]*(${commentLinePrefix:-#}.*)?" "$@" || test $? = 1
 }
 
-# @arg $@ string[] the src directories in which .framework-config file will be searched
+# @description load .framework-config
+# @arg $1 loadedConfigFile:&String (passed by reference) the finally loaded configuration file path
+# @arg $@ srcDirs:String[] the src directories in which .framework-config file will be searched
 # @stdout the config file path loaded if any
 # @exitcode 0 if .framework-config file has been found in srcDirs provided
+# @exitcode 1 if .framework-config file not found
+# @see Conf::loadNearestFile
 Framework::loadConfig() {
   # shellcheck disable=SC2034
-  local -n loadedConfigFile=$1
+  local -n loadConfig_loadedConfigFile=$1
   shift || true
-  Conf::loadNearestFile ".framework-config" loadedConfigFile "$@"
+  Conf::loadNearestFile ".framework-config" loadConfig_loadedConfigFile "$@"
 }
 
 # @description Log namespace provides 2 kind of functions
@@ -468,6 +540,18 @@ Log::fatal() {
 
 # shellcheck disable=SC2317
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
 Log::load() {
   # disable display methods following display level
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
@@ -525,18 +609,20 @@ Log::load() {
   fi
 }
 
-# Load the nearest config file
-# eg: Conf::loadNearestFile ".framework-config" "srcDir1" "srcDir2"
-# will search first .framework-config file in "srcDir1"
+# @description Load the nearest config file
+# in next example will search first .framework-config file in "srcDir1"
 # then if not found will go in up directories until /
 # then will search in "srcDir2"
 # then if not found will go in up directories until /
 # source the file if found
-# @arg $1 String config file name to search
-# @arg $2 String passed by reference, will return the loaded config file name
-# @arg $@ String source directories in which the config file will be searched
-# @exitcode 0 if file found, 1 if file not found
-# @stdout the filepath loaded if any
+# @example
+#   Conf::loadNearestFile ".framework-config" "srcDir1" "srcDir2"
+#
+# @arg $1 configFileName:String config file name to search
+# @arg $2 loadedFile:String (passed by reference) will return the loaded config file name
+# @arg $@ srcDirs:String[] source directories in which the config file will be searched
+# @exitcode 0 if file found
+# @exitcode 1 if file not found
 Conf::loadNearestFile() {
   local configFileName="$1"
   local -n loadedFile="$2"
@@ -655,7 +741,7 @@ Log::rotate() {
 # @arg $2 fileName:String
 # @arg $3 untilInclusivePath:String (optional) find for given file until reaching this folder (default value: /)
 # @arg $@ untilInclusivePaths:String[] list of untilInclusivePath
-# @output The filename if found
+# @stdout The filename if found
 # @exitcode 1 if the command failed or file not found
 File::upFind() {
   local fromPath="$1"
@@ -681,16 +767,19 @@ File::upFind() {
   return 1
 }
 
-# Internal: common log message
-#
-# @arg $1 levelMsg:String message's level description
-# @arg $2 msg:String the message to display
-# @output text
+# @description Internal: common log message
+# @example text
 #   [date]|[levelMsg]|message
 #
-# @example
+# @example text
 #   2020-01-19 19:20:21|ERROR  |log error
 #   2020-01-19 19:20:21|SKIPPED|log skipped
+#
+# @arg $1 levelMsg:String message's level description (eg: STATUS, ERROR, ...)
+# @arg $2 msg:String the message to display
+# @env BASH_FRAMEWORK_LOG_FILE String log file to use, do nothing if empty
+# @env BASH_FRAMEWORK_LOG_LEVEL int log level log only if > OFF or fatal messages
+# @stderr diagnostics information is displayed
 Log::logMessage() {
   local levelMsg="$1"
   local msg="$2"
@@ -785,6 +874,10 @@ Lint files of the current repository
 - check if all namespace::functions are existing in the framework
 - check that function defined in a .sh is correctly named
 - check each function has a bats file associated
+- shdoc
+  - check that shdoc valid annotations are used
+  - check that @require function matches naming convention and exists
+  - check that at least @description is provided
 
 ${__HELP_TITLE}Options:${__HELP_NORMAL}
   -f|--format <checkstyle,plain>  define output format of this command
@@ -930,12 +1023,8 @@ checkEachSrcFileHasBatsFile() {
   fi
   local batsFile="${file%.*}.bats"
   if [[ ! -f "${FRAMEWORK_ROOT_DIR}/${batsFile}" ]]; then
-    if [[ "${FORMAT}" = "plain" ]]; then
-      Log::displayWarning "checkEachSrcFileHasBatsFile - File '${file}' - missing bats file '${batsFile}'"
-    else
-      echo "<error severity='warning' source='checkEachSrcFileHasBatsFile' message='missing bats file '${batsFile}'/>"
-    fi
-    ((++warningCount))
+    reportWarning "checkEachSrcFileHasBatsFile" "${file}" \
+      "missing bats file '${batsFile}'"
   fi
 }
 
@@ -967,14 +1056,103 @@ checkEachSrcFileHasOneFunctionCorrectlyNamed() {
   done < <(sed -E -n 's#^([^([:blank:]]+)\(\)[[:blank:]]*\{#\1#p' "${srcFile}")
 
   if [[ "${foundFunctionMatching}" = "0" ]]; then
-    if [[ "${FORMAT}" = "plain" ]]; then
-      Log::displayWarning "srcFileHasOneFunctionCorrectlyNamed - File ${srcFile} - no function named '${expectedFunctionName}'"
-    else
-      echo "<error severity='warning' source='srcFileHasOneFunctionCorrectlyNamed' message='Should contain a function named ${expectedFunctionName}'/>"
-    fi
-    ((++warningCount))
+    reportWarning "srcFileHasOneFunctionCorrectlyNamed" "${srcFile}" \
+      "Should contain a function named '${expectedFunctionName}'"
     return 0
   fi
+}
+
+checkEachSrcFileHasCorrectShdoc() {
+  local srcFile="$1"
+  if [[ "${srcFile}" =~ ${NON_FRAMEWORK_FILES_REGEXP} ]]; then
+    Log::displaySkipped "checkEachSrcFileHasCorrectShDoc - File ${srcFile} - rule NON_FRAMEWORK_FILES_REGEXP matches in ${CONFIG_FILENAME}"
+    return 0
+  fi
+  if grep -q -E "${FRAMEWORK_FILES_FUNCTION_MATCHING_IGNORE_REGEXP}" <<<"${srcFile}"; then
+    Log::displaySkipped "checkEachSrcFileHasCorrectShDoc - File ${srcFile} - rule FRAMEWORK_FILES_FUNCTION_MATCHING_IGNORE_REGEXP matches in ${CONFIG_FILENAME}"
+    return 0
+  fi
+
+  # @see https://regex101.com/r/H2Yrwp/1
+  function filterAnnotationNames() {
+    sed -n -E 's/^# @(([^ ]|$)+)[ ]*.*$/\1/p' "$@"
+  }
+
+  # @see https://regex101.com/r/5oMFQi/1
+  # shellcheck disable=SC2120
+  function filterInvalidAnnotationNames() {
+    grep -v -E '^(name|file|brief|description|section|example|option|arg|noargs|set|env|exitcode|stdin|stdout|stderr|see|warning|require|feature|trap|deprecated|internal)$' "$@"
+  }
+
+  function checkValidAnnotationsAreUsed() {
+    local srcFile="$1"
+    local invalidAnnotation
+
+    while IFS='' read -r invalidAnnotation; do
+      reportError "checkEachSrcFileHasCorrectShdoc" "${srcFile}" \
+        "shdoc annotation '@${invalidAnnotation}' is invalid"
+    done < <(filterAnnotationNames "${srcFile}" | filterInvalidAnnotationNames)
+  }
+
+  # check that @require function exists and matches naming convention
+  function checkRequiredFunctionExists() {
+    local srcFile="$1"
+    local requireAnnotation
+
+    while IFS='' read -r requireAnnotation; do
+      if ! Assert::bashFrameworkFunction "${requireAnnotation}"; then
+        reportError "checkEachSrcFileHasCorrectShdoc" "${srcFile}" \
+          "# @require ${requireAnnotation}' does not target a valid bash framework function"
+        continue
+      fi
+      if [[ ! "${requireAnnotation}" =~ ^([A-Za-z0-9_]+[A-Za-z0-9_-]*::)+require([A-Z][a-zA-Z0-9_-]+)$ ]]; then
+        reportError "checkEachSrcFileHasCorrectShdoc" "${srcFile}" \
+          "# @require ${requireAnnotation}' does not target a bash framework function with naming convention namespace::requireSomething"
+        continue
+      fi
+      if ! Compiler::findFunctionInSrcDirs "${requireAnnotation}" "${FRAMEWORK_SRC_DIRS[@]}" >/dev/null; then
+        reportError "checkEachSrcFileHasCorrectShdoc" "${srcFile}" \
+          "# @require ${requireAnnotation}' does not target an existing bash framework function"
+      fi
+    done < <(sed -n -E 's/^# @require (.*)$/\1/p' "${srcFile}")
+  }
+
+  function checkDescriptionAnnotationIsProvided() {
+    local srcFile="$1"
+    if ! grep -q -E '^# @description .*' "${srcFile}"; then
+      reportError "checkEachSrcFileHasCorrectShdoc" "${srcFile}" \
+        "missing mandatory sh doc @description annotation"
+    fi
+  }
+
+  checkValidAnnotationsAreUsed "${srcFile}"
+  checkRequiredFunctionExists "${srcFile}"
+  checkDescriptionAnnotationIsProvided "${srcFile}"
+
+}
+
+reportError() {
+  local category="$1"
+  local file="$2"
+  local msg="$3"
+  if [[ "${FORMAT}" = "plain" ]]; then
+    Log::displayError "${category} - File ${file} - ${msg}"
+  else
+    echo "<error severity='error' source='${category}' message='$(sed -E "s/'/\"/g" <<<"${msg}")'/>"
+  fi
+  ((++errorCount))
+}
+
+reportWarning() {
+  local category="$1"
+  local file="$2"
+  local msg="$3"
+  if [[ "${FORMAT}" = "plain" ]]; then
+    Log::displayWarning "${category} - File ${file} - ${msg}"
+  else
+    echo "<error severity='warning' source='${category}' message='$(sed -E "s/'/\"/g" <<<"${msg}")'/>"
+  fi
+  ((++warningCount))
 }
 
 ((errorCount = 0)) || true
@@ -995,6 +1173,7 @@ while IFS='' read -r file; do
   checkEachFunctionHasSrcFile "${file}" "$@" || ((++errorCount))
   checkEachSrcFileHasOneFunctionCorrectlyNamed "${file}" "$@" || ((++errorCount))
   checkEachSrcFileHasBatsFile "${file}" "$@" || ((++errorCount))
+  checkEachSrcFileHasCorrectShdoc "${file}" "$@" || ((++errorCount))
 
   if [[ "${FORMAT}" = "checkstyle" ]]; then
     echo "</file>"
@@ -1007,14 +1186,14 @@ done < <(
 
 # shellcheck disable=SC2154
 while IFS='' read -r file; do
-  if [[ "${FORMAT}" = "plain" ]]; then
-    Log::displayWarning "fileExistence - File ${file} does not exist, git renamed file ?"
-  else
+  if [[ "${FORMAT}" = "checkstyle" ]]; then
     echo "<file name='${file}'>"
-    echo "<error severity='warning' source='fileExistence' message='file does not exist, git renamed file ?'/>"
+  fi
+  reportWarning "fileExistence" "${file}" \
+    "File ${file} does not exist, git renamed file ?"
+  if [[ "${FORMAT}" = "checkstyle" ]]; then
     echo "</file>"
   fi
-  ((++warningCount))
 done < <(cat "${missingBashFileList}" 2>/dev/null || true)
 
 if [[ "${FORMAT}" = "checkstyle" ]]; then
diff --git a/bin/generateShellDoc b/bin/generateShellDoc
--- a/bin/generateShellDoc
+++ b/bin/generateShellDoc
@@ -380,6 +380,18 @@ Log::fatal() {
 
 # shellcheck disable=SC2317
 
+# @description activate or not Log::display* and Log::log* functions
+# based on BASH_FRAMEWORK_DISPLAY_LEVEL and BASH_FRAMEWORK_LOG_LEVEL
+# environment variables
+# try to create log file and rotate it if necessary
+# @noargs
+# @set BASH_FRAMEWORK_LOG_LEVEL int to OFF level if BASH_FRAMEWORK_LOG_FILE is empty or not writable
+# @env BASH_FRAMEWORK_DISPLAY_LEVEL int
+# @env BASH_FRAMEWORK_LOG_LEVEL int
+# @env BASH_FRAMEWORK_LOG_FILE String
+# @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
+# @exitcode 0 always successful
+# @stderr diagnostics information about log file is displayed
 Log::load() {
   # disable display methods following display level
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL < __LEVEL_DEBUG)); then
@@ -713,16 +725,19 @@ ShellDoc::generateShellDocDir() {
   )
 }
 
-# Internal: common log message
-#
-# @arg $1 levelMsg:String message's level description
-# @arg $2 msg:String the message to display
-# @output text
+# @description Internal: common log message
+# @example text
 #   [date]|[levelMsg]|message
 #
-# @example
+# @example text
 #   2020-01-19 19:20:21|ERROR  |log error
 #   2020-01-19 19:20:21|SKIPPED|log skipped
+#
+# @arg $1 levelMsg:String message's level description (eg: STATUS, ERROR, ...)
+# @arg $2 msg:String the message to display
+# @env BASH_FRAMEWORK_LOG_FILE String log file to use, do nothing if empty
+# @env BASH_FRAMEWORK_LOG_LEVEL int log level log only if > OFF or fatal messages
+# @stderr diagnostics information is displayed
 Log::logMessage() {
   local levelMsg="$1"
   local msg="$2"
@@ -762,6 +777,15 @@ ShellDoc::generateShellDoc() {
 BASH_FRAMEWORK_SHDOC_INSTALLED="${FRAMEWORK_ROOT_DIR}/vendor/.shDocInstalled"
 BASH_FRAMEWORK_SHDOC_CHECK_TIMEOUT=86400 # 1 day
 
+# @description install requirements to execute shdoc
+# @warning cloning is skipped if vendor/.shDocInstalled file exists
+# @warning a new check is done everyday
+# @warning repository is not updated if a change is detected
+# @env BASH_FRAMEWORK_SHDOC_CHECK_TIMEOUT int default value 86400 (86400 seconds = 1 day)
+# @set BASH_FRAMEWORK_SHDOC_INSTALLED String the file created when git clone succeeded
+# @see https://github.com/fchastanet/shdoc
+# @stderr diagnostics information is displayed
+# @feature Git::cloneOrPullIfNoChanges
 ShellDoc::installRequirementsIfNeeded() {
   if [[ "$(
     Cache::getFileContentIfNotExpired \
@@ -835,7 +859,7 @@ Git::cloneOrPullIfNoChanges() {
   fi
 }
 
-# @description Number of seconds since last modification of the file
+# @description get number of seconds since last modification of the file
 # @arg $1 file:String file path
 # @exitcode 1 if file does not exist
 # @stdout number of seconds since last modification of the file
@@ -850,24 +874,30 @@ File::elapsedTimeSinceLastModification() {
   echo -n "${diff}"
 }
 
-# pull the repository if no change in it
-# @exitcode 0 on successful pulling, 1 on failure or no pull needed
+# @description pull git directory only if no change has been detected
+# @arg $1 dir:String the git directory to pull
+# @exitcode 0 on successful pulling
+# @exitcode 1 on any other failure
+# @exitcode 2 changes detected, pull avoided
+# @exitcode 3 not a git directory
+# @exitcode 4 not able to update index
+# @stderr diagnostics information is displayed
+# @require Git::requireGitCommand
 Git::pullIfNoChanges() {
   local dir="$1"
-  if [[ -d "${dir}/.git" ]]; then
-    (
-      cd "${dir}"
-      git update-index --refresh &>/dev/null || true
-      if git diff-index --quiet HEAD --; then
-        Log::displayInfo "Pull git repository '${dir}' as no changes detected"
-        git pull --progress
-        return 0
-      else
-        Log::displayWarning "Pulling git repository '${dir}' avoided as changes detected"
-      fi
-    ) && return 0
+  if [[ ! -d "${dir}/.git" ]]; then
+    return 3
   fi
-  return 1
+  (
+    cd "${dir}" || exit 3
+    git update-index --refresh &>/dev/null || exit 4
+    if ! git diff-index --quiet HEAD --; then
+      Log::displayWarning "Pulling git repository '${dir}' avoided as changes detected"
+      exit 2
+    fi
+    Log::displayInfo "Pull git repository '${dir}' as no changes detected"
+    git pull --progress
+  )
 }
 
 # FUNCTIONS
