replaced jekyll by docsify

diff --git a/bin/doc b/bin/doc
--- a/bin/doc
+++ b/bin/doc
@@ -139,12 +139,61 @@ export __LEVEL_INFO
 export __LEVEL_SUCCESS
 export __LEVEL_DEBUG
 
-# Display message using error color (red) and exit immediately with error status 1
+# Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
-Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
-  Log::logFatal "$1"
-  exit 1
+Log::displayInfo() {
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
+  Log::logInfo "$1"
+}
+
+# generate markdown file from template by replacing
+# @@@command_help@@@ by the help of the command
+# eg: @@@test_help@@@ will be replaced by the output
+# of the command `test --help` in the directory provided
+# @param {String} $1 templateFile the file to use as template
+# @param {String} $2 targetFile the target file
+# @param {String} $3 fromDir the directory from which commands will be searched
+# @param {int} $4 tokenNotFoundCount passed by reference, will return
+#    the number of tokens @@@command_help@@@ not found in the template file
+# @param {String} excludeFilesPattern $5 grep exclude pattern
+#   eg: '^(bash-tpl)$'
+ShellDoc::generateMdFileFromTemplate() {
+  local templateFile="$1"
+  local targetFile="$2"
+  local fromDir="$3"
+  local -n tokenNotFoundCount=$4
+  local excludeFilesPattern="${5:-}"
+
+  local -a grepExclude
+  local startTime endTime
+
+  if [[ -z "${excludeFilesPattern}" ]]; then
+    grepExclude=(cat)
+  else
+    grepExclude=(grep -E -v "${excludeFilesPattern}")
+  fi
+
+  cp "${templateFile}" "${targetFile}"
+
+  startTime=$(date +%s.%3N)
+  ((nbTokensGenerated = 0)) || true
+  while IFS= read -r relativeFile; do
+    local token="${relativeFile#./}"
+    token="${token////_}"
+    if grep -q "@@@${token}_help@@@" "${targetFile}"; then
+      Log::displayInfo "generate help for ${token}"
+      ( #
+        (cd "${fromDir}" && "${relativeFile}" --help) |
+          File::replaceTokenByInput "@@@${token}_help@@@" "${targetFile}"
+      ) || Log::displayError "$(realpath "${fromDir}/${relativeFile}" --relative-to="${ROOT_DIR}") --help error caught"
+    else
+      ((++tokenNotFoundCount))
+      Log::displayWarning "token ${token} not found in ${targetFile}"
+    fi
+    ((nbTokensGenerated++)) || true
+  done < <(cd "${fromDir}" && find . -type f -executable | "${grepExclude[@]}")
+  endTime=$(date +%s.%3N)
+  Log::displayInfo "${nbTokensGenerated} commands' help replaced in $(echo "scale=3; ${endTime} - ${startTime}" | bc)seconds"
 }
 
 # generate doc + index
@@ -316,6 +365,23 @@ Env::load() {
   set +o allexport
 }
 
+File::replaceTokenByInput() {
+  local token="$1"
+  local targetFile="$2"
+
+  (
+    local tokenFile
+    tokenFile="$(Framework::createTempFile "replaceTokenByInput")"
+
+    cat - | Filters::escapeColorCodes >"${tokenFile}"
+
+    sed -E -i \
+      -e "/${token}/r ${tokenFile}" \
+      -e "/${token}/d" \
+      "${targetFile}"
+  )
+}
+
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
@@ -335,13 +401,6 @@ Log::displayError() {
 Log::displayHelp() {
   echo -e "${__HELP_COLOR}HELP    - ${1}${__RESET_COLOR}" >&2
   Log::logHelp "$1"
-}
-
-# Display message using info color (bg light blue/fg white)
-# @param {String} $1 message
-Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
-  Log::logInfo "$1"
 }
 
 # Display message using skip color (yellow)
@@ -375,12 +434,6 @@ Log::logDebug() {
 # @param {String} $1 message
 Log::logError() {
   Log::logMessage "ERROR" "$@"
-}
-
-# log message to file
-# @param {String} $1 message
-Log::logFatal() {
-  Log::logMessage "FATAL" "$@"
 }
 
 # log message to file
@@ -469,6 +522,19 @@ ShellDoc::generateShellDocFile() {
 Args::showHelp() {
   local helpArg="$1"
   echo -e "${helpArg}"
+}
+
+Filters::escapeColorCodes() {
+  cat - | sed -E $'s/\e\\[[0-9;:]*[a-zA-Z]//g'
+}
+
+# Public: create a temp file using default TMPDIR variable
+# initialized in src/_includes/_header.tpl
+#
+# **Arguments**:
+# @param $1 {String} template (optional)
+Framework::createTempFile() {
+  mktemp -p "${TMPDIR:-/tmp}" -t "$1.XXXXXXXXXXXX"
 }
 
 # Internal: common log message
@@ -599,6 +665,14 @@ Git::shallowClone() {
   )
 }
 
+# Display message using error color (red) and exit immediately with error status 1
+# @param {String} $1 message
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
+}
+
 # Number of seconds since last modification of the file
 # @param {String} file $1 file path
 # @return 1 if file does not exist
@@ -612,6 +686,12 @@ File::elapsedTimeSinceLastModification() {
   lastModificationTimeSeconds="$(stat -c %Y "${file}")"
   ((diff = $(date +%s) - lastModificationTimeSeconds))
   echo -n "${diff}"
+}
+
+# log message to file
+# @param {String} $1 message
+Log::logFatal() {
+  Log::logMessage "FATAL" "$@"
 }
 
 # FUNCTIONS
@@ -671,15 +751,11 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
   fi
 fi
 
-export FRAMEWORK_DIR="${ROOT_DIR}"
-
-if [[ "$(id -u)" = "0" ]]; then
-  Log::fatal "this script should be executed as normal user"
-fi
+DOC_DIR="${ROOT_DIR}/pages"
 
 HELP="$(
   cat <<EOF
-${__HELP_TITLE}Description:${__HELP_NORMAL} generate jekyll documentation
+${__HELP_TITLE}Description:${__HELP_NORMAL} generate markdown documentation
 ${__HELP_TITLE}Usage:${__HELP_NORMAL} ${SCRIPT_NAME}
 
 ${__HELP_TITLE}Author:${__HELP_NORMAL}
@@ -693,18 +769,67 @@ EOF
 )"
 Args::defaultHelp "${HELP}" "$@"
 
+if [[ "${IN_BASH_DOCKER:-}" != "You're in docker" ]]; then
+  "${BIN_DIR}/runBuildContainer" "/bash/bin/doc" "$@"
+  exit $?
+fi
+
+export FRAMEWORK_DIR="${ROOT_DIR}"
+
+#-----------------------------
+# doc generation
+#-----------------------------
+
+Log::displayInfo 'generate Commands.md'
+((TOKEN_NOT_FOUND_COUNT = 0)) || true
+ShellDoc::generateMdFileFromTemplate \
+  "${ROOT_DIR}/Commands.tmpl.md" \
+  "${DOC_DIR}/Commands.md" \
+  "${BIN_DIR}" \
+  TOKEN_NOT_FOUND_COUNT \
+  '(bash-tpl)$'
+
 # clean folder before generate
-rm -f "${ROOT_DIR}/jekyll/Index.md" || true
-rm -Rf "${ROOT_DIR}/jekyll/bashDoc" || true
+rm -f "${DOC_DIR}/Index.md" || true
+rm -Rf "${DOC_DIR}/bashDoc" || true
 
 ShellDoc::generateShellDocsFromDir \
   "${SRC_DIR}" \
-  "${ROOT_DIR}/jekyll/bashDoc" \
-  "${ROOT_DIR}/jekyll/Index.md" \
-  '(/_\.sh|/ZZZ\.sh|_includes/.*\.sh|/__all\.sh)$'
+  "${DOC_DIR}/bashDoc" \
+  "${DOC_DIR}/FrameworkIndex.md" \
+  '(/_\.sh|/ZZZ\.sh|_includes/.*\.sh|_binaries/.*\.sh|/__all\.sh)$'
 
-cp "${ROOT_DIR}/README.md" "${ROOT_DIR}/jekyll"
-cp "${ROOT_DIR}/Framework.tmpl.md" "${ROOT_DIR}/jekyll/Framework.md"
-# inject index file into Framework.md
-sed -E -i "/## Framework library full Index/ r ${ROOT_DIR}/jekyll/Index.md" "${ROOT_DIR}/jekyll/Framework.md"
-rm -f "${ROOT_DIR}/jekyll/Index.md"
+cp "${ROOT_DIR}/README.md" "${DOC_DIR}"
+cp "${ROOT_DIR}/BestPractices.md" "${DOC_DIR}"
+cp "${ROOT_DIR}/Framework.tmpl.md" "${DOC_DIR}/Framework.md"
+cp "${ROOT_DIR}/FrameworkFullDoc.tmpl.md" "${DOC_DIR}/FrameworkFullDoc.md"
+
+Log::displayInfo 'generate FrameworkFullDoc.md'
+(
+  cd "${ROOT_DIR}/pages/bashDoc" || exit 1
+  currentDir=""
+  echo ""
+  while IFS= read -r file; do
+    dir="$(dirname "${file}")"
+    if [[ "${currentDir}" != "${dir}" ]]; then
+      echo
+      echo "## ${dir#./}"
+      currentDir="${dir}"
+    fi
+    # shellcheck disable=SC2016
+    # print removing 2 first titles
+    sed -E \
+      -e 's/^(##?) [^#]+$//g' \
+      -e 's/^### Function (.+)$/### \1/g' \
+      "${file}"
+  done < <(
+    # find ensuring that files are ordered
+    find . -type f -printf '%h\0%d\0%p\n' |
+      sort -t '\0' -n |
+      awk -F '\0' '{print $3}'
+  )
+) >>"${DOC_DIR}/FrameworkFullDoc.md"
+
+if ((TOKEN_NOT_FOUND_COUNT > 0)); then
+  exit 1
+fi
