🔧(detectBashFile): fix concurrency issue + fix xargs logic
- File::detectBashFile was lazin creating a temp file that could be overridden simulateneously by multipe process leading to lose some matching files
- introduced  File::detectBashFileInit
- fix xargs logic on frameworkLint, shellcheckLint, findShebangFiles

diff --git a/bin/findShebangFiles b/bin/findShebangFiles
--- a/bin/findShebangFiles
+++ b/bin/findShebangFiles
@@ -419,17 +419,18 @@ export missingBashFileList
 
 # @description check if file provided is a bash file
 # @arg $@ files:String[]
-# @set missingBashFileList String temp filepath that contains eventual missing files
+# @prerequisite File::detectBashFileInit must have been called before to initialize the missingBashFileList variable
 # @stdout filepath if Assert::bashFile succeed
 # @see Assert::bashFile
 File::detectBashFile() {
   local -a files=("$@")
   local file
+  if [[ -z "${missingBashFileList}" ]]; then
+    Log::displayError "File::detectBashFile: missingBashFileList variable is not set, you should call File::detectBashFileInit before using File::detectBashFile"
+    return 1
+  fi
   for file in "${files[@]}"; do
     if [[ ! -f "${file}" ]]; then
-      if [[ -z "${missingBashFileList}" ]]; then
-        missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
-      fi
       echo "${file}" >>"${missingBashFileList}"
       continue
     fi
@@ -437,6 +438,22 @@ File::detectBashFile() {
       echo "${file}"
     fi
   done
+}
+
+
+# @description Initialize the missingBashFileList variable used by File::detectBashFile
+# @set missingBashFileList String temp filepath that contains eventual missing files
+# @noargs
+File::detectBashFileInit() {
+  local -a files=("$@")
+  local file
+  if [[ -n "${missingBashFileList}" ]]; then
+    rm -f "${missingBashFileList}" || true
+  fi
+  missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
+  export -f File::detectBashFile
+  export -f Assert::bashFile
+  export missingBashFileList
 }
 
 
@@ -1633,12 +1650,10 @@ findShebangFilesCommandParse "$@"
 MAIN_FUNCTION_NAME="main"
 main() {
 
-export -f File::detectBashFile
-export -f Assert::bashFile
-
+File::detectBashFileInit
 # shellcheck disable=SC2154
 git ls-files --exclude-standard -c -o -m |
-  xargs -r -L 1 -n 1 -I@ bash -c 'File::detectBashFile "@"' |
+  LC_ALL=C.UTF-8 xargs -r -P0 -n 10 bash -c 'File::detectBashFile "$@"' 'arg0' |
   xargs -r "${commandToApply[@]}"
 
 }
diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -464,17 +464,18 @@ export missingBashFileList
 
 # @description check if file provided is a bash file
 # @arg $@ files:String[]
-# @set missingBashFileList String temp filepath that contains eventual missing files
+# @prerequisite File::detectBashFileInit must have been called before to initialize the missingBashFileList variable
 # @stdout filepath if Assert::bashFile succeed
 # @see Assert::bashFile
 File::detectBashFile() {
   local -a files=("$@")
   local file
+  if [[ -z "${missingBashFileList}" ]]; then
+    Log::displayError "File::detectBashFile: missingBashFileList variable is not set, you should call File::detectBashFileInit before using File::detectBashFile"
+    return 1
+  fi
   for file in "${files[@]}"; do
     if [[ ! -f "${file}" ]]; then
-      if [[ -z "${missingBashFileList}" ]]; then
-        missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
-      fi
       echo "${file}" >>"${missingBashFileList}"
       continue
     fi
@@ -482,6 +483,22 @@ File::detectBashFile() {
       echo "${file}"
     fi
   done
+}
+
+
+# @description Initialize the missingBashFileList variable used by File::detectBashFile
+# @set missingBashFileList String temp filepath that contains eventual missing files
+# @noargs
+File::detectBashFileInit() {
+  local -a files=("$@")
+  local file
+  if [[ -n "${missingBashFileList}" ]]; then
+    rm -f "${missingBashFileList}" || true
+  fi
+  missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
+  export -f File::detectBashFile
+  export -f Assert::bashFile
+  export missingBashFileList
 }
 
 
@@ -2040,7 +2057,7 @@ checkEachSrcFileHasCorrectShdoc() {
   # @see https://regex101.com/r/5oMFQi/1
   # shellcheck disable=SC2120
   function filterInvalidAnnotationNames() {
-    grep -v -E '^(name|file|brief|description|section|example|option|arg|noargs|set|env|exitcode|stdin|stdout|stderr|see|warning|require|feature|trap|deprecated|internal|generated)$' "$@"
+    grep -v -E '^(name|file|brief|description|section|example|option|arg|noargs|set|env|exitcode|stdin|stdout|stderr|see|warning|require|feature|trap|deprecated|internal|generated|prerequisite)$' "$@"
   }
 
   function checkValidAnnotationsAreUsed() {
@@ -2121,9 +2138,9 @@ run() {
     echo "<?xml version='1.0' encoding='UTF-8'?>"
     echo "<checkstyle>"
   fi
-  export -f File::detectBashFile
-  export -f Assert::bashFile
   echo >"${CURRENT_WARNINGS_FILE}"
+
+  File::detectBashFileInit
 
   # shellcheck disable=SC2016
   while IFS='' read -r file; do
@@ -2141,7 +2158,7 @@ run() {
     fi
   done < <(
     git ls-files --exclude-standard |
-      xargs -n 10 bash -c 'File::detectBashFile "$@" || true' _ |
+      xargs -r -P0 -n 10 bash -c 'File::detectBashFile "$@" || true' arg0 |
       sort ||
       true
   )
diff --git a/bin/shellcheckLint b/bin/shellcheckLint
--- a/bin/shellcheckLint
+++ b/bin/shellcheckLint
@@ -442,17 +442,18 @@ export missingBashFileList
 
 # @description check if file provided is a bash file
 # @arg $@ files:String[]
-# @set missingBashFileList String temp filepath that contains eventual missing files
+# @prerequisite File::detectBashFileInit must have been called before to initialize the missingBashFileList variable
 # @stdout filepath if Assert::bashFile succeed
 # @see Assert::bashFile
 File::detectBashFile() {
   local -a files=("$@")
   local file
+  if [[ -z "${missingBashFileList}" ]]; then
+    Log::displayError "File::detectBashFile: missingBashFileList variable is not set, you should call File::detectBashFileInit before using File::detectBashFile"
+    return 1
+  fi
   for file in "${files[@]}"; do
     if [[ ! -f "${file}" ]]; then
-      if [[ -z "${missingBashFileList}" ]]; then
-        missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
-      fi
       echo "${file}" >>"${missingBashFileList}"
       continue
     fi
@@ -460,6 +461,22 @@ File::detectBashFile() {
       echo "${file}"
     fi
   done
+}
+
+
+# @description Initialize the missingBashFileList variable used by File::detectBashFile
+# @set missingBashFileList String temp filepath that contains eventual missing files
+# @noargs
+File::detectBashFileInit() {
+  local -a files=("$@")
+  local file
+  if [[ -n "${missingBashFileList}" ]]; then
+    rm -f "${missingBashFileList}" || true
+  fi
+  missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
+  export -f File::detectBashFile
+  export -f Assert::bashFile
+  export missingBashFileList
 }
 
 
@@ -2333,12 +2350,10 @@ getFiles() {
   if [[ -f "${PWD}/.shellcheckrc" ]]; then
     shellcheckrcFile="${PWD}/.shellcheckrc"
   fi
+  File::detectBashFileInit
+  # Use grep with LC_ALL to safely handle the exclude pattern
+  #exclude="$(grep -E '^exclude=' "${shellcheckrcFile}" 2>/dev/null | head -1 | cut -d= -f2- || true)"
   exclude="$(sed -n -E 's/^exclude=(.+)$/\1/p' "${shellcheckrcFile}" 2>/dev/null || true)"
-  if [[ -z "${exclude}" ]]; then
-    exclude='^$'
-  fi
-  export -f File::detectBashFile
-  export -f Assert::bashFile
 
   (
     if [[ "${optionStaged}" = "1" ]]; then
@@ -2357,8 +2372,8 @@ getFiles() {
       )
     fi
   ) |
-    (grep -E -v "${exclude}" || true) |
-    LC_ALL=C.UTF-8 xargs -r -n 10 bash -c 'File::detectBashFile "$@"' arg0
+    (if [[ -n "${exclude}" ]]; then grep -E -v "${exclude}"; else cat; fi) |
+    LC_ALL=C.UTF-8 xargs -r -P0 -n 10 bash -c 'File::detectBashFile "$@"' arg0
 }
 
 shellcheckFiles() {
@@ -2404,7 +2419,8 @@ shellcheckFiles() {
     # shellcheck disable=SC2154
     if [[ "${optionXargs}" = "1" ]]; then
       xargsArgs+=(
-        -P "$(nproc --ignore=1)"
+        -r
+        -P0
         -n 10
       )
     fi
