fix frameworkLint + clean coding (#121)
- frameworkLint
  - fixed bug skipping some files
  - File::detectBashFile replaced return by continue
  - excludes files with -options.sh or -main.sh suffix from being checked
  - warnings count 73 -> 62

- better error management and added logs
  - Github::defaultInstall
  - Github::defaultInstall

- clean coding
  - extracted Log::getLevelText
  - changed some log messages levels

diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -392,7 +392,7 @@ Conf::loadNearestFile() {
     fi
   done
 
-  Log::displayWarning "Config file '${configFileName}' not found in any source directories provided"
+  Log::displayDebug "Config file '${configFileName}' not found in any source directories provided"
   return 1
 }
 
@@ -477,7 +477,7 @@ File::detectBashFile() {
         missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-detectBashFile-before-XXXXXX)"
       fi
       echo "${file}" >>"${missingBashFileList}"
-      return 0
+      continue
     fi
     if Assert::bashFile "${file}"; then
       echo "${file}"
@@ -711,6 +711,35 @@ Log::fatal() {
   echo -e "${__ERROR_COLOR}FATAL   - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
+}
+
+
+# @description Get the text representation of a log level
+# @arg $1 level:String the log level to convert
+# @exitcode 1 if the level is invalid
+Log::getLevelText() {
+  local level="$1"
+  case "${level}" in
+    "${__LEVEL_OFF}")
+      echo OFF
+      ;;
+    "${__LEVEL_ERROR}")
+      echo ERROR
+      ;;
+    "${__LEVEL_WARNING}")
+      echo WARNING
+      ;;
+    "${__LEVEL_INFO}")
+      echo INFO
+      ;;
+    "${__LEVEL_DEBUG}")
+      echo DEBUG
+      ;;
+    *)
+      Log::displayError "Command ${SCRIPT_NAME} - Invalid level ${level}"
+      return 1
+      ;;
+  esac
 }
 
 
@@ -1105,31 +1134,6 @@ getLevel() {
   esac
 }
 
-getLevelText() {
-  local level="$1"
-  case "${level}" in
-    "${__LEVEL_OFF}")
-      echo OFF
-      ;;
-    "${__LEVEL_ERROR}")
-      echo ERROR
-      ;;
-    "${__LEVEL_WARNING}")
-      echo WARNING
-      ;;
-    "${__LEVEL_INFO}")
-      echo INFO
-      ;;
-    "${__LEVEL_DEBUG}")
-      echo DEBUG
-      ;;
-    *)
-      Log::displayError "Command ${SCRIPT_NAME} - Invalid level ${level}"
-      return 1
-      ;;
-  esac
-}
-
 getVerboseLevel() {
   local levelName="$1"
   case "${levelName^^}" in
@@ -1163,7 +1167,7 @@ optionDisplayLevelCallback() {
 }
 
 optionDisplayLevelDefaultValueFunction() {
-  getLevelText "${BASH_FRAMEWORK_DISPLAY_LEVEL:-${__LEVEL_INFO}}"
+  Log::getLevelText "${BASH_FRAMEWORK_DISPLAY_LEVEL:-${__LEVEL_INFO}}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1178,7 +1182,7 @@ optionLogLevelCallback() {
 }
 
 optionLogLevelDefaultValueFunction() {
-  getLevelText "${BASH_FRAMEWORK_LOG_LEVEL:-${__LEVEL_OFF}}"
+  Log::getLevelText "${BASH_FRAMEWORK_LOG_LEVEL:-${__LEVEL_OFF}}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1755,12 +1759,14 @@ frameworkLintCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}INFO${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionLogLevelDefaultValueFunction)"
   echo
 
   echo -e "  ${__HELP_OPTION_COLOR}--log-file <log-file>${__HELP_NORMAL} {single}"
   Array::wrap2 ' ' 76 4 "    " "Set log file"
   echo
+
 
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionLogFileDefaultValueFunction)"
   echo
@@ -1778,6 +1784,7 @@ frameworkLintCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}INFO${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionDisplayLevelDefaultValueFunction)"
   echo
 
@@ -1794,6 +1801,7 @@ frameworkLintCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}default${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}default-force${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}noColor${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "default"
   echo
 
@@ -1815,6 +1823,7 @@ frameworkLintCommandHelp() {
   echo "    Possible values: "
   echo -e "      - ${__OPTION_COLOR}plain${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}checkstyle${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "plain"
   echo
 
@@ -2127,7 +2136,8 @@ run() {
     fi
   done < <(
     git ls-files --exclude-standard |
-      xargs -n 10 bash -c 'File::detectBashFile "$@"' ||
+      xargs -n 10 bash -c 'File::detectBashFile "$@" || true' _ |
+      sort ||
       true
   )
 
diff --git a/bin/installRequirements b/bin/installRequirements
--- a/bin/installRequirements
+++ b/bin/installRequirements
@@ -429,7 +429,7 @@ Conf::loadNearestFile() {
     fi
   done
 
-  Log::displayWarning "Config file '${configFileName}' not found in any source directories provided"
+  Log::displayDebug "Config file '${configFileName}' not found in any source directories provided"
   return 1
 }
 
@@ -629,11 +629,21 @@ Github::defaultInstall() {
   if [[ "$(type -t "${installCallback}")" = "function" ]]; then
     ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
   else
-    ${SUDO:-} mv "${newSoftware}" "${targetFile}"
-    ${SUDO:-} chmod +x "${targetFile}"
+    ${SUDO:-} mv "${newSoftware}" "${targetFile}" || {
+      Log::displayError "Failed to move ${newSoftware} to ${targetFile}"
+      return 1
+    }
+    ${SUDO:-} chmod +x "${targetFile}" || {
+      Log::displayError "Failed to set execution bit on ${targetFile}"
+      return 1
+    }
     hash -r
     ${SUDO:-} rm -f "${newSoftware}" || true
-    Log::displaySuccess "Version ${version} installed in ${targetFile}"
+    if [[ -z "${CURRENT_VERSION}" ]]; then
+      Log::displaySuccess "Version ${version} installed in ${targetFile}"
+    else
+      Log::displaySuccess "Version ${CURRENT_VERSION} upgraded to ${version} in ${targetFile}"
+    fi
   fi
 }
 
@@ -661,6 +671,7 @@ Github::extractRepoFromGithubUrl() {
 Github::isReleaseVersionExist() {
   local releaseUrl="$1"
 
+  Log::displayDebug "Checking if release version exists on github: ${releaseUrl}"
   curl \
     -L \
     --connect-timeout "${CURL_CONNECT_TIMEOUT:-5}" \
@@ -862,6 +873,35 @@ Log::fatal() {
   echo -e "${__ERROR_COLOR}FATAL   - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
+}
+
+
+# @description Get the text representation of a log level
+# @arg $1 level:String the log level to convert
+# @exitcode 1 if the level is invalid
+Log::getLevelText() {
+  local level="$1"
+  case "${level}" in
+    "${__LEVEL_OFF}")
+      echo OFF
+      ;;
+    "${__LEVEL_ERROR}")
+      echo ERROR
+      ;;
+    "${__LEVEL_WARNING}")
+      echo WARNING
+      ;;
+    "${__LEVEL_INFO}")
+      echo INFO
+      ;;
+    "${__LEVEL_DEBUG}")
+      echo DEBUG
+      ;;
+    *)
+      Log::displayError "Command ${SCRIPT_NAME} - Invalid level ${level}"
+      return 1
+      ;;
+  esac
 }
 
 
@@ -1334,7 +1374,7 @@ Web::upgradeRelease() {
 
   local currentVersion="not existing"
   if [[ -f "${targetFile}" ]]; then
-    currentVersion="$(${softVersionCallback} "${targetFile}" "${softVersionArg}" 2>&1 || true)"
+    currentVersion="$(${softVersionCallback} "${targetFile}" "${softVersionArg}" || true)"
   fi
   if [[ -z "${exactVersion}" ]]; then
     local latestVersion
@@ -1370,7 +1410,7 @@ Web::upgradeRelease() {
       --fail \
       "${url}"
 
-    Github::defaultInstall "${newSoftware}" "${targetFile}" "${exactVersion}" "${installCallback}"
+    CURRENT_VERSION="${currentVersion}" Github::defaultInstall "${newSoftware}" "${targetFile}" "${exactVersion}" "${installCallback}"
   fi
 }
 # FUNCTIONS
@@ -1476,31 +1516,6 @@ getLevel() {
   esac
 }
 
-getLevelText() {
-  local level="$1"
-  case "${level}" in
-    "${__LEVEL_OFF}")
-      echo OFF
-      ;;
-    "${__LEVEL_ERROR}")
-      echo ERROR
-      ;;
-    "${__LEVEL_WARNING}")
-      echo WARNING
-      ;;
-    "${__LEVEL_INFO}")
-      echo INFO
-      ;;
-    "${__LEVEL_DEBUG}")
-      echo DEBUG
-      ;;
-    *)
-      Log::displayError "Command ${SCRIPT_NAME} - Invalid level ${level}"
-      return 1
-      ;;
-  esac
-}
-
 getVerboseLevel() {
   local levelName="$1"
   case "${levelName^^}" in
@@ -1534,7 +1549,7 @@ optionDisplayLevelCallback() {
 }
 
 optionDisplayLevelDefaultValueFunction() {
-  getLevelText "${BASH_FRAMEWORK_DISPLAY_LEVEL:-${__LEVEL_INFO}}"
+  Log::getLevelText "${BASH_FRAMEWORK_DISPLAY_LEVEL:-${__LEVEL_INFO}}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1549,7 +1564,7 @@ optionLogLevelCallback() {
 }
 
 optionLogLevelDefaultValueFunction() {
-  getLevelText "${BASH_FRAMEWORK_LOG_LEVEL:-${__LEVEL_OFF}}"
+  Log::getLevelText "${BASH_FRAMEWORK_LOG_LEVEL:-${__LEVEL_OFF}}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -2049,12 +2064,14 @@ installRequirementsCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}INFO${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionLogLevelDefaultValueFunction)"
   echo
 
   echo -e "  ${__HELP_OPTION_COLOR}--log-file <log-file>${__HELP_NORMAL} {single}"
   Array::wrap2 ' ' 76 4 "    " "Set log file"
   echo
+
 
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionLogFileDefaultValueFunction)"
   echo
@@ -2072,6 +2089,7 @@ installRequirementsCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}INFO${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "$(optionDisplayLevelDefaultValueFunction)"
   echo
 
@@ -2088,6 +2106,7 @@ installRequirementsCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}default${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}default-force${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}noColor${__RESET_COLOR}"
+
   Array::wrap2 ' ' 76 6 "    Default value: " "default"
   echo
 
