frameworkLint added --expected-warnings-count option

diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -1152,6 +1152,8 @@ frameworkLintCommand() {
   if [[ "${options_parse_cmd}" = "parse" ]]; then
     local -i options_parse_optionParsedCountOptionFormat
     ((options_parse_optionParsedCountOptionFormat = 0)) || true
+    local -i options_parse_optionParsedCountOptionExpectedWarningsCount
+    ((options_parse_optionParsedCountOptionExpectedWarningsCount = 0)) || true
     local -i options_parse_optionParsedCountOptionBashFrameworkConfig
     ((options_parse_optionParsedCountOptionBashFrameworkConfig = 0)) || true
     optionConfig="0"
@@ -1191,7 +1193,7 @@ frameworkLintCommand() {
       local options_parse_arg="$1"
       local argOptDefaultBehavior=0
       case "${options_parse_arg}" in
-        # Option 1/15
+        # Option 1/16
         # Option optionFormat --format variableType String min 0 max 1 authorizedValues 'plain|checkstyle' regexp ''
         --format)
           shift
@@ -1211,7 +1213,23 @@ frameworkLintCommand() {
           optionFormat="$1"
           updateArgListFormatCallback "${options_parse_arg}" "${optionFormat}"
           ;;
-        # Option 2/15
+        # Option 2/16
+        # Option optionExpectedWarningsCount --expected-warnings-count variableType String min 0 max 1 authorizedValues '' regexp ''
+        --expected-warnings-count)
+          shift
+          if (($# == 0)); then
+            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - a value needs to be specified"
+            return 1
+          fi
+          if ((options_parse_optionParsedCountOptionExpectedWarningsCount >= 1)); then
+            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - Maximum number of option occurrences reached(1)"
+            return 1
+          fi
+          ((++options_parse_optionParsedCountOptionExpectedWarningsCount))
+          optionExpectedWarningsCount="$1"
+          optionExpectedWarningsCountCallback "${options_parse_arg}" "${optionExpectedWarningsCount}"
+          ;;
+        # Option 3/16
         # Option optionBashFrameworkConfig --bash-framework-config variableType String min 0 max 1 authorizedValues '' regexp ''
         --bash-framework-config)
           shift
@@ -1227,7 +1245,7 @@ frameworkLintCommand() {
           optionBashFrameworkConfig="$1"
           optionBashFrameworkConfigCallback "${options_parse_arg}" "${optionBashFrameworkConfig}"
           ;;
-        # Option 3/15
+        # Option 4/16
         # Option optionConfig --config variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --config)
           optionConfig="1"
@@ -1237,7 +1255,7 @@ frameworkLintCommand() {
           fi
           ((++options_parse_optionParsedCountOptionConfig))
           ;;
-        # Option 4/15
+        # Option 5/16
         # Option optionInfoVerbose --verbose|-v variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --verbose | -v)
           optionInfoVerbose="1"
@@ -1249,7 +1267,7 @@ frameworkLintCommand() {
           optionInfoVerboseCallback "${options_parse_arg}"
           updateArgListInfoVerboseCallback "${options_parse_arg}"
           ;;
-        # Option 5/15
+        # Option 6/16
         # Option optionDebugVerbose -vv variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         -vv)
           optionDebugVerbose="1"
@@ -1261,7 +1279,7 @@ frameworkLintCommand() {
           optionDebugVerboseCallback "${options_parse_arg}"
           updateArgListDebugVerboseCallback "${options_parse_arg}"
           ;;
-        # Option 6/15
+        # Option 7/16
         # Option optionTraceVerbose -vvv variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         -vvv)
           optionTraceVerbose="1"
@@ -1273,7 +1291,7 @@ frameworkLintCommand() {
           optionTraceVerboseCallback "${options_parse_arg}"
           updateArgListTraceVerboseCallback "${options_parse_arg}"
           ;;
-        # Option 7/15
+        # Option 8/16
         # Option optionEnvFiles --env-file variableType StringArray min 0 max -1 authorizedValues '' regexp ''
         --env-file)
           shift
@@ -1286,7 +1304,7 @@ frameworkLintCommand() {
           optionEnvFileCallback "${options_parse_arg}" "${optionEnvFiles[@]}"
           updateArgListEnvFileCallback "${options_parse_arg}" "${optionEnvFiles[@]}"
           ;;
-        # Option 8/15
+        # Option 9/16
         # Option optionNoColor --no-color variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --no-color)
           optionNoColor="1"
@@ -1298,7 +1316,7 @@ frameworkLintCommand() {
           optionNoColorCallback "${options_parse_arg}"
           updateArgListNoColorCallback "${options_parse_arg}"
           ;;
-        # Option 9/15
+        # Option 10/16
         # Option optionTheme --theme variableType String min 0 max 1 authorizedValues 'default|default-always|noColor' regexp ''
         --theme)
           shift
@@ -1319,7 +1337,7 @@ frameworkLintCommand() {
           optionThemeCallback "${options_parse_arg}" "${optionTheme}"
           updateArgListThemeCallback "${options_parse_arg}" "${optionTheme}"
           ;;
-        # Option 10/15
+        # Option 11/16
         # Option optionHelp --help|-h variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --help | -h)
           optionHelp="1"
@@ -1330,7 +1348,7 @@ frameworkLintCommand() {
           ((++options_parse_optionParsedCountOptionHelp))
           optionHelpCallback "${options_parse_arg}"
           ;;
-        # Option 11/15
+        # Option 12/16
         # Option optionVersion --version variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --version)
           optionVersion="1"
@@ -1341,7 +1359,7 @@ frameworkLintCommand() {
           ((++options_parse_optionParsedCountOptionVersion))
           optionVersionCallback "${options_parse_arg}"
           ;;
-        # Option 12/15
+        # Option 13/16
         # Option optionQuiet --quiet|-q variableType Boolean min 0 max 1 authorizedValues '' regexp ''
         --quiet | -q)
           optionQuiet="1"
@@ -1353,7 +1371,7 @@ frameworkLintCommand() {
           optionQuietCallback "${options_parse_arg}"
           updateArgListQuietCallback "${options_parse_arg}"
           ;;
-        # Option 13/15
+        # Option 14/16
         # Option optionLogLevel --log-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
         --log-level)
           shift
@@ -1374,7 +1392,7 @@ frameworkLintCommand() {
           optionLogLevelCallback "${options_parse_arg}" "${optionLogLevel}"
           updateArgListLogLevelCallback "${options_parse_arg}" "${optionLogLevel}"
           ;;
-        # Option 14/15
+        # Option 15/16
         # Option optionLogFile --log-file variableType String min 0 max 1 authorizedValues '' regexp ''
         --log-file)
           shift
@@ -1391,7 +1409,7 @@ frameworkLintCommand() {
           optionLogFileCallback "${options_parse_arg}" "${optionLogFile}"
           updateArgListLogFileCallback "${options_parse_arg}" "${optionLogFile}"
           ;;
-        # Option 15/15
+        # Option 16/16
         # Option optionDisplayLevel --display-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
         --display-level)
           shift
@@ -1428,6 +1446,7 @@ frameworkLintCommand() {
       shift || true
     done
     export optionFormat
+    export optionExpectedWarningsCount
     export optionBashFrameworkConfig
     export optionConfig
     export optionInfoVerbose
@@ -1452,11 +1471,13 @@ frameworkLintCommand() {
     echo -e "$(Array::wrap " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" "${SCRIPT_NAME}" "[OPTIONS]")"
     echo -e "$(Array::wrap " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" \
       "${SCRIPT_NAME}" \
-      "[--format <String>]" "[--bash-framework-config <String>]" "[--config]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--env-file <String>]" "[--no-color]" "[--theme <String>]" "[--help|-h]" "[--version]" "[--quiet|-q]" "[--log-level <String>]" "[--log-file <String>]" "[--display-level <String>]")"
+      "[--format <String>]" "[--expected-warnings-count <String>]" "[--bash-framework-config <String>]" "[--config]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--env-file <String>]" "[--no-color]" "[--theme <String>]" "[--help|-h]" "[--version]" "[--quiet|-q]" "[--log-level <String>]" "[--log-file <String>]" "[--display-level <String>]")"
     echo
     echo -e "${__HELP_TITLE_COLOR}OPTIONS:${__RESET_COLOR}"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--format <String>${__HELP_NORMAL} (optional) (at most 1 times)"
     echo -e "    define output format of this command(available: ) (default: plain)"
+    printf "  %b\n" "${__HELP_OPTION_COLOR}--expected-warnings-count <String>${__HELP_NORMAL} (optional) (at most 1 times)"
+    echo -e "    Specify expected warning count (default: 0)"
     echo
     echo -e "${__HELP_TITLE_COLOR}GLOBAL OPTIONS:${__RESET_COLOR}"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--bash-framework-config <String>${__HELP_NORMAL} (optional) (at most 1 times)"
@@ -1515,6 +1536,14 @@ Lint files of the current repository
   else
     Log::displayError "Command ${SCRIPT_NAME} - Option command invalid: '${options_parse_cmd}'"
     return 1
+  fi
+}
+
+declare -i optionExpectedWarningsCount=0
+
+optionExpectedWarningsCountCallback() {
+  if [[ ! "$2" =~ ^[0-9]+$ ]] || (( $2 < 0 )); then
+    Log::fatal "Command ${SCRIPT_NAME} - Expected warnings count value should be a number greater or equal to 0"
   fi
 }
 
@@ -1774,9 +1803,6 @@ run() {
     fi
   done < <(cat "${missingBashFileList}" 2>/dev/null || true)
 
-  if [[ "${optionFormat}" = "checkstyle" ]]; then
-    echo "</checkstyle>"
-  fi
   if [[ "${optionFormat}" = "plain" ]]; then
     if ((errorCount > 0)); then
       Log::displayError "${errorCount} errors/${warningCount} warnings found !"
@@ -1787,9 +1813,32 @@ run() {
     fi
   fi
 
-  if ((errorCount > 0)); then
-    exit 1
+  ((exitCode = 0)) || true
+  # shellcheck disable=SC2154
+  if ((warningCount > optionExpectedWarningsCount)); then
+    local errorMsg="Warnings count(${warningCount}) is greater than expected warnings count(${optionExpectedWarningsCount})"
+    if [[ "${optionFormat}" = "plain" ]]; then
+      Log::displayError "${errorMsg} !"
+    else
+      echo "<error severity='error' source='warningsCount' message='${errorMsg}'/>"
+    fi
+    ((exitCode = 2))
+  elif ((warningCount < optionExpectedWarningsCount)); then
+    local errorMsg="you can set expected warnings count to ${warningCount} to match the current warnings count"
+    if [[ "${optionFormat}" = "plain" ]]; then
+      Log::displayWarning "${errorMsg}"
+    else
+      echo "<error severity='warning' source='warningsCount' message='${errorMsg}'/>"
+    fi
   fi
+  if ((errorCount > 0)); then
+    ((exitCode = 1))
+  fi
+  if [[ "${optionFormat}" = "checkstyle" ]]; then
+    echo "</checkstyle>"
+  fi
+
+  return "${exitCode}"
 }
 
 if [[ "${BASH_FRAMEWORK_QUIET_MODE:-0}" = "1" ]]; then
