FrameworkLint checks about missing bats files
* Fixed issue that was filtering out all bash files
* added  Assert::bashFile
* fixed File::detectBashFile
* added lint framework that check for bats file
  presence for each framework file

diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -41,6 +41,16 @@ Array::contains() {
   return 1
 }
 
+Assert::bashFile() {
+  local file="$1"
+  local head=""
+  if [[ ! -f "${file}" ]]; then
+    return 2
+  fi
+  head="$(head -n 1 "${file}")"
+  [[ "${head}" =~ ^#\!.*bash ]]
+}
+
 Env::pathPrepend() {
   local arg
   for arg in "$@"; do
@@ -54,21 +64,23 @@ Env::pathPrepend() {
 # File::detectBashFile is used in conjunction with git ls-files
 # typical case for missing file is when a file is marked as deleted but not staged
 declare missingBashFileList
-missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-buildBinFiles-before-XXXXXX)"
+missingBashFileList=""
 export missingBashFileList
 
 File::detectBashFile() {
   local file="$1"
-  local head=""
-  if [[ ! -f "${file}" ]]; then
-    echo "${file}" >>"${missingBashFileList}"
-    return 1
-  fi
-  head="$(head -n 1 "${file}")"
-  [[ "${head}" =~ ^#!.*bash ]]
-}
 
-export -f File::detectBashFile
+  if [[ ! -f "${file}" ]]; then
+    if [[ -z "${missingBashFileList}" ]]; then
+      missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-buildBinFiles-before-XXXXXX)"
+    fi
+    echo "${file}" >>"${missingBashFileList}"
+    return 0
+  fi
+  if Assert::bashFile "${file}"; then
+    echo "${file}"
+  fi
+}
 
 # shellcheck disable=SC2120
 Filters::bashCommentLines() {
@@ -586,6 +598,7 @@ ${__HELP_TITLE}Description:${__HELP_NORMAL}
 Lint files of the current repository
 - check if all namespace::functions are existing in the framework
 - check that function defined in a .sh is correctly named
+- check each function has a bats file associated
 
 ${__HELP_TITLE}Options:${__HELP_NORMAL}
   -f|--format <checkstyle,plain>  define output format of this command
@@ -692,6 +705,19 @@ checkEachFunctionHasSrcFile() {
   done
 }
 
+checkEachSrcFileHasBatsFile() {
+  local file="$1"
+  local batsFile="${file%.*}.bats"
+  if [[ -f "${ROOT_DIR}/${batsFile}" ]]; then
+    if [[ "${FORMAT}" = "plain" ]]; then
+      Log::displayWarning "File '${file}', missing bats file '${batsFile}'"
+    else
+      echo "<error severity='warning' message='missing bats file '${batsFile}'/>"
+    fi
+    ((++warningCount))
+  fi
+}
+
 # search for at least one function that is matching the filename
 checkEachSrcFileHasOneFunctionCorrectlyNamed() {
   local srcFile="$1"
@@ -730,6 +756,8 @@ if [[ "${FORMAT}" = "checkstyle" ]]; then
   echo "<?xml version='1.0' encoding='UTF-8'?>"
   echo "<checkstyle>"
 fi
+export -f File::detectBashFile
+export -f Assert::bashFile
 
 # shellcheck disable=SC2016
 while IFS='' read -r file; do
@@ -739,6 +767,7 @@ while IFS='' read -r file; do
 
   checkEachFunctionHasSrcFile "${file}" "$@" || ((++errorCount))
   checkEachSrcFileHasOneFunctionCorrectlyNamed "${file}" "$@" || ((++errorCount))
+  checkEachSrcFileHasBatsFile "${file}" "$@" || ((++errorCount))
 
   if [[ "${FORMAT}" = "checkstyle" ]]; then
     echo "</file>"
