compile using Framework::loadConfig

diff --git a/bin/frameworkLint b/bin/frameworkLint
--- a/bin/frameworkLint
+++ b/bin/frameworkLint
@@ -152,7 +152,14 @@ File::detectBashFile() {
 export -f File::detectBashFile
 
 Filters::bashFrameworkFunctions() {
-  grep -Eoi '([a-z0-9_]+[a-z0-9_-]*::)+([a-z0-9_-]+)' "$@"
+  grep -Eo "${PREFIX:-}([A-Za-z0-9_]+[A-Za-z0-9_-]*::)+([a-zA-Z0-9_-]+)" "$@"
+}
+
+# @param {string[]} $@ the src directories in which .framework-config file will be searched
+# @output the config file path loaded if any
+# @return 0 if .framework-config file has beend found in srcDirs provided
+Framework::loadConfig() {
+  Conf::loadNearestFile ".framework-config" "$@"
 }
 
 # Public: log level off
@@ -209,6 +216,36 @@ Log::fatal() {
   echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
+}
+
+# Load the nearest config file
+# eg: Conf::loadNearestFile ".framework-config" "srcDir1" "srcDir2"
+# will search first .framework-config file in "srcDir1"
+# then if not found will go in up directories until /
+# then will search in "srcDir2"
+# then if not found will go in up directories until /
+# source the file if found
+# @param {String} $1 config file name to search
+# @param {String} $@ source directories in which the config file will be searched
+# @return 0 if file found, 1 if file not found
+# @output the filepath loaded if any
+Conf::loadNearestFile() {
+  local configFileName="$1"
+  shift || true
+  local -a srcDirs=("$@")
+  for srcDir in "${srcDirs[@]}"; do
+    configFile="$(File::upFind "${srcDir}" "${configFileName}" || true)"
+    if [[ -n "${configFile}" ]]; then
+      # shellcheck source=/.framework-config
+      source "${configFile}" || Log::fatal "error while loading config file '${configFile}'"
+      Log::displayDebug "Config file ${configFile} is loaded"
+      echo "${configFile}"
+      return 0
+    fi
+  done
+
+  Log::displayWarning "Config file '${configFileName}' not found in any source directories provided"
+  return 1
 }
 
 # lazy initialization
@@ -391,6 +428,38 @@ Log::rotate() {
   fi
 }
 
+# Public: search a file in parent directories
+#
+# **Arguments**:
+# * $1 path
+# * $2 fileName
+# * $@ list of untilInclusivePath
+# **Output**: The filename if found
+# **Exit**: code 1 if the command failed
+File::upFind() {
+  local fromPath="$1"
+  shift || true
+  local fileName="$1"
+  shift || true
+  local untilInclusivePath="${1:-/}"
+  shift || true
+
+  if [[ -f "${fromPath}" ]]; then
+    fromPath="$(dirname "${fromPath}")"
+  fi
+  while true; do
+    if [[ -f "${fromPath}/${fileName}" ]]; then
+      echo "${fromPath}/${fileName}"
+      return 0
+    fi
+    if Array::contains "${fromPath}" "${untilInclusivePath}" "$@" "/"; then
+      return 1
+    fi
+    fromPath="$(readlink -f "${fromPath}"/..)"
+  done
+  return 1
+}
+
 # Internal: common log message
 #
 # **Arguments**:
@@ -509,10 +578,9 @@ FRAMEWORK_FUNCTIONS_IGNORE_REGEXP=^$
 NON_FRAMEWORK_FILES_REGEXP=^$
 FRAMEWORK_FILES_FUNCTION_MATCHING_IGNORE_REGEXP=^$
 FRAMEWORK_SRC_DIRS=()
-if [[ -f "${CONFIG_FILENAME}" ]]; then
-  # shellcheck source=/.framework-config
-  source "${CONFIG_FILENAME}" || Log::fatal "error while loading config file '${CONFIG_FILENAME}'"
-fi
+
+# load .framework-config
+Framework::loadConfig "${ROOT_DIR}" >/dev/null || Log::fatal "error while loading config file"
 
 if (($# == 0)); then
   set -- "${DEFAULT_ARGS[@]}"
