Theme option with default-always to colorize output even if piped command

diff --git a/bin/installFacadeExample b/bin/installFacadeExample
--- a/bin/installFacadeExample
+++ b/bin/installFacadeExample
@@ -476,9 +476,18 @@ Log::logSkipped() {
 # @set __HELP_NORMAL String to remove
 UI::theme() {
   local theme="${1-default}"
-  if ! Assert::tty; then
+  if [[ ! "${theme}" =~ -always$ ]] && ! Assert::tty; then
     theme="noColor"
   fi
+  case "${theme}" in
+  default | default-always)
+    theme="default"
+    ;;
+  noColor)
+    ;;
+  *)
+    Log::fatal "invalid theme provided"
+  esac
   if [[ "${theme}" = "default" ]]; then
     export BASH_FRAMEWORK_THEME="default"
     # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
@@ -529,6 +538,20 @@ UI::theme() {
 # @stderr diagnostic information + help if second argument is provided
 Assert::tty() {
   [[ -t 1 || -t 2 ]]
+}
+
+# @description Display message using error color (red) and exit immediately with error status 1
+# @arg $1 message:String the message to display
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
+}
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logFatal() {
+  Log::logMessage "${2:-FATAL}" "$1"
 }
 
 # FUNCTIONS
