Command enhancement
Facade calls function on invalid action
command's short/long description overridable by callback function

tag: 2.3.2

# Breaking changes

# Bug fixes

- Ability to use a function to override command short/long description

# Compiler changes

N/A

# Binaries changes

- Facade call defaultFacadeAction (if exists) if invalid action requested

# Updated Bash framework functions

N/A

# New Bash framework functions

N/A

# Documentation

N/A

# Validation/Tooling

- upgraded megalinter to version 3.10.0
- pre-commit go back from prettier v4.0.0-alpha.8 to v4.0.0-alpha.4
  because of the error "No files matching the given patterns were found"

diff --git a/bin/installFacadeExample b/bin/installFacadeExample
--- a/bin/installFacadeExample
+++ b/bin/installFacadeExample
@@ -100,6 +100,13 @@ cleanOnExit() {
 }
 trap cleanOnExit EXIT HUP QUIT ABRT TERM
 
+# @description checks if function name provided exists
+# @arg $1 functionName:String
+# @exitcode 1 if function name doesn't exist
+Assert::functionExists() {
+  declare -F "$1" >/dev/null
+}
+
 # @description Log namespace provides 2 kind of functions
 # - Log::display* allows to display given message with
 #   given display level
@@ -490,8 +497,12 @@ case ${action} in
     install "$@"
     ;;
   *)
-    Log::displayError "invalid action requested: ${action}"
-    exit 1
+    if Assert::functionExists defaultFacadeAction; then
+      defaultFacadeAction "$1" "$@"
+    else
+      Log::displayError "invalid action requested: ${action}"
+      exit 1
+    fi
     ;;
 esac
 exit 0
