shellcheck using Options shellcheck added option --xargs args/option help wrapped

diff --git a/bin/megalinter b/bin/megalinter
--- a/bin/megalinter
+++ b/bin/megalinter
@@ -1527,47 +1527,50 @@ megalinterCommand() {
     echo
     echo -e "${__HELP_TITLE_COLOR}OPTIONS:${__RESET_COLOR}"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--format <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    define output format of this command(available: plain|json) (default: plain)"
+    echo -e "    define output format of this command(available: plain|json) (default: plain
+    )"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--fix${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Apply linters fixes automatically."
+    echo -e "    Apply linters fixes automatically."
     printf "  %b\n" "${__HELP_OPTION_COLOR}--filesOnly${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Skip linters that run in project mode."
+    echo -e "    Skip linters that run in project mode."
     printf "  %b\n" "${__HELP_OPTION_COLOR}--incremental${__HELP_NORMAL}, ${__HELP_OPTION_COLOR}-i${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Run megalinter only on files that are git staged"
+    echo -e "    Run megalinter only on files that are git staged"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--image <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Specify docker megalinter image name to use (default: oxsecurity/megalinter-terraform:v7.3.0)"
+    echo -e "    Specify docker megalinter image name to use (default: oxsecurity/megalinter
+    -terraform:v7.3.0)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--check-megalinter-version${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Check if new version of megalinter is available (compared to oxsecurity/megalinter-terraform:v7.3.0) and exit 1 if yes and display new version number."
+    echo -e "    Check if new version of megalinter is available (compared to oxsecurity/meg
+    alinter-terraform:v7.3.0) and exit 1 if yes and display new version number."
     echo
     echo -e "${__HELP_TITLE_COLOR}GLOBAL OPTIONS:${__RESET_COLOR}"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--bash-framework-config <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    use alternate bash framework configuration."
+    echo -e "    use alternate bash framework configuration."
     printf "  %b\n" "${__HELP_OPTION_COLOR}--config${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Display configuration"
+    echo -e "    Display configuration"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--verbose${__HELP_NORMAL}, ${__HELP_OPTION_COLOR}-v${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    info level verbose mode (alias of --display-level INFO)"
+    echo -e "    info level verbose mode (alias of --display-level INFO)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}-vv${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    debug level verbose mode (alias of --display-level DEBUG)"
+    echo -e "    debug level verbose mode (alias of --display-level DEBUG)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}-vvv${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    trace level verbose mode (alias of --display-level TRACE)"
+    echo -e "    trace level verbose mode (alias of --display-level TRACE)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--env-file <String>${__HELP_NORMAL} (optional)"
-    echo "    Load the specified env file"
+    echo -e "    Load the specified env file"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--no-color${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Produce monochrome output. alias of --theme noColor."
+    echo -e "    Produce monochrome output. alias of --theme noColor."
     printf "  %b\n" "${__HELP_OPTION_COLOR}--theme <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    choose color theme (default or noColor)"
+    echo -e "    choose color theme (default or noColor)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--help${__HELP_NORMAL}, ${__HELP_OPTION_COLOR}-h${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Display this command help"
+    echo -e "    Display this command help"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--version${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Print version information and quit"
+    echo -e "    Print version information and quit"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--quiet${__HELP_NORMAL}, ${__HELP_OPTION_COLOR}-q${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    quiet mode, doesn't display any output"
+    echo -e "    quiet mode, doesn't display any output"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--log-level <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Set log level (one of OFF, ERROR, WARNING, INFO, DEBUG, TRACE value)"
+    echo -e "    Set log level (one of OFF, ERROR, WARNING, INFO, DEBUG, TRACE value)"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--log-file <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    Set log file"
+    echo -e "    Set log file"
     printf "  %b\n" "${__HELP_OPTION_COLOR}--display-level <String>${__HELP_NORMAL} (optional) (at most 1 times)"
-    echo "    set display level (one of OFF, ERROR, WARNING, INFO, DEBUG, TRACE value)"
+    echo -e "    set display level (one of OFF, ERROR, WARNING, INFO, DEBUG, TRACE value)"
     echo -e """
 megalinter image oxsecurity/megalinter-terraform:v7.3.0 will be used.
 
