✨(plantuml): Update include path handling for PlantUML
Enhance the include path option in PlantUML to default to the current directory if not specified. This improves usability when working with include directives.

## 1. ✨ Include Path Option Update

- Modify `includePathOptionCallback` to set the current directory as the default include path when no path is provided.
- Update documentation to clarify that the current directory will be used if the include path is not specified.

## 2. 🔧 Documentation Improvements

- Add a note in the help message for the include path option to inform users about the default behavior.

diff --git a/bin/plantuml b/bin/plantuml
--- a/bin/plantuml
+++ b/bin/plantuml
@@ -1094,9 +1094,25 @@ optionLimitSizeCallback() {
   fi
 }
 
+includePathOptionCallback() {
+  if [[ -z "${includePathOption}" ]]; then
+    includePathOption="-"
+  fi
+  if [[ "${includePathOption}" != "-" ]]; then
+    if [[ ! -d "${includePathOption}" ]]; then
+      Log::displayError "Command ${SCRIPT_NAME} - invalid include path '${includePathOption}'"
+      return 1
+    fi
+    includePathOption="$(realpath "${includePathOption}")"
+  fi
+}
+
 plantumlCallback() {
   if ((${#optionFormats[@]} == 0)); then
     optionFormats=("${defaultFormatsIfNoneProvided[@]}")
+  fi
+  if [[ "${includePathOption}" = "-" ]]; then
+    includePathOption="$(pwd)"
   fi
   # shellcheck disable=SC2154
   if [[ -n "${optionOutputDir}" && "${sameDirectoryOption}" = "1" ]]; then
@@ -1162,9 +1178,10 @@ declare optionVersion="0"
 declare optionQuiet="0"
 declare optionContinuousIntegrationMode="0"
 declare -a optionFormats=()
-declare optionLimitSize=""
+declare optionLimitSize="0"
 declare sameDirectoryOption="0"
 declare optionOutputDir=""
+declare includePathOption="-"
 # arguments variables initialization
 declare -a argPlantumlFiles=()
 # @description parse command options and arguments for plantumlCommand
@@ -1214,7 +1231,7 @@ plantumlCommandParse() {
   local -i options_parse_optionParsedCountOptionContinuousIntegrationMode
   ((options_parse_optionParsedCountOptionContinuousIntegrationMode = 0)) || true
 
-  optionLimitSize=""
+  optionLimitSize="0"
   local -i options_parse_optionParsedCountOptionLimitSize
   ((options_parse_optionParsedCountOptionLimitSize = 0)) || true
   sameDirectoryOption="0"
@@ -1223,6 +1240,9 @@ plantumlCommandParse() {
   optionOutputDir=""
   local -i options_parse_optionParsedCountOptionOutputDir
   ((options_parse_optionParsedCountOptionOutputDir = 0)) || true
+  includePathOption="-"
+  local -i options_parse_optionParsedCountIncludePathOption
+  ((options_parse_optionParsedCountIncludePathOption = 0)) || true
 
   argPlantumlFiles=()
 
@@ -1233,7 +1253,7 @@ plantumlCommandParse() {
     local options_parse_arg="$1"
     local argOptDefaultBehavior=0
     case "${options_parse_arg}" in
-      # Option 1/18
+      # Option 1/19
       # optionHelp alts --help|-h
       # type: Boolean min 0 max 1
       --help | -h)
@@ -1249,7 +1269,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 2/18
+      # Option 2/19
       # optionConfig alts --config
       # type: Boolean min 0 max 1
       --config)
@@ -1263,7 +1283,7 @@ plantumlCommandParse() {
         ((++options_parse_optionParsedCountOptionConfig))
         ;;
 
-      # Option 3/18
+      # Option 3/19
       # optionBashFrameworkConfig alts --bash-framework-config
       # type: String min 0 max 1
       --bash-framework-config)
@@ -1284,7 +1304,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 4/18
+      # Option 4/19
       # optionInfoVerbose alts --verbose|-v
       # type: Boolean min 0 max 1
       --verbose | -v)
@@ -1302,7 +1322,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 5/18
+      # Option 5/19
       # optionDebugVerbose alts -vv
       # type: Boolean min 0 max 1
       -vv)
@@ -1320,7 +1340,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 6/18
+      # Option 6/19
       # optionTraceVerbose alts -vvv
       # type: Boolean min 0 max 1
       -vvv)
@@ -1338,7 +1358,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 7/18
+      # Option 7/19
       # optionLogLevel alts --log-level
       # type: String min 0 max 1
       # authorizedValues: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE
@@ -1366,7 +1386,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 8/18
+      # Option 8/19
       # optionLogFile alts --log-file
       # type: String min 0 max 1
       --log-file)
@@ -1389,7 +1409,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 9/18
+      # Option 9/19
       # optionDisplayLevel alts --display-level
       # type: String min 0 max 1
       # authorizedValues: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE
@@ -1417,7 +1437,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 10/18
+      # Option 10/19
       # optionNoColor alts --no-color
       # type: Boolean min 0 max 1
       --no-color)
@@ -1435,7 +1455,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 11/18
+      # Option 11/19
       # optionTheme alts --theme
       # type: String min 0 max 1
       # authorizedValues: default|default-force|noColor
@@ -1463,7 +1483,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 12/18
+      # Option 12/19
       # optionVersion alts --version
       # type: Boolean min 0 max 1
       --version)
@@ -1479,7 +1499,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 13/18
+      # Option 13/19
       # optionQuiet alts --quiet|-q
       # type: Boolean min 0 max 1
       --quiet | -q)
@@ -1497,7 +1517,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 14/18
+      # Option 14/19
       # optionContinuousIntegrationMode alts --ci
       # type: Boolean min 0 max 1
       --ci)
@@ -1513,7 +1533,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 15/18
+      # Option 15/19
       # optionFormats alts --format|-f
       # type: StringArray min 0 max -1
       # authorizedValues: svg|png
@@ -1532,7 +1552,7 @@ plantumlCommandParse() {
         optionFormats+=("$1")
         ;;
 
-      # Option 16/18
+      # Option 16/19
       # optionLimitSize alts --limit-size|-l
       # type: String min 0 max 1
       --limit-size | -l)
@@ -1553,7 +1573,7 @@ plantumlCommandParse() {
 
         ;;
 
-      # Option 17/18
+      # Option 17/19
       # sameDirectoryOption alts --same-dir
       # type: Boolean min 0 max 1
       --same-dir)
@@ -1567,7 +1587,7 @@ plantumlCommandParse() {
         ((++options_parse_optionParsedCountSameDirectoryOption))
         ;;
 
-      # Option 18/18
+      # Option 18/19
       # optionOutputDir alts --output-dir|-o
       # type: String min 0 max 1
       --output-dir | -o)
@@ -1585,6 +1605,27 @@ plantumlCommandParse() {
         # shellcheck disable=SC2034
         optionOutputDir="$1"
         plantUmlOutputDirCallback "${options_parse_arg}" "${optionOutputDir}"
+
+        ;;
+
+      # Option 19/19
+      # includePathOption alts --include-path
+      # type: String min 0 max 1
+      --include-path)
+        shift
+        if (($# == 0)); then
+          Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - a value needs to be specified"
+          return 1
+        fi
+
+        if ((options_parse_optionParsedCountIncludePathOption >= 1 )); then
+          Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - Maximum number of option occurrences reached(1)"
+          return 1
+        fi
+        ((++options_parse_optionParsedCountIncludePathOption))
+        # shellcheck disable=SC2034
+        includePathOption="$1"
+        includePathOptionCallback "${options_parse_arg}" "${includePathOption}"
 
         ;;
 
@@ -1649,7 +1690,7 @@ plantumlCommandHelp() {
   # ------------------------------------------
   # usage/options section
   # ------------------------------------------
-  optionsAltList=("[--help|-h]" "[--config]" "[--bash-framework-config <bash-framework-config>]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--log-level <log-level>]" "[--log-file <log-file>]" "[--display-level <display-level>]" "[--no-color]" "[--theme <theme>]" "[--version]" "[--quiet|-q]" "[--ci]" "[--format|-f <Format>]" "[--limit-size|-l <LimitSize>]" "[--same-dir]" "[--output-dir|-o <OutputDir>]"
+  optionsAltList=("[--help|-h]" "[--config]" "[--bash-framework-config <bash-framework-config>]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--log-level <log-level>]" "[--log-file <log-file>]" "[--display-level <display-level>]" "[--no-color]" "[--theme <theme>]" "[--version]" "[--quiet|-q]" "[--ci]" "[--format|-f <Format>]" "[--limit-size|-l <LimitSize>]" "[--same-dir]" "[--output-dir|-o <OutputDir>]" "[--include-path <IncludePath>]"
   )
   Array::wrap2 " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" \
     "plantuml" "${optionsAltList[@]}"
@@ -1789,6 +1830,9 @@ plantumlCommandHelp() {
   echo
 
 
+  Array::wrap2 ' ' 76 6 "    Default value: " "0"
+  echo
+
   echo -e "  ${__HELP_OPTION_COLOR}--same-dir${__HELP_NORMAL} {single}"
   Array::wrap2 ' ' 76 4 "    " "Write image file in same directory as source file" "and with the same base name (except extension)" "Incompatible with the option --output-dir" ""
   echo
@@ -1798,6 +1842,14 @@ plantumlCommandHelp() {
   Array::wrap2 ' ' 76 4 "    " "Define output directory of this command (default: <currentDirectory>)" "Incompatible with the option --same-dir" ""
   echo
 
+
+  echo -e "  ${__HELP_OPTION_COLOR}--include-path <IncludePath>${__HELP_NORMAL} {single}"
+  Array::wrap2 ' ' 76 4 "    " "Make the path specified shared inside docker container" "so that !include directives in plantuml files can work" "relative to this path." "" "If not provided, the current directory will be used as" "include path." ""
+  echo
+
+
+  Array::wrap2 ' ' 76 6 "    Default value: " "-"
+  echo
   # ------------------------------------------
   # longDescription section
   # ------------------------------------------
@@ -1876,7 +1928,8 @@ convertPuml() {
   local format="$4"
   local optionLimitSize="$5"
   local optionTraceVerbose="$6"
-  shift 6 || true
+  local includePathOption="$7"
+  shift 7 || true
   local -a plantumlOptions=("$@")
 
   local targetFile
@@ -1888,14 +1941,21 @@ convertPuml() {
   fi
   Log::displayInfo "Generating ${targetFile} from ${file}"
   local -a env=()
-  if [[ -n "${optionLimitSize}" ]]; then
+  if [[ "${optionLimitSize}" != "0" ]]; then
     env+=(-e "PLANTUML_LIMIT_SIZE=${optionLimitSize}")
   fi
   # shellcheck disable=SC2154
   if [[ "${optionTraceVerbose}" = "1" ]]; then
     set -x
   fi
-  docker run -i --rm "${env[@]}" plantuml/plantuml \
+  if [[ "${includePathOption}" != "-" ]]; then
+    env+=(
+      -v "${includePathOption}:/data/src:ro"
+    )
+    javaArgs+=("-Dplantuml.include.path=/data/src")
+  fi
+  docker run -i --rm "${env[@]}" --entrypoint java plantuml/plantuml \
+    "${javaArgs[@]}" -jar /opt/plantuml.jar \
     -t"${format}" --disable-metadata -v -pipe -failfast2 -nbthread auto "${plantumlOptions[@]}" \
     >"${targetFile}" \
     <"${file}"
@@ -1919,12 +1979,13 @@ export BASH_FRAMEWORK_DISPLAY_LEVEL __LEVEL_INFO __INFO_COLOR __RESET_COLOR
       declare -a myArgs=(
         "${file}" "${sameDirectoryOption}" "${optionOutputDir}"
         "${format}" "${optionLimitSize}" "${optionTraceVerbose}"
+        "${includePathOption}"
         "${plantumlOptions[@]}"
       )
       printf "%s\0" "${myArgs[@]}"
     done
   done
-) | xargs -0 -P0 -r -n $((6 + ${#plantumlOptions[@]})) bash -c 'convertPuml $@' _
+) | xargs -0 -P0 -r -n $((7 + ${#plantumlOptions[@]})) bash -c 'convertPuml $@' _
 
 # shellcheck disable=SC2154
 if [[ "${optionContinuousIntegrationMode}" = "1" ]] && ((${#argPlantumlFiles[@]} == 0)); then
