🪛 (shellcheckLint) restored parallelization
- fixed as well log level default value to INFO
- Linux::getCodename and Linux::getDistributorId - avoid to source /etc/os-release
- added shellcheck disable to avoid false positives

diff --git a/bin/shellcheckLint b/bin/shellcheckLint
--- a/bin/shellcheckLint
+++ b/bin/shellcheckLint
@@ -397,7 +397,7 @@ Env::createDefaultEnvFile() {
 # @arg $@ list of default files to load at the end
 # @exitcode 1 if one of env files fails to load
 # @stderr diagnostics information is displayed
-# shellcheck disable=SC2120
+# shellcheck disable=SC2120,SC2329
 Env::requireLoad() {
   export REQUIRE_FUNCTION_ENV_REQUIRE_LOAD_LOADED=1
 
@@ -975,6 +975,7 @@ Log::logWarning() {
 # @env BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION int do log rotation if > 0
 # @exitcode 0 always successful
 # @stderr diagnostics information about log file is displayed
+# shellcheck disable=SC2329
 Log::requireLoad() {
   export REQUIRE_FUNCTION_LOG_REQUIRE_LOAD_LOADED=1
 
@@ -1153,6 +1154,7 @@ UI::drawLine() {
 # @env BASH_FRAMEWORK_THEME String theme to use
 # @env LOAD_THEME int 0 to avoid loading theme
 # @exitcode 0 always successful
+# shellcheck disable=SC2329
 UI::requireTheme() {
   export REQUIRE_FUNCTION_UI_REQUIRE_THEME_LOADED=1
 
@@ -1388,73 +1390,75 @@ Web::upgradeRelease() {
 
 declare -a BASH_FRAMEWORK_ARGV_FILTERED=()
 
+# shellcheck disable=SC2329
 beforeParseCallback() {
   Env::requireLoad
   UI::requireTheme
   Log::requireLoad
 }
 
+# shellcheck disable=SC2329
 copyrightCallback() {
   #
   # shellcheck disable=SC2155,SC2154,SC2250
   echo "Copyright (c) 2022-now François Chastanet"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListInfoVerboseCallback() {
   BASH_FRAMEWORK_ARGV_FILTERED+=(--verbose)
 }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListDebugVerboseCallback() {
   BASH_FRAMEWORK_ARGV_FILTERED+=(-vv)
 }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListTraceVerboseCallback() {
   BASH_FRAMEWORK_ARGV_FILTERED+=(-vvv)
 }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListEnvFileCallback() { :; }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListLogLevelCallback() { :; }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListDisplayLevelCallback() { :; }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListNoColorCallback() {
   BASH_FRAMEWORK_ARGV_FILTERED+=(--no-color)
 }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListThemeCallback() { :; }
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 updateArgListQuietCallback() { :; }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionHelpCallback() {
   Log::displayError "optionHelpCallback needs to be overridden"
   exit 0
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionVersionCallback() {
   # shellcheck disable=SC2154
   echo "${SCRIPT_NAME} version 3.0"
   exit 0
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionInfoVerboseCallback() {
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='--verbose'
   BASH_FRAMEWORK_ARGS_VERBOSE=${__VERBOSE_LEVEL_INFO}
   echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_INFO}" >>"${overrideEnvFile}"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionDebugVerboseCallback() {
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='-vv'
   BASH_FRAMEWORK_ARGS_VERBOSE=${__VERBOSE_LEVEL_DEBUG}
   echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_DEBUG}" >>"${overrideEnvFile}"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionTraceVerboseCallback() {
   # shellcheck disable=SC2034
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='-vvv'
@@ -1534,11 +1538,7 @@ optionLogLevelCallback() {
   echo "BASH_FRAMEWORK_LOG_LEVEL=${logLevel}" >>"${overrideEnvFile}"
 }
 
-optionLogLevelDefaultValueFunction() {
-  Log::getLevelText "${BASH_FRAMEWORK_LOG_LEVEL:-${__LEVEL_OFF}}"
-}
-
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionLogFileCallback() {
   local logFile="$2"
   echo "BASH_FRAMEWORK_LOG_FILE='${logFile}'" >>"${overrideEnvFile}"
@@ -1549,17 +1549,17 @@ optionLogFileDefaultValueFunction() {
   echo "${BASH_FRAMEWORK_LOG_FILE:-"${FRAMEWORK_ROOT_DIR}/logs/${SCRIPT_NAME}.log"}"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionQuietCallback() {
   echo "BASH_FRAMEWORK_QUIET_MODE=1" >>"${overrideEnvFile}"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionNoColorCallback() {
   UI::theme "noColor"
 }
 
-# shellcheck disable=SC2317 # if function is overridden
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionThemeCallback() {
   UI::theme "$2"
 }
@@ -1574,6 +1574,7 @@ displayConfig() {
   exit 0
 }
 
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionBashFrameworkConfigCallback() {
   if [[ ! -f "$2" ]]; then
     Log::fatal "Command ${SCRIPT_NAME} - Bash framework config file '$2' does not exists"
@@ -1605,6 +1606,7 @@ declare MIN_SHELLCHECK_VERSION="0.9.0"
 declare optionFormat="${optionFormatDefault}"
 declare -a shellcheckArgs=()
 
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 beforeParseCallback() {
   Env::requireLoad
   Linux::requireJqCommand
@@ -1614,6 +1616,8 @@ beforeParseCallback() {
 unknownOption() {
   shellcheckArgs+=("$1")
 }
+
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 shellcheckLintParseCallback() {
   # shellcheck disable=SC2154
   if [[ "${optionStaged}" = "1" ]] && ((${#argShellcheckFiles[@]} > 0)); then
@@ -1623,6 +1627,7 @@ shellcheckLintParseCallback() {
   shellcheckArgs=(-f "${optionFormat}")
 }
 
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionHelpCallback() {
   local shellcheckHelpFile
   shellcheckHelpFile="$(Framework::createTempFile "shellcheckHelp")"
@@ -1641,6 +1646,7 @@ optionHelpCallback() {
   exit 0
 }
 
+# shellcheck disable=SC2317,SC2329 # if function is overridden
 optionVersionCallback() {
   echo -e "${__HELP_TITLE_COLOR}${SCRIPT_NAME} version: ${__RESET_COLOR} 3.0"
   echo -e -n "${__HELP_TITLE_COLOR}shellcheck Version: ${__RESET_COLOR}"
@@ -1660,7 +1666,7 @@ declare optionBashFrameworkConfig=""
 declare optionInfoVerbose="0"
 declare optionDebugVerbose="0"
 declare optionTraceVerbose="0"
-declare optionLogLevel="optionLogLevelDefaultValueFunction"
+declare optionLogLevel="INFO"
 declare optionLogFile="optionLogFileDefaultValueFunction"
 declare optionDisplayLevel="optionDisplayLevelDefaultValueFunction"
 declare optionNoColor="0"
@@ -1694,7 +1700,7 @@ shellcheckLintCommandParse() {
   optionTraceVerbose="0"
   local -i options_parse_optionParsedCountOptionTraceVerbose
   ((options_parse_optionParsedCountOptionTraceVerbose = 0)) || true
-  optionLogLevel="optionLogLevelDefaultValueFunction"
+  optionLogLevel="INFO"
   local -i options_parse_optionParsedCountOptionLogLevel
   ((options_parse_optionParsedCountOptionLogLevel = 0)) || true
   optionLogFile="optionLogFileDefaultValueFunction"
@@ -2178,7 +2184,7 @@ shellcheckLintCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
 
-  Array::wrap2 ' ' 76 6 "    Default value: " "$(optionLogLevelDefaultValueFunction)"
+  Array::wrap2 ' ' 76 6 "    Default value: " "INFO"
   echo
 
   echo -e "  ${__HELP_OPTION_COLOR}--log-file <log-file>${__HELP_NORMAL} {single}"
@@ -2323,7 +2329,11 @@ Softwares::installShellcheck "${PERSISTENT_TMPDIR}/shellcheck"
 
 # shellcheck disable=SC2154
 getFiles() {
-  exclude="$(sed -n -E 's/^exclude=(.+)$/\1/p' "${FRAMEWORK_ROOT_DIR}/.shellcheckrc" 2>/dev/null || true)"
+  shellcheckrcFile="${FRAMEWORK_ROOT_DIR}/.shellcheckrc"
+  if [[ -f "${PWD}/.shellcheckrc" ]]; then
+    shellcheckrcFile="${PWD}/.shellcheckrc"
+  fi
+  exclude="$(sed -n -E 's/^exclude=(.+)$/\1/p' "${shellcheckrcFile}" 2>/dev/null || true)"
   if [[ -z "${exclude}" ]]; then
     exclude='^$'
   fi
@@ -2348,7 +2358,7 @@ getFiles() {
     fi
   ) |
     (grep -E -v "${exclude}" || true) |
-    LC_ALL=C.UTF-8 xargs -r -L 1 -n 1 -I@ bash -c "File::detectBashFile '@'"
+    LC_ALL=C.UTF-8 xargs -r -n 10 bash -c 'File::detectBashFile "$@"' arg0
 }
 
 shellcheckFiles() {
@@ -2363,37 +2373,28 @@ shellcheckFiles() {
   Log::displayInfo "${#files[@]} files to check using ${optionFormat} format"
 
   if ((${#files[@]} > 0)); then
-    local tmpDir
-    tmpDir="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-tools-shellcheck-XXXXXX)"
-    export tmpDir
-    local failuresFile
-    failuresFile="${tmpDir}/.failures"
-    export failuresFile
-    export FRAMEWORK_VENDOR_BIN_DIR
-
-    # shellcheck disable=SC2329
-    shellcheckFunction() {
+    shellcheckScript() {
+      set -o errexit -o pipefail
       if (($# == 0)); then
         return 0
       fi
       if [[ "${optionTraceVerbose}" = "1" ]]; then
         set -x
       fi
-      echo >&2 "Linting $* ..."
-      # shellcheck disable=SC2086,SC2154
-      "${FRAMEWORK_VENDOR_BIN_DIR}/shellcheck" ${shellcheckArgsStr} "$@"
-    }
-    export -f shellcheckFunction
+      if [[ "${debug}" = "1" ]]; then
+        echo 2>&1 "Running shellcheck on the following files: $*"
+      fi
 
-    shellcheckScript() {
-      set -o errexit -o pipefail
       file="$(md5sum <<<"$@")"
       declare shellcheckExit=0
-      shellcheckFunction "$@" >"${tmpDir}/${file%% *}" >&2 || shellcheckExit=$?
+      # shellcheck disable=SC2086,SC2154
+      "${PERSISTENT_TMPDIR}/shellcheck" ${shellcheckArgsStr} "$@" >"${tmpDir}/${file%% *}" >&2 || shellcheckExit=$?
       if ((shellcheckExit != 0)); then
         echo "$@" >>"${failuresFile}"
       fi
     }
+    export FRAMEWORK_VENDOR_BIN_DIR
+    export -f Log::displayDebug Log::computeDuration Log::logDebug Log::logMessage
     export -f shellcheckScript
 
     local -a xargsArgs=(
@@ -2411,15 +2412,19 @@ shellcheckFiles() {
     if [[ "${optionTraceVerbose}" = "1" ]]; then
       xargsArgs+=(-t)
     fi
-
+    local debug=0
+    if [[ "${BASH_FRAMEWORK_DISPLAY_LEVEL}" = "${__LEVEL_DEBUG}" ]]; then
+      debug=1
+    fi
     # shellcheck disable=SC2016,SC2154
     echo "${files[@]}" |
       optionTraceVerbose="${optionTraceVerbose}" \
         shellcheckArgsStr="${shellcheckArgs[*]}" \
         tmpDir="${tmpDir}" \
+        debug="${debug}" \
         failuresFile="${failuresFile}" \
         xargs "${xargsArgs[@]}" \
-        bash -c 'shellcheckScript "$@"' bash || true
+        bash -c 'shellcheckScript "$@" || true' bash || true
 
     if [[ "${optionFormat}" = "checkstyle" ]]; then
       (
@@ -2435,17 +2440,27 @@ shellcheckFiles() {
     elif [[ "${optionFormat}" = "json1" ]]; then
       jq -s 'map(.comments[])' "${tmpDir}/"* | jq '{"comments": .}'
     fi
-
-    # Check if any shellcheck calls failed
-    if [[ -f "${failuresFile}" ]]; then
-      return 1
-    fi
   else
     Log::displayWarning "no file provided"
   fi
 }
 
+declare tmpDir
+tmpDir="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-tools-shellcheck-XXXXXX)"
+export tmpDir
+declare failuresFile
+failuresFile="${tmpDir}/.failures"
+export failuresFile
+
 shellcheckFiles
+
+# Check if any shellcheck calls failed
+if [[ -f "${failuresFile}" ]]; then
+  cat "${failuresFile}" >&2
+  return 1
+else
+  Log::displaySuccess "All files passed shellcheck with ${optionFormat} format"
+fi
 
 }
 
