Stabilization (#8)
* stabilize Github::upgradeRelease
* header.tpl deduces ROOT_DIR when binary is a symlink

diff --git a/bin/shellcheckLint b/bin/shellcheckLint
--- a/bin/shellcheckLint
+++ b/bin/shellcheckLint
@@ -7,9 +7,10 @@
 
 # shellcheck disable=SC2034
 SCRIPT_NAME=${0##*/}
+REAL_SCRIPT_FILE="$(readlink -e "$(realpath "${BASH_SOURCE[0]}")")"
 # shellcheck disable=SC2034
-CURRENT_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
-BIN_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
+CURRENT_DIR="$(cd "$(readlink -e "${REAL_SCRIPT_FILE%/*}")" && pwd -P)"
+BIN_DIR="${CURRENT_DIR}"
 ROOT_DIR="$(cd "${BIN_DIR}/.." && pwd -P)"
 # shellcheck disable=SC2034
 SRC_DIR="${ROOT_DIR}/src"
@@ -154,7 +155,8 @@ Github::upgradeRelease() {
   local repo
 
   repo="$(Github::extractRepoFromGithubUrl "${releaseUrl}")"
-  Github::getLatestRelease "${repo}" latestVersion
+  Github::getLatestRelease "${repo}" latestVersion ||
+    Log::fatal "Repo ${repo} latest version not found"
   Log::displayInfo "Repo ${repo} latest version found is ${latestVersion}"
 
   local currentVersion="not existing"
@@ -300,7 +302,10 @@ Github::getLatestRelease() {
     "https://api.github.com/repos/${repo}/releases/latest"; then
     # shellcheck disable=SC2034
     resultRef="$(Version::githubApiExtractVersion <"${resultFile}")"
+    return 0
   fi
+  # display curl result in case of failure
+  cat >&2 "${resultFile}"
   rm -f "${resultFile}"
 }
 
@@ -350,6 +355,14 @@ Log::displayInfo() {
 Log::displayWarning() {
   echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
   Log::logWarning "$1"
+}
+
+# Display message using error color (red) and exit immediately with error status 1
+# @param {String} $1 message
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
 }
 
 # Retry a command 5 times with a delay of 15 seconds between each attempt
@@ -524,6 +537,12 @@ Log::logDebug() {
 # @param {String} $1 message
 Log::logError() {
   Log::logMessage "ERROR" "$@"
+}
+
+# log message to file
+# @param {String} $1 message
+Log::logFatal() {
+  Log::logMessage "FATAL" "$@"
 }
 
 # log message to file
