added Framework::installBinaries

diff --git a/bin/shellcheckLint b/bin/shellcheckLint
--- a/bin/shellcheckLint
+++ b/bin/shellcheckLint
@@ -113,33 +113,28 @@ export __HELP_EXAMPLE
 export __HELP_TITLE
 export __HELP_NORMAL
 
-Args::defaultHelpNoExit() {
-  local helpArg=$1
-  shift || true
-  # shellcheck disable=SC2034
-  local args
-  args="$(getopt -l help -o h -- "$@" 2>/dev/null)" || true
-  eval set -- "${args}"
-
-  while true; do
-    case $1 in
-      -h | --help)
-        if [[ "$(type -t "${helpArg}")" = "function" ]]; then
-          "${helpArg}" "$@"
-        else
-          Args::showHelp "${helpArg}"
-        fi
-        return 1
-        ;;
-      --)
-        break
-        ;;
-      *)
-        # ignore
-        ;;
-    esac
-  done
+Args::showHelp() {
+  local helpArg="$1"
+  echo -e "${helpArg}"
 }
+
+# missingBashFileList this file will contain the files that are not available when checking them
+# File::detectBashFile is used in conjunction with git ls-files
+# typical case for missing file is when a file is marked as deleted but not staged
+declare missingBashFileList
+missingBashFileList="$(mktemp -p "${TMPDIR:-/tmp}" -t bash-tools-buildBinFiles-before-XXXXXX)"
+export missingBashFileList
+
+File::detectBashFile() {
+  file="$1"
+  if [[ ! -f "${file}" ]]; then
+    echo "${file}" >>"${missingBashFileList}"
+  else
+    awk 'FNR==1{if ($0~"^#!.*bash") print FILENAME}' "${file}"
+  fi
+}
+
+export -f File::detectBashFile
 
 # upgrade given binary to latest github release using retry
 # @param {String}   targetFile target binary file (eg: /usr/local/bin/kind)
@@ -232,11 +227,6 @@ Version::getCommandVersionFromPlainText() {
   local argVersion="${2:---version}"
   "${command}" "${argVersion}" 2>&1 |
     Version::parse # keep only version numbers
-}
-
-Args::showHelp() {
-  local helpArg="$1"
-  echo -e "${helpArg}"
 }
 
 # Public: check if command specified exists or return 1
@@ -719,35 +709,12 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
 fi
 
 if [[ -z "${DEFAULT_ARGS+unset}" ]]; then
-  DEFAULT_ARGS=(--source-path=SCRIPTDIR --check-sourced -x -f checkstyle)
+  DEFAULT_ARGS=(-f tty)
 fi
 MIN_SHELLCHECK_VERSION="0.9.0"
-HELP="$(
-  cat <<EOF
-${__HELP_TITLE}Description:${__HELP_NORMAL} shellcheck wrapper
-- installs new shellcheck version(>${MIN_SHELLCHECK_VERSION}) automatically
-- lint this project files using default files filter
-- use the default options '${DEFAULT_ARGS[*]}' if no parameter specified
-
-${__HELP_TITLE}Usage:${__HELP_NORMAL} ${SCRIPT_NAME} <shellcheck options>
-
-${__HELP_TITLE}Author:${__HELP_NORMAL}
-[François Chastanet](https://github.com/fchastanet)
-
-${__HELP_TITLE}Source file:${__HELP_NORMAL}
-https://github.com/fchastanet/bash-tools-framework/tree/master/src/_binaries/shellcheckLint.sh
-
-${__HELP_TITLE}License:${__HELP_NORMAL}
-MIT License
-
-Copyright (c) 2022 François Chastanet
-
-EOF
-)"
-Args::defaultHelpNoExit "${HELP}" "$@" || true
 
 # check if command in PATH is already the minimal version needed
-if ! Version::checkMinimal "shellcheck" "--version" "${MIN_SHELLCHECK_VERSION}" >/dev/null 2>&1; then
+if ! Version::checkMinimal "${VENDOR_BIN_DIR}/shellcheck" "--version" "${MIN_SHELLCHECK_VERSION}" >/dev/null 2>&1; then
   install() {
     local file="$1"
     local targetFile="$2"
@@ -769,12 +736,100 @@ if ! Version::checkMinimal "shellcheck" "--version" "${MIN_SHELLCHECK_VERSION}" 
     install
 fi
 
-if (($# == 0)); then
+HELP="$(
+  cat <<EOF
+${__HELP_TITLE}Description:${__HELP_NORMAL} shellcheck wrapper
+
+${__HELP_TITLE}Usage:${__HELP_NORMAL} ${SCRIPT_NAME} [--help] prints this help and exits.
+${__HELP_TITLE}Usage:${__HELP_NORMAL} ${SCRIPT_NAME} [--staged] <shellcheck options>
+
+  [--staged] lint only staged git files which are beginning with a bash shebang.
+
+shellcheck wrapper that will
+- installs new shellcheck version(${MIN_SHELLCHECK_VERSION}) automatically
+- by default, lint all git files of this project which are beginning with a bash shebang
+  except if the option --staged is passed
+- use the default options '${DEFAULT_ARGS[*]}' if no parameter specified
+
+${__HELP_TITLE}Special configuration .shellcheckrc:${__HELP_NORMAL}
+use the following line in your .shellcheckrc file to exclude
+some files from being checked (use grep -E syntax)
+exclude=^bin/bash-tpl$
+
+${__HELP_TITLE}Author:${__HELP_NORMAL}
+[François Chastanet](https://github.com/fchastanet)
+
+${__HELP_TITLE}Source file:${__HELP_NORMAL}
+https://github.com/fchastanet/bash-tools-framework/tree/master/src/_binaries/shellcheckLint.sh
+
+${__HELP_TITLE}License:${__HELP_NORMAL}
+MIT License
+
+Copyright (c) 2022 François Chastanet
+
+${__HELP_TITLE}Shellcheck help:${__HELP_NORMAL}
+EOF
+)"
+
+declare -a savedOptions=("$@")
+
+# read command parameters
+# $@ is all command line parameters passed to the script.
+# -o is for short options like -h
+# -l is for long options with double dash like --help
+# the comma separates different long options
+options=$(getopt -n "$0" -l help,staged -o h -- "$@" 2>/dev/null || true)
+ONLY_STAGED=0
+eval set -- "${options}"
+while true; do
+  case $1 in
+    -h | --help)
+      Args::showHelp "${HELP}"
+      "${VENDOR_BIN_DIR}/shellcheck" --help
+      exit 0
+      ;;
+    --staged)
+      ONLY_STAGED=1
+      ;;
+    --)
+      break
+      ;;
+    *) ;;
+
+  esac
+  shift || true
+done
+
+# shell check options without this command option
+for i in "${!savedOptions[@]}"; do
+  if [[ "${savedOptions[i]}" = "--staged" ]]; then
+    unset 'savedOptions[i]'
+  fi
+done
+
+if ((${#savedOptions[@]} == 0)); then
   set -- "${DEFAULT_ARGS[@]}"
+else
+  set -- "${savedOptions[@]}"
 fi
 
 (
+  exclude="$(sed -n -E 's/^exclude=(.+)$/\1/p' "${ROOT_DIR}/.shellcheckrc" 2>/dev/null || true)"
+  if [[ -z "${exclude}" ]]; then
+    exclude='^$'
+  fi
+  export -f File::detectBashFile
   # shellcheck disable=SC2046
-  LC_ALL=C.UTF-8 shellcheck "$@" \
-    $(git ls-files --exclude-standard | grep -E '\.(sh|bats)$' || true)
+  LC_ALL=C.UTF-8 "${VENDOR_BIN_DIR}/shellcheck" "$@" $(
+    (
+      if [[ "${ONLY_STAGED}" = "1" ]]; then
+        git --no-pager diff --name-only --cached --diff-filter=audbx
+      else
+        git ls-files --exclude-standard -c -o -m
+      fi
+    ) |
+      xargs -L 1 -n 1 -I@ bash -c 'File::detectBashFile "@"' |
+      grep -E -v "${exclude}" | uniq ||
+      true
+  )
 )
