🔧(shellcheck): Improve shellcheck output handling and logging
Enhance the shellcheck linting process by refining output
management and error logging. This improves user
feedback during linting.

## 1. 🔧 Shellcheck Output Handling

- Add progress indication during shellcheck execution.
- Update error handling to log failures with a clear message instead of dumping raw output.
- Add error count display after processing shellcheck results
- Ensure correct display for formats checkstyle, json, json1 and tty

## 2. 🔧 Logging Enhancements

- Export additional logging functions for better information display.
- Ensure consistent logging of success and failure messages for shellcheck results.

diff --git a/bin/shellcheckLint b/bin/shellcheckLint
--- a/bin/shellcheckLint
+++ b/bin/shellcheckLint
@@ -468,8 +468,6 @@ File::detectBashFile() {
 # @set missingBashFileList String temp filepath that contains eventual missing files
 # @noargs
 File::detectBashFileInit() {
-  local -a files=("$@")
-  local file
   if [[ -n "${missingBashFileList}" ]]; then
     rm -f "${missingBashFileList}" || true
   fi
@@ -1683,7 +1681,7 @@ declare optionBashFrameworkConfig=""
 declare optionInfoVerbose="0"
 declare optionDebugVerbose="0"
 declare optionTraceVerbose="0"
-declare optionLogLevel="INFO"
+declare optionLogLevel="OFF"
 declare optionLogFile="optionLogFileDefaultValueFunction"
 declare optionDisplayLevel="optionDisplayLevelDefaultValueFunction"
 declare optionNoColor="0"
@@ -1717,7 +1715,7 @@ shellcheckLintCommandParse() {
   optionTraceVerbose="0"
   local -i options_parse_optionParsedCountOptionTraceVerbose
   ((options_parse_optionParsedCountOptionTraceVerbose = 0)) || true
-  optionLogLevel="INFO"
+  optionLogLevel="OFF"
   local -i options_parse_optionParsedCountOptionLogLevel
   ((options_parse_optionParsedCountOptionLogLevel = 0)) || true
   optionLogFile="optionLogFileDefaultValueFunction"
@@ -2201,7 +2199,7 @@ shellcheckLintCommandHelp() {
   echo -e "      - ${__OPTION_COLOR}DEBUG${__RESET_COLOR}"
   echo -e "      - ${__OPTION_COLOR}TRACE${__RESET_COLOR}"
 
-  Array::wrap2 ' ' 76 6 "    Default value: " "INFO"
+  Array::wrap2 ' ' 76 6 "    Default value: " "OFF"
   echo
 
   echo -e "  ${__HELP_OPTION_COLOR}--log-file <log-file>${__HELP_NORMAL} {single}"
@@ -2401,15 +2399,19 @@ shellcheckFiles() {
       fi
 
       file="$(md5sum <<<"$@")"
+      echo >&2 -n "."
       declare shellcheckExit=0
       # shellcheck disable=SC2086,SC2154
-      "${PERSISTENT_TMPDIR}/shellcheck" ${shellcheckArgsStr} "$@" >"${tmpDir}/${file%% *}" >&2 || shellcheckExit=$?
+      "${PERSISTENT_TMPDIR}/shellcheck" ${shellcheckArgsStr} "$@" \
+        >&2 >"${tmpDir}/${file%% *}" || shellcheckExit=$?
       if ((shellcheckExit != 0)); then
         echo "$@" >>"${failuresFile}"
       fi
+      echo >&2 -n "."
     }
     export FRAMEWORK_VENDOR_BIN_DIR
-    export -f Log::displayDebug Log::computeDuration Log::logDebug Log::logMessage
+    export -f Log::displayDebug Log::displayInfo Log::computeDuration \
+      Log::logInfo Log::logDebug Log::logMessage
     export -f shellcheckScript
 
     local -a xargsArgs=(
@@ -2442,19 +2444,38 @@ shellcheckFiles() {
         xargs "${xargsArgs[@]}" \
         bash -c 'shellcheckScript "$@" || true' bash || true
 
+    echo >&2
+    ((errorCount = 0)) || true
     if [[ "${optionFormat}" = "checkstyle" ]]; then
       (
         echo "<?xml version='1.0' encoding='UTF-8'?>"
         echo "<checkstyle version='4.3'>"
-        awk '/<checkstyle/{flag=1; next} /<\/checkstyle>/{flag=0} flag' "${tmpDir}/"*
+        awk '/<checkstyle/{flag=1; next} /<\/checkstyle>/{flag=0; next} flag' "${tmpDir}/"*
         echo "</checkstyle>"
       )
+      errorCount=$(awk -F 'errors="' '/<file/{if ($2 > 0) {count += $2}} END{print count}' "${tmpDir}/"*)
     elif [[ "${optionFormat}" = "json" ]]; then
-      (
-        jq '.[]' "${tmpDir}/"* | jq -s '.'
-      )
+      # format: [
+      # {"file":"file.sh","line":129,"endLine":129,"column":20,"endColumn":78,
+      #  "level":"style","code":2126,"message":"...","fix":null}
+      # ...]
+      jq -s '.[] | select(length > 0) | add' "${tmpDir}/"* | jq -s '.'
+      errorCount=$(jq -s 'map(length) | add' "${tmpDir}/"*)
     elif [[ "${optionFormat}" = "json1" ]]; then
+      # format: {"comments":[
+      # {"file":"file.sh","line":125,"endLine":125,"column":20,"endColumn":78,
+      #  "level":"style","code":2126,"message":"...","fix":null}
+      # ...]}
       jq -s 'map(.comments[])' "${tmpDir}/"* | jq '{"comments": .}'
+      errorCount=$(jq -s 'map(length) | add' "${tmpDir}/"*)
+    else
+      cat "${tmpDir}/"*
+      # shellcheck disable=SC2126 # grep -c not possible - we want to count the number of lines across all files
+      errorCount=$(grep -E "^In " "${failuresFile}" "${tmpDir}/"* 2>/dev/null | wc -l || true)
+    fi
+    if ((errorCount > 0)); then
+      Log::displayError "${errorCount} error(s) found by shellcheck"
+      return 1
     fi
   else
     Log::displayWarning "no file provided"
@@ -2472,7 +2493,7 @@ shellcheckFiles
 
 # Check if any shellcheck calls failed
 if [[ -f "${failuresFile}" ]]; then
-  cat "${failuresFile}" >&2
+  Log::fatal "Some files failed shellcheck"
   return 1
 else
   Log::displaySuccess "All files passed shellcheck with ${optionFormat} format"
