review fixes

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -146,6 +146,7 @@ Bats::installRequirementsIfNeeded() {
       "${BASH_FRAMEWORK_BATS_DEPENDENCIES_CHECK_TIMEOUT}"
   )" != "1" ]] \
     ; then
+    Log::displayInfo "Install or update bats requirements"
     Git::shallowClone \
       "https://github.com/bats-core/bats-core.git" \
       "${ROOT_DIR}/vendor/bats" \
@@ -245,21 +246,6 @@ Git::shallowClone() {
   )
 }
 
-# Number of seconds since last modification of the file
-# @param {String} file $1 file path
-# @return 1 if file does not exist
-# @output number of seconds since last modification of the file
-File::elapsedTimeSinceLastModification() {
-  local file="$1"
-  if [[ ! -f "${file}" ]]; then
-    return 1
-  fi
-  local lastModificationTimeSeconds diff
-  lastModificationTimeSeconds="$(stat -c %Y "${file}")"
-  ((diff = $(date +%s) - lastModificationTimeSeconds))
-  echo -n "${diff}"
-}
-
 # Public: log level off
 export __LEVEL_OFF=0
 # Public: log level error
@@ -280,25 +266,11 @@ export __LEVEL_INFO
 export __LEVEL_SUCCESS
 export __LEVEL_DEBUG
 
-# Display message using error color (red)
-# @param {String} $1 message
-Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
-  Log::logError "$1"
-}
-
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
   echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
   Log::logInfo "$1"
-}
-
-# Display message using warning color (yellow)
-# @param {String} $1 message
-Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
-  Log::logWarning "$1"
 }
 
 # lazy initialization
@@ -397,11 +369,33 @@ Env::load() {
   set +o allexport
 }
 
+# Number of seconds since last modification of the file
+# @param {String} file $1 file path
+# @return 1 if file does not exist
+# @output number of seconds since last modification of the file
+File::elapsedTimeSinceLastModification() {
+  local file="$1"
+  if [[ ! -f "${file}" ]]; then
+    return 1
+  fi
+  local lastModificationTimeSeconds diff
+  lastModificationTimeSeconds="$(stat -c %Y "${file}")"
+  ((diff = $(date +%s) - lastModificationTimeSeconds))
+  echo -n "${diff}"
+}
+
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
   echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
   Log::logDebug "$1"
+}
+
+# Display message using error color (red)
+# @param {String} $1 message
+Log::displayError() {
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
+  Log::logError "$1"
 }
 
 # Display message using info color (bg light blue/fg white)
@@ -423,6 +417,13 @@ Log::displaySkipped() {
 Log::displaySuccess() {
   echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
   Log::logSuccess "$1"
+}
+
+# Display message using warning color (yellow)
+# @param {String} $1 message
+Log::displayWarning() {
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+  Log::logWarning "$1"
 }
 
 # log message to file
