Performance optimizations
Performance optimizations:
- using bash variable expansion instead of dirname and basename
- removed usage of readlink and pwd where not useful
- call mkdir if directory does not exist
- replaced grep usage by bash regexp check on Assert::validVariableName
- replaced sed usage by bash expansion on
  - Backup::file
  - Linux::Wsl::getKeyFromWslpathOptions
  - Compiler::Facade::generateFacadeScript
  - WSL_DISTRO_NAME computation in Linux::Wsl::initEnv
- Created new set of wsl function to get wslpath and wslvar data in a more performant way.
  Load cache file first time as associative array.
  - Cache::getPropertyValue2
  - Linux::Wsl::cachedWslpath2
  - Linux::Wsl::cachedWslpathFromWslVar2
  - Linux::Wsl::cachedWslvar2
  Old equivalent functions are marked as deprecated.
- Linux::getCodename and Linux::getDistributorId are using source /etc/os-release intead
  of lsb_release -a
- Log duration based on EPOCHREALTIME variable instead of date command

Changes:
- Linux::getDistributorId and Linux::getCodename returned value can be slightly
  different (case change)
- Linux::Wsl::getKeyFromWslpathOptions some cleaning on the key
- Linux::Wsl::originalWslpath filters unwanted eols

Deprecations:
- Linux::Wsl::cachedWslpath : use Linux::Wsl::cachedWslpath2 instead
- Cache::getPropertyValue : use Cache::getPropertyValue2 instead
- Linux::Wsl::cachedWslpathFromWslVar : use Linux::Wsl::cachedWslpathFromWslVar2 instead
- Linux::Wsl::cachedWslvar : use Linux::Wsl::cachedWslvar2 instead

diff --git a/src/Compiler/testsData/frameworkLint b/src/Compiler/testsData/frameworkLint
--- a/src/Compiler/testsData/frameworkLint
+++ b/src/Compiler/testsData/frameworkLint
@@ -9,7 +9,7 @@
 SCRIPT_NAME=${0##*/}
 REAL_SCRIPT_FILE="$(readlink -e "$(realpath "${BASH_SOURCE[0]}")")"
 # shellcheck disable=SC2034
-CURRENT_DIR="$(cd "$(readlink -e "${REAL_SCRIPT_FILE%/*}")" && pwd -P)"
+CURRENT_DIR="${REAL_SCRIPT_FILE%/*}"
 FRAMEWORK_BIN_DIR="${CURRENT_DIR}"
 FRAMEWORK_ROOT_DIR="$(cd "${FRAMEWORK_BIN_DIR}/.." && pwd -P)"
 # shellcheck disable=SC2034
@@ -24,7 +24,9 @@ export PATH="${FRAMEWORK_BIN_DIR}":"${FRAMEWORK_VENDOR_BIN_DIR}":${PATH}
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 # prepare bin directory for eventual bin files generated by Compiler::Embed::embed*
-mkdir -p "${TMPDIR}/bin"
+if [[ ! -d "${TMPDIR}/bin" ]]; then
+  mkdir -p "${TMPDIR}/bin"
+fi
 export PATH="${TMPDIR}/bin":${PATH}
 
 # temp dir cleaning
@@ -535,9 +537,11 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
     BASH_FRAMEWORK_LOG_LEVEL=${__LEVEL_OFF}
     export BASH_FRAMEWORK_LOG_LEVEL
   elif [[ ! -f "${BASH_FRAMEWORK_LOG_FILE}" ]]; then
-    if ! mkdir -p "$(dirname "${BASH_FRAMEWORK_LOG_FILE}")" 2>/dev/null; then
-      BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
-      Log::displayWarning "Log dir cannot be created $(dirname "${BASH_FRAMEWORK_LOG_FILE}")"
+    if [[ ! -d  "${BASH_FRAMEWORK_LOG_FILE%/*}" ]]; then
+      if ! mkdir -p "${BASH_FRAMEWORK_LOG_FILE%/*}" 2>/dev/null; then
+        BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
+        Log::displayWarning "Log dir cannot be created ${BASH_FRAMEWORK_LOG_FILE%/*}"
+      fi
     fi
     if ! touch --no-create "${BASH_FRAMEWORK_LOG_FILE}" 2>/dev/null; then
       BASH_FRAMEWORK_LOG_LEVEL=__LEVEL_OFF
